### ISSUE TITLE
Eslint/prettier: harmonization of rules and config format

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1024]
Using prettier and eslint greatly improve code reading quality inside a project. To apply this over multiple projects we want to propose guidelines to harmonize set of rules and configuration format for eslint and prettier 

Currently:
We use eslint on different projects like murmur and datashare client and have a different set of rules and different config format.
- https://github.com/ICIJ/murmur/blob/8caebb53b19d26a4a68d6f80d57b4bdf4cd3ab61/package.json
- https://github.com/ICIJ/datashare-client/blob/master/.eslintrc.js

Objectives: 
- [ ] Agree on a convention for configuration (external file, inside package.json ...)
- [ ] Agree on a convention for eslint (level of strictness, rules to remove)
- [ ] Agree on a convention for prettier 
- [ ] Update public repositories (murmur, datashare client)
- [ ] Update private repositories

**Comment by marieglr** [comment]
we could publish an eslint-config-icij plugin to easily share it accross projects :eyes:

**Comment by Soliine** [comment]
Same config for all projects

**Comment by caro3801** [comment]
@marieglr remarks from https://github.com/ICIJ/murmur/pull/68, we will need consistency for : 
- import extensions
- spaces inside brackets
