### ISSUE TITLE
When using contextualized facets, choosing a filtering value or search decontextualizes FacetPath

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#104]
To reproduce:

* activate "contextualized facet"
* see the paths are filtered in the facet
* change a filter (like the language)
* see the paths are **not** filtered anymore in the facet

**Comment by annelhote** [comment]
This seems to be a little bit different right now.
To reproduce :
1. Set the search as "contextualized".
2. Filter on a language
=> Everything works as expected
3. Reset filters
4. Filter on the same language
=> Here is the bug.
So the "Reset filters" functionality seems to reset the "contextualized" search too. It os not supposed to do so.
