### ISSUE TITLE
feat: add a histogram on the creation date filter 

### ISSUE THREAD

**Issue by marieglr** [ICIJ/datashare#1041]
Currently, Datashare has a "Creation Dates" filter allowing to select a date range to see all documents created in the selected timeframe. 

We would like for the date picker to have the format of a histogram, which would allow the user to visualise the amount of document created on each date. A range should be selectable in this histogram to filter on.

**Comment by pirhoo** [comment]
This will be implemented through a new component on Murmur.

**Comment by caro3801** [comment]
Murmur component PR done by @pirhoo here https://github.com/ICIJ/murmur/pull/75
