### ISSUE TITLE
Follow shortcuts/symbolic links when scanning a directory

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#106]
As a user I'd like to be able to plug an USB key or external drive and make a shortcut to it into the `Datashare` directory

**Comment by bamthomas** [comment]
As a user I'd like to be able to plug an USB key or external drive and make a shortcut to it into the `Datashare` directory

**Comment by bamthomas** [comment]
A user contacted us to index a 16M docs drive with datashare

**Comment by Soliine** [comment]
See #145
