### ISSUE TITLE
Perform proximity search with wildcard operator.

### ISSUE THREAD

**Issue by FacetedGlass** [ICIJ/datashare#1068]
Hello, I have a question.
I try to recreate dtSearch query _Joh* w/2 Doe_ in Datashare and I ran into trouble.
I know, that search queries like _"Joh* Doe"~2_ is not supported in Datashare and Elasticsearch, but in Elasic I can use Span queries to achieve what I whant.
So, does Datashare some workaround to perform proximity search with wildcard operator?

**Comment by pirhoo** [comment]
Hi, Datashare user interface doesn't support span queries but you can always use this API to perform them with CURL:

```
curl -XPOST -H "Content-Type: application/json" -d '{
  "query": {
    "span_near": {
      "clauses": [
        {
          "span_multi": {
            "match": {
              "wildcard": {
                "content": "joh*"
              }
            }
          }
        },
        {
          "span_term": {
            "content": "doe"
          }
        }
      ],
      "slop": 2,
      "in_order": true
    }
  }
}
' "http://localhost:8080/api/index/search/local-datashare/_search"
```
