### ISSUE TITLE
refactor: migrate batch search to AMQP

### ISSUE THREAD

**Issue by ClemDoum** [ICIJ/datashare#1080]
Depends on #1079, #1081 and #1283  

At the end of this story, BatchSearchLoop and BatchDownloadLoop should be the same. 

* [x] do #1283 to make it easier for this story
* [x] refactor Event -> Message
* [x] remove `BatchDownloadCleaner` from `BatchDownloadLoop` and any specific batch download coupling then rename class
* [x] use `TaskView<T>` for sending batch search to worker(s)
* [x] use `TaskManager.startTask(String id, String taskName, User user)` like  `BatchDownload` 
* [x] use TaskRunnerLoop for batch search
* [x] adapt error handling with batch search (repost, dead letter queue) in TaskRunnerLoop
* [x] remove method `startTask(Callable<V> task, ...)` to use same methods as BatchDownload and BatchSearch
* [x] implement AMQP for `BatchSearch`
* [ ] use AMQP for working queues between SCAN, INDEX, NLP (full redis, full AMQP, full memory) if possible
* [x] manually test non regression with memory, Redis, AMQP

**Comment by caro3801** [comment]
Closed in favor of testing issues in Sprint 25:
- Enhancement: AMQP for working queues between SCAN, INDEX, NLP (full redis, full AMQP, full memory) if possible
- batch search migration #1372
- test of the installers
