### ISSUE TITLE
feat(OpenAPI): Fluent http generation of JSON file

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#1082]
For now we have an API documentation generated by the CI [here](https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API).

We would like to have a more convenient API description with [openapi](https://swagger.io/specification/).

The idea would be to update [fluent-http-apigen](https://github.com/ICIJ/fluent-http-apigen) and generate json openapi file.

**Comment by pirhoo** [comment]
* [ ] refactor Datashare backend to implement this.
