### ISSUE TITLE
Datashare doesn't start on mac OS

### ISSUE THREAD

**Issue by stchris** [ICIJ/datashare#1139]
**Describe the bug**
Following the [installation instructions](https://icij.gitbook.io/datashare/local-mode/install-datashare-on-mac) on mac OS results in an Application that doesn't start, apparently due to no Java Runtime being available.

**To Reproduce**
1. Double-click on the installed Datashare.app Application
2. A window pops up and gets closed immediately, a terminal window stays open
3. The application does not start

**Expected behavior**
The application starts up correctly. The documentation mentions how to install a Java Runtime.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: mac OS 12.5.1
 - Browser: Firefox
 - Version: 115.0

**Additional context**
I had to do the following steps as a workaround:

- `brew install java`
- `brew link java --force`
- in `/Applications/Datashare.app/Contents/MacOS/Datashare.command` change the line that starts with `java_bin=` to `java_bin="/opt/homebrew/opt/openjdk/bin/java"` (there was no `java_home` binary on my system) 

**(Optional) Your contact, availabilities and timezone if a video call with screensharing is needed**
-

**Comment by pirhoo** [comment]
Hi @stchris, thanks for the detailed report!

This is a known issue that is difficult to fix yet (installing brew from a script can be challenging) but we should certainly add more documentation about existing workarounds.
