### ISSUE TITLE
The server is not connected

### ISSUE THREAD

**Issue by Aurbu** [ICIJ/datashare#1163]
**Describe the bug**
When I open the  data share workspace  it says ''The server is not connected''

Desktop (please complete the following information):**

 - Browser: e.g. Chrome, 
![Screenshot 2023-08-09 091833](https://github.com/ICIJ/datashare/assets/141772484/a9822255-41d4-47de-bc05-6c0a983dcc6a)

**Additional context**
Please contact me at any time at arnas.urbutis@wordleylaw.com

**Comment by bamthomas** [comment]
@Aurbu could you provide the server logs or the console logs?

**Comment by Aurbu** [comment]
Do you mean my login with password?



Arnas Urbutis

Trainee Solicitor

Wordley Partnership



11 Leadenhall Street, London, EC3V 1LP

T: +44 (0) 20 3924 3260 | M: +44 (0) 7729 779 688

www.wordleylaw.com<http://www.wordleylaw.com/>





Partners: Alison Proctor LLP, Costas Frangeskides LLP, Graham Denny LLP, Nicolas Foster LLP, Paul Wordley LLP, Simon Schindler LLP



Wordley Partnership is a partnership registered in England and Wales. A firm authorised and regulated by the Solicitors Regulation Authority, Number 656370.



This email (including any attachments) is confidential, protected by copyright and may be privileged. It is for the exclusive use of the intended recipient(s). If you have received it in error, please notify the sender immediately by emailing a response before deleting the email completely from your computer, and note that any storage, copying or dissemination is prohibited.

________________________________

**Comment by Aurbu** [comment]
Dear Sirs,

Could help to solve this issue? It's really urgent !


***@***.***
Arnas Urbutis
Trainee Solicitor
Wordley Partnership

11 Leadenhall Street, London, EC3V 1LP
T: +44 (0) 20 3924 3260 | M: +44 (0) 7729 779 688
www.wordleylaw.com<http://www.wordleylaw.com/>


Partners: Alison Proctor LLP, Costas Frangeskides LLP, Graham Denny LLP, Nicolas Foster LLP, Paul Wordley LLP, Simon Schindler LLP

Wordley Partnership is a partnership registered in England and Wales. A firm authorised and regulated by the Solicitors Regulation Authority, Number 656370.

This email (including any attachments) is confidential, protected by copyright and may be privileged. It is for the exclusive use of the intended recipient(s). If you have received it in error, please notify the sender immediately by emailing a response before deleting the email completely from your computer, and note that any storage, copying or dissemination is prohibited.

**Comment by pirhoo** [comment]
No we meant the logs that shows in Datashare terminal (the black windows that appears when you start Datashare). Without those detail we cannot provide any help.

**Comment by Aurbu** [comment]
Dear Pierre

Many thanks for your prompt reply.

See below screenshots.


Part 1 /3

***@***.***

Part 2/3

***@***.***

Part 3/3

***@***.***
***@***.***
Arnas Urbutis
Trainee Solicitor
Wordley Partnership

11 Leadenhall Street, London, EC3V 1LP
T: +44 (0) 20 3924 3260 | M: +44 (0) 7729 779 688
www.wordleylaw.com<http://www.wordleylaw.com/>


Partners: Alison Proctor LLP, Costas Frangeskides LLP, Graham Denny LLP, Nicolas Foster LLP, Paul Wordley LLP, Simon Schindler LLP

Wordley Partnership is a partnership registered in England and Wales. A firm authorised and regulated by the Solicitors Regulation Authority, Number 656370.

This email (including any attachments) is confidential, protected by copyright and may be privileged. It is for the exclusive use of the intended recipient(s). If you have received it in error, please notify the sender immediately by emailing a response before deleting the email completely from your computer, and note that any storage, copying or dissemination is prohibited.

**Comment by pirhoo** [comment]
Hello @Aurbu, the logs are still missing from your previous message. We cannot provide help without it.

**Comment by Aurbu** [comment]
I have provided screenshots with log details (as you advised)

**Comment by pirhoo** [comment]
They are not visible on Github. You have to share them directly in this conversation so we can see them.

**Comment by Aurbu** [comment]
See attached

![3 of 3](https://github.com/ICIJ/datashare/assets/141772484/809ca127-2060-49bf-a7f6-223cf38b0efd)
![2 of 3](https://github.com/ICIJ/datashare/assets/141772484/579289ea-b354-4e0c-a437-1422c4655ff4)
![1of 3](https://github.com/ICIJ/datashare/assets/141772484/6c7b83d9-6e45-4f5d-956e-ff13a9fbd5c7)

**Comment by Aurbu** [comment]
Can you see screenshots now?

**Comment by bamthomas** [comment]
yes thank you for the feedback. 
It seems there is an issue with your Elasticsearch index files on disk.

What you can do (if your index is not hard to rebuild) is to remove the files.
They are located in your user local data : 
`\Users\kfinc\AppData\Roaming\Datashare\index`

Remove all the files here and relaunch datashare. It should restart normally and will recreate the local index files.
