### ISSUE TITLE
feat: create dynamic ES name field

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#1173]
**Is your feature request related to a problem? Please describe.**
Related to the [sort by filename issue](https://github.com/ICIJ/datashare/issues/1103), We want to create a new ElasticSearch field to store the filename (`resourcename` for docs, `title` for emails, `subject` for tweets, etc...)  in lowercase in order to perform case insensitive sort.

**Comment by pirhoo** [comment]
I would suggest we create two fields:

* `name` based on resourcename for docs, title for emails, subject for tweets, etc...
* `nameNorm` a sanitized version of `name` (lowercase + no accentuated characters)

**Comment by mvanzalu** [comment]
We would probably add those 2 fields in [this method](https://github.com/ICIJ/datashare/blob/a4fece29dd1214a35f8d73b52a36d51425b16cfe/datashare-index/src/main/java/org/icij/datashare/text/indexing/elasticsearch/ElasticsearchSpewer.java#L134)
