### ISSUE TITLE
As a `DEVELOPER` I should be able to create extension tasks

### ISSUE THREAD

**Issue by ClemDoum** [ICIJ/datashare#1185]
**Is your feature request related to a problem? Please describe.**
Currently as a developper it's not possible to create tasks from a Datashare extension:
- the `TaskManager` interface  is not accessible from the extension since it's in `datashare.app.tasks`
- the `TaskView` class is not accessible either
- it's not possible to get the app `TaskManager` through the `mode.get(TaskManager.class)` since the `CommonMode` and its Guice adapter are not accessible to the extension

**Describe the solution you'd like**
Developer of extensions should be able to create/schedule/access/delete tasks one ways or another.

Potential solutions would involve:
- making the main `TaskManager` accessible to extensions (moving the interface to the API ? + dependency injection ?)
- letting the frontend directly create/schedule/access/delete arbitrary tasks through `TaskResource`. While being simpler this options offers less control

**Comment by pirhoo** [comment]
Pending https://github.com/ICIJ/datashare/issues/1080

**Comment by ClemDoum** [comment]
Replaced by #1384
