### ISSUE TITLE
Facets go down when document opens with overlay

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#119]
Caution: if there is no overlay, you cannot see this bug.
To reproduce:
- resize your window on small size
- open a doc
- you see that facets on the left go down

**Comment by pirhoo** [comment]
Yeah I saw that, I'm not sure there is an easy fix yet. We might need to use a javascript lib to handle sticky boxes instead of relying only on CSS.

**Comment by pirhoo** [comment]
This might help https://github.com/eddiemf/vue-affix
