### ISSUE TITLE
Show applied filters in search results and allow to unselect each of them

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#121]
When a user search for some words and/or tickes some filters:
- the number of results and the number of documents appear in the sentence : "_690 results in 2 documents for:_" 
- then each query and each ticked filter appear by chronological order (least to most recent query/filter added) and can be removed by clicking on a cross

In the example below, user queried "netflix" and "gold" and then ticked "PDF":
![Sd4](https://user-images.githubusercontent.com/17233829/55164835-a9499380-516c-11e9-9264-0bc752c8411a.png)

**Comment by annelhote** [comment]
Consider exact match as one string !

**Comment by annelhote** [comment]
Remove "NOT" from applied filters.

**Comment by annelhote** [comment]
Use the lib "lucene" : https://www.npmjs.com/package/lucene.
