### ISSUE TITLE
feat: choose installation folders in Windows

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#1222]
**Is your feature request related to a problem? Please describe.**
We want to be able to choose the installation folders for Datashare app and for its data (index, models, docs, plugins/extensions...)

**Comment by LeoGe2022** [comment]
Alternatively, let the user choose the data folder when creating a new project.
So far the default datashare root is in the %userprofile% (windows edition) but this is usually C: driver that has not very large space.
I have to manually hacked the .bat, .conf and .db files to change the root folder to another driver.
