### ISSUE TITLE
Overwrite the latest version of Datashare

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#123]
For Macs and Windows, how to reproduce:
- open your current version of Datashare
- download a newest version of Datashare
- if Docker is still running, when you open Datashare, you will still open the current version of Datashare, not the latest.

Today, users can resolve this by running "docker rm -f [Datashare's container ID]" in their Terminal. We would like to allow users not to do this and make Datashare automatically open the latest version downloaded.

**Comment by bamthomas** [comment]
Should be fixed with version > 1.64.2
