### ISSUE TITLE
Can't preview pdf document

### ISSUE THREAD

**Issue by abdelhakel** [ICIJ/datashare#1230]
**Describe the bug**
Impossible to preview a pdf document. Got the following error message in the preview tab : 
{"error":"You are not allowed to download this document"}

I'm using 13.2.6 version.

Thanks for your help !

**Comment by pirhoo** [comment]
Hi @abdelhakel, are you on Windows or Mac? You cannot download any documents from your Datashare instance?

**Comment by abdelhakel** [comment]
yes, sorry. I am working on MacOS Ventura installed on a MacBook Pro M2, 2023.
I cannot preview or even download a document. Even if the doc was uploaded from my Datashare folder.

**Comment by pirhoo** [comment]
OK thanks! Is this the first time you install Datashare on this computer? 

We had an issue prevent download on projects created with past version of Datashare, that might why :/

**Comment by abdelhakel** [comment]
No, its not the first time. I started with version 10.7.2. Then i upgraded to 10.9.1, 10.15.3, 11.0.0, 11.1.9, 13.1.2.
And now i use 13.2.6.
I still can see the datashare-dist-XX.X.X-all.jar files in the /Applications/Datashare.app/Contents/Resources/ folder.
Is there a workaround or known solution to that problem ?

**Comment by zarinekharazian** [comment]
I believe I am having this same problem - I am using version 13.3 on a 2020 Intel Macbook Pro running Ventura. I can't preview any documents, including PDFs or JPEGS in my Datashare folder.

**Comment by pirhoo** [comment]
Sorry to hear that @zarinekharazian! 

We'll discuss the potential solutions today and will get back to you.

**Comment by abdelhakel** [comment]
So, i, can confirm that this workaround [https://github.com/ICIJ/datashare/issues/1164#issuecomment-1706271174](https://github.com/ICIJ/datashare/issues/1164#issuecomment-1706271174) worked for me.

**Comment by pirhoo** [comment]
The version `13.3.2` fixes that issue. Thanks you all for reporting the problem!

**Comment by zarinekharazian** [comment]
I can confirm it works for me! Awesome, thanks!
