### ISSUE TITLE
When clicking on "back to search results", user go to first page instead of current

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#125]
How to reproduce:
- search for a term that is mentioned in more than 25 documents
- click on "Go to next page" and stay on page 2
- open any document of page 2
- click "Back to search results"
- you arrive on page 1 of results. 

You would like to arrive on page 2.

**Comment by annelhote** [comment]
Another linked bug :
- search for anything
- go to the second page of results
- refresh
=> I'm on the first page of results, but I would like to be on the second page !

**Comment by pirhoo** [comment]
I think this can be solved easily by passing the page number to the URL.

**Comment by annelhote** [comment]
@pirhoo currently working on it !
