### ISSUE TITLE
unable to use basic authFilter (server mode)

### ISSUE THREAD

**Issue by liabozarth** [ICIJ/datashare#1255]
**Describe the bug**

I can successfully log-in once. But after I log out, and try to log back in, it doesn't work.

**To Reproduce**
part of the docker-compose.yml, added the lines
`      --authFilter org.icij.datashare.session.BasicAuthAdaptorFilter
      --authUsersProvider org.icij.datashare.session.UsersInDb
`
to original: 
` command: >-
      --mode SERVER
      --dataDir /home/datashare/Datashare
      --authFilter org.icij.datashare.session.YesCookieAuthFilter
      --busType REDIS
      --batchQueueType REDIS
      --dataSourceUrl jdbc:postgresql://postgresql/datashare?user=datashare\&password=password
      --defaultProject secret-project
      --elasticsearchAddress http://elasticsearch:9200
      --messageBusAddress redis://redis:6379
      --queueType REDIS
      --redisAddress redis://redis:6379
      --rootHost http://localhost:8080
      --sessionStoreType REDIS
      --authFilter org.icij.datashare.session.BasicAuthAdaptorFilter
      --authUsersProvider org.icij.datashare.session.UsersInDb
      --sessionTtlSeconds 43200
      --tcpListenPort 8080
`

**Expected behavior**
being able to log out and log in without an issue

**Screenshots**

**Desktop (please complete the following information):**
-ubuntu 20.04

**Additional context**

**(Optional) Your contact, availabilities and timezone if a video call with screensharing is needed**
For any private information, please consider sending an email to datashare@icij.org.

**Comment by pirhoo** [comment]
Hi @liabozarth, thanks for reporting the isse. Any log in the Datashare container?

**Comment by liabozarth** [comment]
I disabled the auth for now. I'll update this when I have a chance to test with auth again.
