### ISSUE TITLE
Launch failing on MacOS -- insecure directories

### ISSUE THREAD

**Issue by cimar** [ICIJ/datashare#1256]
Trying to run a new, completed install of DataShare on macOS Monterrey 12.5.1.

When I click the icon in "Applications", Terminal launches, but looks like it's stalling out (log below). Datashare does not open a browser window. I tried accessing `localhost:8080` from multiple browsers (Brave, Chrome, Safari) but the connection is refused.

```Last login: Fri Nov 10 17:53:56 on ttys008
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? /Applications/Datashare.app/Contents/MacOS/Datashare.command ; exit;
compinit: initialization aborted
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? Applications/Datashare.app/Contents/MacOS/Datashare.command ; exit;
compinit: initialization aborted
complete:13: command not found: compdef
172086@EWS2101441 ~ % pplications/Datashare.app/Contents/MacOS/Datashare.command ; exit;
zsh: no such file or directory: pplications/Datashare.app/Contents/MacOS/Datashare.command

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by pirhoo** [comment]
Hi @cimar, looks like you have a permission problems caused by zsh. I don't think that's a problem with Datashare itself. 

Some users reported being able to fix it with this command:

```
compaudit | xargs chmod g-w
```

More here:

https://github.com/zsh-users/zsh-completions/issues/680
