### ISSUE TITLE
Documenting the CLI arguments for datashare server mode

### ISSUE THREAD

**Issue by liabozarth** [ICIJ/datashare#1259]
Hi, I'm uploading images to datashare server using the code block from the documentation (see code block below). But, our server is pretty small and we are uploading 2K+ images, it's eating up all our CPU/RAM. Is there a **thread_num** kind of argument I can pass in here. I did a code search on the git repo, but didn't find anything. Also, if there is documentation link where all the possible arguments and their effects are listed, that would be great!

```
docker compose exec datashare_web /entrypoint.sh \
  --mode CLI \
  --stage SCAN,INDEX \
  --defaultProject secret-project \
  --elasticsearchAddress http://elasticsearch:9200 \
  --dataDir /home/datashare/Datashare/
```

**Comment by pirhoo** [comment]
Hello,

`--help` will do the trick:

```
docker run -it icij/datashare:13.6.0 --help
```

You will see we have several parameters such as `--parallelism <Integer>`, --parserParallelism <Integer>` or `--nlpParallelism <Integer>`.

**Comment by liabozarth** [comment]
ah, thanks!
