### ISSUE TITLE
About enabling basic auth in local mode

### ISSUE THREAD

**Issue by a3sroot** [ICIJ/datashare#1273]
Hi,
      The plugin feature in local mode and analyze your documents in tasks work very well.Instead, service mode does not have these nice-to-have features, but basic authentication cannot be enabled in local mode.

<img width="940" alt="image" src="https://github.com/ICIJ/datashare/assets/81551286/cf36c0b9-aef0-43d3-bad8-436dcef58b20">
<img width="520" alt="image" src="https://github.com/ICIJ/datashare/assets/81551286/31b6a4a3-8014-495f-bc3d-fd7849bcc775">

**Comment by pirhoo** [comment]
The main difference between the SERVER mode and the LOCAL mode is the ability to handle multi-tenancy in the application. **This is by design** because multi-tenancy can have many impacts on the application.
