### ISSUE TITLE
cannot log in normally when the mode is server mode.

### ISSUE THREAD

**Issue by a3sroot** [ICIJ/datashare#1279]
If Database login is configured, I will be redirected to the login page after successful login. 
Welcome to datashare will appear.But obviously I don't have oauth2 authentication enabled.
<img width="900" alt="image" src="https://github.com/ICIJ/datashare/assets/81551286/4aa5e599-8f01-4f4b-8eb4-d8ded05e43fa">

Later I realized that I needed the cookie to have a _ds_session_id attached to it. Only then can you jump to the normal use of the interface.
BasicAuthAdaptorFilter does not return cookies.

Version：13.8.1

web configure
```
      --mode SERVER
      --dataDir /home/datashare/Datashare    
      --busType REDIS
      --batchQueueType REDIS
      --dataSourceUrl jdbc:postgresql://postgresql/datashare?user=datashare\&password=password 
      --defaultProject secret-project
      --elasticsearchAddress http://xxxxxx@10.xxxxxx:9200
      --messageBusAddress redis://redis:6379
      --queueType REDIS
      --redisAddress redis://redis:6379  
      --rootHost http://xxxxxx
      --sessionStoreType REDIS
      --sessionTtlSeconds 43200
      --tcpListenPort 8080
      --authFilter org.icij.datashare.session.BasicAuthAdaptorFilter
      --authUsersProvider org.icij.datashare.session.UsersInDb
```

**Comment by a3sroot** [comment]
BasicAuthAdaptorFilter No context.setCurrentUser configuration

**Comment by a3sroot** [comment]
@bamthomas

**Comment by bamthomas** [comment]
`BasicAuthAdaptorFilter` does not return cookie because it's not based on cookie, it's based on basic auth that means with `Authorization` header. 

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

**Comment by a3sroot** [comment]
> authentication

You're right, it did pop up a window asking me to enter my account and password.
However, the BasicAuthAdaptorFilter interface does not return the uid under the /api/user/me interface, which makes it impossible for the front-end to determine the logged-in user.


From there the front end will jump here.
![image](https://github.com/ICIJ/datashare/assets/81551286/484b71c3-eb24-4b0c-9023-dab5933f663a)

**Comment by a3sroot** [comment]
I made a suggestion for a fix. @bamthomas 
https://github.com/ICIJ/datashare-client/pull/342/
