### ISSUE TITLE
feat: The search syntax can be set for dirname

### ISSUE THREAD

**Issue by a3sroot** [ICIJ/datashare#1280]
MODE SERVER

PATHS is empty in Server mode, I want to be able to search by dirname so I can set the directory as well.
<img width="336" alt="image" src="https://github.com/ICIJ/datashare/assets/81551286/dc45d9d4-f0b6-49e3-8179-5bb7c33156df">

**Comment by pirhoo** [comment]
Can you please share more details about how you run Datashare in server mode?

**Comment by a3sroot** [comment]
> Can you please share more details about how you run Datashare in server mode?

server mode,I see that the documentation can only import data via the command line. Configuration is the way the official documentation provides.

Although I'm not sure if incremental data appears in the catalog, or if it's imported all over again?

#1279 Here's the configuration
