### ISSUE TITLE
Remove documents from index with CLI

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#1292]
**Is your feature request related to a problem? Please describe.**

I'd like to remove documents from index.

**Describe the solution you'd like**

We wanted to avoid users to have access to document removal because we wanted the document corpus to be immutable specifically with SERVER mode. 

However, it could be made with command line interface as only administrative persons have access to it.

**Comment by LeoGe2022** [comment]
Support!!

I had no idea that documents that had been removed would still remain in the index although I tried re-analyzing tasks.

Any workaround? Remove the dirty project and create a clean one? Thanks!

**Comment by pirhoo** [comment]
Hello @LeoGe2022, yes you must delete the project or delete them all: https://icij.gitbook.io/datashare/usage/faq/general/can-i-remove-a-document-from-datashare
