### ISSUE TITLE
Star a document with the new database configuration

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#130]
Users should be able to star a document:
- we will use 2 versions of the star icon : regular https://fontawesome.com/icons/star?style=regular and solid https://fontawesome.com/icons/star?style=solid
- when users hover the container of a document's title, the light star will appear (like the download icon)
- when users hover the star icon itself, the star icon becomes solid
- when users click the star icon itself, the star icon remains solid until the user unstar it

To unstar:
- users will click on the solid star icon 
- the star icon will become and remain light until users star it again

The star icon can be placed just left to the download button. It can mean that the length of the title of a document will be reduced in order to have some room for the star icon.
![Example star](https://user-images.githubusercontent.com/17233829/58803836-abb6e680-8610-11e9-99aa-33eaaeaba66d.png)

**Comment by Soliine** [comment]
@annelhote We decided to keep the solid star icon sticky when it is starred and to reverse the star icon and the download icon in order to have the star icon on the right.

**Comment by annelhote** [comment]
@bamthomas needs to configure the ansible role to postgresql and create the database in production
