### ISSUE TITLE
(priority 2/2) Boolean and exact phrase searches

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#131]
Users currently cannot use Boolean operators in Datashare. 
They would also like to be able to make searches for exact phrase in double quotes. For this second functionality, we will pay attention to consequences for results and applied filters.

**Comment by annelhote** [comment]
Lucene syntax : https://www.elastic.co/guide/en/elasticsearch/reference/7.0/query-dsl-query-string-query.html#query-string-syntax

**Comment by annelhote** [comment]
It works. Whe should add :
- [ ] Some tests on the frontend to check the multiple syntax available
- [ ] Some help to explain the user how it works (TBC)
- [ ] Some autocompletion in the search input (cf. Kibana)

**Comment by annelhote** [comment]
https://demo.elastic.co/app/kibana

**Comment by annelhote** [comment]
- Boolean
  - AND : term_01 AND term_02
  - OR : Term_01 OR term_02
- Exact search : "this is an exact search"
- Field name : field_name:term_01
- Wildcards
  - ? : term_0?
  - * : te*
- Fuzziness : trem_01~

**Comment by annelhote** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-suggesters-completion.html

**Comment by annelhote** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html

**Comment by annelhote** [comment]
Example w/ React : https://blog.bitsrc.io/how-to-build-an-autocomplete-widget-with-react-and-elastic-search-dd4f846f784

**Comment by annelhote** [comment]
Let's discuss about the last point : "Some autocompletion in the search input (cf. Kibana)". Which field should feed the autocompletion ? Should I add the field names and the logical operators (AND, OR, ?, *, ~ ...) ? How soon should start the autocompletion, after 3 chars ?

**Comment by annelhote** [comment]
Next : #167.
