### ISSUE TITLE
(priority 1/2) Difference between named entities in Extracted Text and in Preview

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#132]
Named entities differ from the original document (as seen in Preview) and the Extracted Text.

See screenshot sent by private message.

**Comment by Soliine** [comment]
We decide to create a toggle-switch button:

- user can switch between 2 modes: 
1. "See highlights:" with the hover "Caution! There might be some errors that overwrite the original text"
2. do not see highlights

- the mode is persistent from one document to another

- the toggler can be seen and switch on any doc view (extracted text, named entities, preview, details)
![Group 27](https://user-images.githubusercontent.com/17233829/56799814-f8412200-6819-11e9-9157-c0e646ca52e8.png)

**Comment by Soliine** [comment]
We decide to create a toggle-switch button:

- Users can switch between 2 modes: 
1. "See highlights" with a tooltip when hovering which says "Caution! There might be some errors that overwrite the original text"
2. do not see highlights

- The mode is persistent from one document to another

- The toggle-switch button can be seen and switched in any tab of the doc view (extracted text, named entities, preview, details)

![Group 27](https://user-images.githubusercontent.com/17233829/56799995-553cd800-681a-11e9-9562-991591290dfa.png)

**Comment by annelhote** [comment]
Put the "Show highlights" 

- [ ] Rename "Show highlights" into "Show named entities"
- [ ] Change tooltip to "Warning! the named entities will be highlighted and may replace text underneath. This does not impact your search results."
- [ ] Put the toggle button on the top right of the "Extracted text" tab (white part).

**Comment by annelhote** [comment]
Hide the "Show named entities" toggler if there is no named entites.
