### ISSUE TITLE
bug: date histogram not showing 2023 - 2024

### ISSUE THREAD

**Issue by sesscon** [ICIJ/datashare#1323]
**Describe the bug**
The date histogram is not displaying the year 2023 or 2024, however when you go to the monthly view it will show the correct amount of documents for those perspective years.

I am using the DEB package on Ubuntu 22.04 LTS version 13.9.2

**To Reproduce**
1. Fresh Install of 13.9.2
2. Load Initial Front Page after completed document index.

**Expected behavior**
Show documents with the creation date of 2023.

**Screenshots**
![image](https://github.com/ICIJ/datashare/assets/125361902/4b9f9c5e-b4c9-49a9-91f2-81ede10ac1e5)

![image](https://github.com/ICIJ/datashare/assets/125361902/74380f6b-3fc0-4574-a3b6-a34b24add94f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: e.g. Chrome
 - Version: e.g. Version 121.0.6167.161

**Comment by pirhoo** [comment]
Thanks for the detailed bug report @sesscon! We are having a look.

**Comment by sesscon** [comment]
Just curious if there is an update on a bug fix for this?

**Comment by pirhoo** [comment]
Hello @sesscon, unfortunately I did not manage to reproduce the error consistently but the API we use to build the histogram is deprecated. Therefore, we are going to rewrite this piece of code in the following weeks. Hoping it will solve this issue at the same time!
