### ISSUE TITLE
Add Creation date in the filters

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#133]
Create a new left facet to filter documents by their "Creation date" and add creation date in sort by.
Keep "Indexing date" and add "Creation date" in both the left facet and the sort by.

**Comment by annelhote** [comment]
Create a dedicated facet.

**Comment by Soliine** [comment]
Creation date:
- Put "unknown" if no creation date. 
- Limit on 8 items

**Comment by annelhote** [comment]
Finally find how to truncate a bucket aggregation. Use a pipeline aggregation to perform operation on the output of other aggregations. The one we were looking for was a bucket sort aggregation : [https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html#_truncating_without_sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html#_truncating_without_sorting).
```
{
    "size": 0,
    "aggs" : {
        "bucket_aggregation_name" : {
            "date_histogram" : {
                "field" : "field_name"
            },
            "aggs": {
                "bucket_sort_name": {
                    "bucket_sort": {
                        "size": 8
                    }
                }
            }
        }
    }
}
```

**Comment by annelhote** [comment]
And the way to write it with [bodybuilder](https://bodybuilder.js.org/) :
```
bodybuilder()
	.size(0)
        .agg('date_histogram', 'field_name', {}, 'bucket_aggregation_name', a => a.agg('bucket_sort', { size: 8 }, 'bucket_sort_name'))
        .build()
```

**Comment by pirhoo** [comment]
Cool! I was also having a look this afternoon on `top_hits` which can be used to do something similar:
https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-aggregations-metrics-top-hits-aggregation.html

**Comment by annelhote** [comment]
Try to resolve the issue about "How to filter on missing creation date" ?

**Comment by annelhote** [comment]
Linked to #170.
