### ISSUE TITLE
Add a spinner to the named entities "show more" window

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#134]
When there are lots of named entities, in the "shore more" window, users don't see that the next named entities are loading. To add a spinner which says "loading..." will solve this.
<img width="497" alt="Screen Shot 2019-04-25 at 2 44 22 PM" src="https://user-images.githubusercontent.com/17233829/56736650-fff4be00-6768-11e9-8889-a213d643789d.png">

**Comment by annelhote** [comment]
Avoid the display of "no results" while it's loading
