### ISSUE TITLE
Error message when trying to delete project

### ISSUE THREAD

**Issue by arthcras** [ICIJ/datashare#1354]
**Describe the bug**
Error message when trying to delete project

**To Reproduce**
1. Go to '.Projects..'
2. Click on '.Delete and select "Yes...'
4. See error: '.Unable to delete, see attachment..'

**Expected behavior**
That project is deleted

**Screenshots**
Pls find attached

**Desktop (please complete the following information):**
 Apple Macbook Pro, Max

<img width="1728" alt="Screenshot 2024-03-01 at 7 23 13 AM" src="https://github.com/ICIJ/datashare/assets/34338515/cad971f2-0a18-4ff8-a16b-8daf55eccf73">

**Comment by mvanzalu** [comment]
Cannot reproduce on Monterey 12.6, on which version of MacOS are you running DS ?
