### ISSUE TITLE
Unable to view sub-folders on external drive

### ISSUE THREAD

**Issue by rayrobinson** [ICIJ/datashare#1358]
When using an external drive for the Datashare data directory, I can see only the top level folder when adding documents for indexing.
*
1. Go to Settings | Data Dir
2. Add path to external volume.
3. Go to Projects | New Project and enter path to external drive in Folder field.
4. Go to Tasks | Analyze Documents | Add Documents
5. Result: only the top level folder is shown. (See attached screenshot)

**Expected behavior**
Being able to drill down to and select sub-folders.

**Screenshots**
See attached.
![Screenshot 2024-03-10 at 12 13 54 PM](https://github.com/ICIJ/datashare/assets/9682402/00985634-17cd-4139-9121-aad338789e5c)

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2
 - Browser: Chrome
 - Version: Datashare 14.1.5

Additional context:

I am able to browse to and use sub-folders when I use the Datashare folder on the Mac. But it would be helpful to be able to do the same on an external drive.

**Comment by pirhoo** [comment]
Hi Ray, thanks for the issue! Is there any symlinks in your external volume?

**Comment by rayrobinson** [comment]
No, all of the files are hard links.
