### ISSUE TITLE
Failure to launch ("No enum constant org.icij.datashare.cli.QueueType.memory")

### ISSUE THREAD

**Issue by JCBerger** [ICIJ/datashare#1368]
**Describe the bug**
Receive an error in Terminal when I try to open Datashare. (This has been a long-standing issue across other versions, but it looked like someone always reported it before I did.)

**To Reproduce**
1. Double-click on "Datashare" from the Applications folder.
2. Terminal window opens. Among the wall of text, I receive what I think is the substantive culprit: 
```
An exception was caught and reported. Message: No enum constant org.icij.datashare.cli.QueueType.memory
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
```

**Expected behavior**
The application wouldn't kick back an error, and I could access it through the web view.

**Desktop (please complete the following information):**
 - OS: macOS (14.2.1 (23C71))
 - Browser: Safari (Version 17.2.1 (19617.1.17.11.12))

**Additional context**

**(Optional) Your contact, availabilities and timezone if a video call with screensharing is needed**
United States, Eastern (in line with New York City).

**Comment by caro3801** [comment]
Thanks for reaching out! We are investigating this issue

**Comment by caro3801** [comment]
Indeed we already have solved a similar issue https://github.com/ICIJ/datashare/issues/1338
They indicate that uninstalling and reinstalling datashare worked. Have you tried ?

**Comment by JCBerger** [comment]
@caro3801 I tried removing Datashare and then reinstalling it like in the other ticket, but no luck. Are there other components somewhere else (e.g., Java) that I should move to the Trash (and empty) to effectuate the uninstall?

 I also noticed that ticket mentioned use of an Intel processor and I'm on Silicon, is there any way that makes a difference?

**Comment by caro3801** [comment]
Thanks for the quick reply. I don't think the processor makes a difference.
- Can you tell me which version of datashare are you trying to install ? 
- What is your mac os version ? 
- Do you know you java version ?

**Comment by JCBerger** [comment]
Based on the information included in the Terminal window, it looks like I'm running Java 17.0.9.  My Mac version is 14.4.1 (23E224).

Yeah, I've tried uninstalling Datashare both that way and through "AppZapper," but still no success.

**Comment by caro3801** [comment]
And the datashare version?

**Comment by JCBerger** [comment]
Sorry, 14.2.3. I would assume it's unrelated, but could an issue be created by the fact that the Info box for the application is not showing a version number?
<img width="395" alt="Screenshot 2024-04-19 at 11 02 24" src="https://github.com/ICIJ/datashare/assets/3228462/1da3e15a-3435-4f95-9278-4d991b304491">

**Comment by JCBerger** [comment]
@caro3801 For what it's worth, I downloaded and installed version 15.1.9, and the problem went away. So I don't know if that fixed something or I somehow managed to download and install necessary dependencies for another application that just so happened to resolve this issue.
