### ISSUE TITLE
Couldn't connect to Docker daemon at http+docker://localhost - Ubuntu

### ISSUE THREAD

**Issue by reichaves** [ICIJ/datashare#137]
Hello
My name is Reinaldo Chaves, I'm a journalist in Brazil.
Please, I'm having trouble installing Datashare
I have a notebook with Ubuntu 16.04 LTS, with 8GB of RAM

-> I installed Docker for Ubuntu 16 and did the test:
sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

-> Then I installed Docker Compose and did the test:
docker-compose --version
docker-compose version 1.24.0, build 0aa59064

-> Then I encountered this error with datashare.sh:
chmod + datashare.sh
./datashare.sh
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
binding data directory to /home/reinaldo/Datashare
binding NER models directory to /home/reinaldo/.local/share/Datashare_Models
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=datashare: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

Please, do you know how I can solve it?

**Comment by Soliine** [comment]
Hello Reinaldo Chaves, thank you for using Datashare.
You now need to add your user to the Docker group. 
To do this, you can type in your command line: `sudo usermod -aG docker your-use`r
You need to log out and log in after that. You can find this step at the end of this page if needed: https://docs.docker.com/install/linux/docker-ce/ubuntu/
