### ISSUE TITLE
feat: automatically apply elastic search settings

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1382]
During deploy or install, automatically apllying settings to elastic search would prevent discrepancies and manual interventions to update the settings.

Currently it could be done with this `curl` command:
* `curl -XPUT http://elasticsearch:9200/_settings -H "Content-Type: application/json" -d @src/main/resources/datashare_index_settings.json`
* `curl -XPUT http://elasticsearch:9200/_settings -H "Content-Type: application/json" -d @src/main/resources/datashare_index_settings_windows.json`

Example for applying current query `default_fields` manually:
```sh
curl -XPUT http://elasticsearch:9200/_settings -H "Content-Type: application/json" -d'{ "index.query.default_field": [              
    "content",
    "mentionNorm",
    "content_translated.content",
    "metadata.tika_metadata_author",
    "metadata.tika_metadata_creator",
    "metadata.tika_metadata_dc_creator",
    "metadata.tika_metadata_dc_title",
    "metadata.tika_metadata_message_from",
    "metadata.tika_metadata_message_to",
    "metadata.tika_metadata_meta_author",
    "metadata.tika_metadata_subject",
    "metadata.tika_metadata_title",
    "metadata.tika_metadata_resourcename",
    "name",
    "path",
    "tags"
  ]}'

```

**Comment by mvanzalu** [comment]
We decided to document every change on ES settings to help users to migrate.
Aside we can write a guide to deal with indexes modifications.

**Comment by mvanzalu** [comment]
We decided to use scripts from [datashare-playground](https://github.com/ICIJ/datashare-playground) to apply/reindex changes.

- [ ] Add a script which reindex given a version of Datashare
- [ ] Add `datashare_index_settings_(windows).json` and `datashare_index_mappings.json` in the [release files](https://github.com/ICIJ/datashare/releases)
- [ ] Make a Gitbook page to explain how to migrate
