### ISSUE TITLE
Add Previous/Next buttons for occurrences -not documents- in extracted text

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#139]
When a user makes a search on the page with one or several words, in Extracted Text, users should be able to go from one occurrence of the search to the next one (replicating the command+F behaviour). 

We can create 2 buttons (Previous and Next) in Extracted Text on the right at the same level as the toggle button "Show named entities".

**Comment by Soliine** [comment]
We can see if we can "catch" the Control+F functionality of the browsers and make it work only in Extracted Text (not in the list of documents' titles nor in the facets) as Google docs do in the text of the document only.

**Comment by Soliine** [comment]
on Mac:
- you go to the next occurrence with ENTER
- you go to the previous occurrence with SHIFT+ENTER

**Comment by Soliine** [comment]
In emails, when we search for a term that is contained in previous emails, it does not find the terms.

**Comment by annelhote** [comment]
F3 doesn't work

**Comment by annelhote** [comment]
Ce que moi j'avais compris de la demande :
Sur ta machine, tu fais un cmd + f pour lancer la recherche
puis tu fais un ENTER pour aller au résultat suivant
ou un SHIFT + ENTER pour aller au résultat précédent
Mais tu dois aussi pouvoir faire F3 pour aller au résultat suivant
et SHIFT + F3 pour aller au résultat précédent
