### ISSUE TITLE
refactor: align `icij-python` and `datashare-tasks`

### ISSUE THREAD

**Issue by ClemDoum** [ICIJ/datashare#1399]
When #1384 is complete, align async task in datashare and https://github.com/ICIJ/icij-python, so that the Python worker and DS can communicate

**Comment by ClemDoum** [comment]
needed to complete https://github.com/ICIJ/oslomet-collab/issues/22

**Comment by ClemDoum** [comment]
This is still WIP as of today, I'm starting to list divergences to prepare a discussion this week.

**Comment by bamthomas** [comment]
maybe needs #1385
