### ISSUE TITLE
Datashare connection to neo4j aura

### ISSUE THREAD

**Issue by arthcras** [ICIJ/datashare#1402]
The current connection to neo4j desktop is a great feature; It would add value to the users of datashare if datashare can also connect to neo4j instance in the cloud through neo4j aura; it provide them with more flexibility!

Cheers 
Arthur

**Comment by caro3801** [comment]
Thanks for creating the issue. This feature is already supported by the plugin

**Comment by arthcras** [comment]
Hi Team
In the meantime, I reinstalled datashare (latest version) after receiving attached errors, but still error occurs, any suggestion how to repair/solve this issue are welcome
Thanks and Best rgds
Arthur
￼
