### ISSUE TITLE
design system: search form control

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1427]
# Search form control
- [x] option for clearing text
- [x] option for rounded input
- [x] option for size
- [x] slot for icon start
- [x] slot for icon end
# Search bar input uses search form control in LG size
- [x] addon slot (as before)
- [x] option for submit button (as before)
- [x] option for hide tips (as before)

**Comment by caro3801** [comment]
https://icij.github.io/datashare-client/?path=/docs/layout-searchformcontrol--docs
https://icij.github.io/datashare-client/?path=/docs/components-searchbar-searchbarinput--docs

**Comment by caro3801** [comment]
I added an option to have shadow in light mode on the search form control and apply it to the search bar input https://github.com/ICIJ/datashare-client/commit/068535cdaa9e10130e6bb625097cc15cfe9155cb
