### ISSUE TITLE
design system: app sidebar

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1428]
* [x] app sidebar toggler 
* [x] app sidebar footer 
* [x] app sidebar section
* [x] app sidebar section entry
* [x] app sidebar section toggler

**Comment by Soliine** [comment]
Great job! It's such a big component :)

- The [AppSidebarFooter](https://icij.github.io/datashare-client/?path=/docs/components-appsidebar-appsidebarfooter--docs) has a vertical alignment issue
<img width="761" alt="Screenshot 2024-07-15 at 10 32 48" src="https://github.com/user-attachments/assets/3bcb3e4d-7a10-49df-a563-318176929b05">

- The [AppSidebarSectionEntry](https://icij.github.io/datashare-client/?path=/docs/components-appsidebar-appsidebarsectionentry--docs), when hovered, should display the [secondary pink left border](https://www.figma.com/proto/zuUb7ndAVzky62jhRP1edJ/Datashare?node-id=1-3501&viewport=1925%2C366%2C0.08&t=HZ1q5NlxerGZuLWH-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5%3A3508&show-proto-sidebar=1)

- The [AppSidebarSectionTitle](https://icij.github.io/datashare-client/?path=/docs/components-appsidebar-appsidebarsectiontitle--docs) has a bold text (700) while it should be 500 (regular, what is called "medium bold" in Figma)

- There are 2 tooltips when hovering the [AppSidebarSectionToggler](https://icij.github.io/datashare-client/?path=/docs/components-appsidebar-appsidebarsectiontoggler--docs)

- The icon of the [AppSidebarToggler](https://icij.github.io/datashare-client/?path=/docs/components-appsidebar-appsidebartoggler--docs) should be white (and remains white in the dark theme)

**Comment by pirhoo** [comment]
Done!

**Comment by pirhoo** [comment]
I'm reopening this issue because we added the keyboard shortcut buttons to the sidebar.

**Comment by pirhoo** [comment]
Done here: https://icij.github.io/datashare-client/?path=/docs/stories-introduction--docs

**Comment by Soliine** [comment]
Great!
