### ISSUE TITLE
design system: dismissable alert

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1430]

**Comment by Soliine** [comment]
Perfect!

**Comment by Soliine** [comment]
- the button is attached to the right side of the frame while it should be next to the text
- the x icon on the right side is missing (if user want to dismiss now but show again later)

**Comment by pirhoo** [comment]
Done!

**Comment by Soliine** [comment]
Thanks!

- Do you understand why the texts are not aligned? <img width="640" alt="Screenshot 2024-07-18 at 13 08 37" src="https://github.com/user-attachments/assets/7a12c570-f96e-4539-8541-a3dd6117e910">

- Can you also space out the text and the button with 16pt?

**Comment by pirhoo** [comment]
I adjusted the vertical centering.

![Image](https://github.com/user-attachments/assets/213a633a-ed05-436c-9538-3b9b3522e5d4)

For small screen I also proposed a column-free versions:

![Image](https://github.com/user-attachments/assets/038ccd25-3fdb-4304-a9a8-57dd748d2d01)

**Comment by Soliine** [comment]
Perfect! I love the small screen's version you made!
