### ISSUE TITLE
design system: navgation breadcrumb

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1432]
* [x] entry
* [x] link

**Comment by Soliine** [comment]
Well done!

- A small detail (not sure it is important but maybe yes, if we search for it one day), the ["Mutltiple Addons" here]( https://icij.github.io/datashare-client/?path=/docs/components-navigationbreadcrumb--docs&globals=theme:light) has a small misspelling => it should be "Multiple Addons"

- When there are Button or Multiple Addon, the general height of the component is bigger, it could be make the component "jump" when we go from one page without button/addon to a one with button/addon

- When we hover a [Link](https://icij.github.io/datashare-client/?path=/docs/components-navigationbreadcrumb-link--docs) which is not the last link of the breadcrumb, the secondary pink bottom border should be visible

**Comment by pirhoo** [comment]
Got catch for the component height! I fixed it to at least `3rem = 48px` which will avoid this effect.

I made the other changes.

**Comment by Soliine** [comment]
Great! 

The only things I see is the configure icon which is pink when hovered while it should be in primary for accessibility reasons 
<img width="238" alt="Screenshot 2024-07-18 at 13 14 25" src="https://github.com/user-attachments/assets/4df6e50d-4cbb-4da9-a5ad-265caa28c768">

**Comment by pirhoo** [comment]
This is a "link" button so it behave like a link:

http://localhost:6006/?path=/story/layout-button--default&globals=theme:light

But maybe we should define that those button behave differently?

**Comment by Soliine** [comment]
Good news: I actually realize we can use this secondary pink for UI component so we can keep the hover state in pink when the link button is an icon:
<img width="1246" alt="Screenshot 2024-07-22 at 10 20 26" src="https://github.com/user-attachments/assets/15d04cd6-4a78-4e1a-9f46-e506d103ac14">

**Comment by Soliine** [comment]
The rest is fantastic!
