### ISSUE TITLE
design system: pagination

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1434]

**Comment by Soliine** [comment]
Looks good!

- When we are in row = True and we have number in thousands in the "modelValue", we don't see the comma <img width="869" alt="Screenshot 2024-07-15 at 11 05 20" src="https://github.com/user-attachments/assets/ea62f020-2b5e-4f95-af03-92ccd0f58049">

- When hovering an arrow, I suggest we have it in secondary pink and in bold
<img width="387" alt="Screenshot 2024-07-15 at 11 08 13" src="https://github.com/user-attachments/assets/63269d18-6f88-4fbb-91a7-a850921a82b3">

- I forgot to design it but when hovering the number input, we could have the border in secondary pink

**Comment by pirhoo** [comment]
Mixing comma/thousands separators is not possible here because the input is of type "number" which has build-in validation in the web browser. I don't advise allowing users use separator as they can lead to mistake due to localization difference (US != France != Germany, for instance).
