### ISSUE TITLE
design system: search breadcrumb

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1435]
* [x] search breadcrumb entry
* [x] search breadcrumb entry filter
* [x] search breadcrumb entry query
* [x] search breadcrumb entry occurrences
* [x] search breadcrumb footer
* [x] search breadcrumb toggler

**Preview**

![Image](https://github.com/ICIJ/datashare/assets/471176/b9de2511-7f9a-4602-b6c6-a824387db6ff)

**Comment by pirhoo** [comment]
Components are here : https://icij.github.io/datashare-client/?path=/docs/components-searchbreadcrumb--docs

**Comment by pirhoo** [comment]
Done!

**Comment by Soliine** [comment]
Excellent 👌
