### ISSUE TITLE
design system: filter panel

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1436]
* [x] filter panel toggler
* [x] filter panel search
* [x] filter panel section
* [x] filter panel section title
* [x] filter panel section filter
* [x] filter panel section filter title
* [x] filter panel section filter title toggler
* [x] filter panel section filter entry
* [x] filter panel section filter footer
* [x] filter panel section filter footer sort 

**Preview**

![Image](https://github.com/ICIJ/datashare/assets/471176/6293b774-570a-4acb-9859-ced34cdb0101) ![Image](https://github.com/ICIJ/datashare/assets/471176/c11b4501-e6aa-4ef7-ba41-897d81350e69)

**Comment by pirhoo** [comment]
Ready for review: https://icij.github.io/datashare-client/?path=/docs/components-filterspanel--docs

**Comment by Soliine** [comment]
Well done! That's a big one :)

In the Tags filter, when it's open:
- I need to work again on the "sort" and its icon. Atm, they look like 2 different buttons to me
- the scrollbar overlaps the items' numbers
- I need to work again on the Expand-Contextualize-Exclude footer, its height may be not big enough
- The header doesn't look tall enough too

**Comment by Soliine** [comment]
Following @pirhoo's insight on being consistent when users hover inputs, I suggest the following design when we hover the "search in filters" bar:
<img width="521" alt="Screenshot 2024-07-15 at 13 52 21" src="https://github.com/user-attachments/assets/c951945f-4e28-4b69-9206-e06166511869">

**Comment by pirhoo** [comment]
I updated the horizontal padding so the scroll bar is doesn't stick to the content too much.

I also increased the vertical padding on the filter title when open.

WDYM "The header doesn't look tall enough too" ?

**Comment by Soliine** [comment]
That's great, thanks!
I meant this height in red. I think we can increase the bottom padding so when users scroll down to read the list, the "Tags" and the list are not too close:
<img width="235" alt="Screenshot 2024-07-15 at 15 46 48" src="https://github.com/user-attachments/assets/1e8a76bd-fb49-408d-9316-32dc6b6ec47a">

**Comment by Soliine** [comment]
So I think it's what you already fixed as you said "I also increased the vertical padding on the filter title when open."

**Comment by pirhoo** [comment]
OK cool!

**Comment by pirhoo** [comment]
Looks good!

![Image](https://github.com/user-attachments/assets/fe64210d-dcca-43e9-9a47-03c60533557e)
![Image](https://github.com/user-attachments/assets/2693f6b7-fe45-4f86-b518-56adf2f32b2a)
