### ISSUE TITLE
design system: separator line

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1438]
![Image](https://github.com/user-attachments/assets/b3576ace-fa30-456e-b323-bd3a7359c01e)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-sepratorline--docs

**Comment by Soliine** [comment]
Is it possible to have the icon in bold when it's hovered?

**Comment by pirhoo** [comment]
Sure!

**Comment by pirhoo** [comment]
Done!
