### ISSUE TITLE
design system: document actions

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1439]
* [x] favorite
* [x] download
* [x] share
* [x] expand

**Comment by caro3801** [comment]
![Image](https://github.com/user-attachments/assets/78de0c95-03e0-47d6-9172-de0f0dd86a6f)

https://icij.github.io/datashare-client/?path=/docs/components-document-documentactionsgroup--docs

**Comment by Soliine** [comment]
Excellent work! 

I like the sharing icon that you chose! But I wonder if the DownloadSimple icon in Phosphor wouldn't be simpler as they say. As we have a very heavy interface, I would keep the DownloadSimple icon rather than the more detailed one.

**Comment by Soliine** [comment]
Great!
I see a new issue, the star became an expand icon: <img width="241" alt="Screenshot 2024-07-30 at 11 41 12" src="https://github.com/user-attachments/assets/1ee23e1c-ef4c-45fb-a7eb-140b495485ce">

**Comment by caro3801** [comment]
Oups thanks for noticing, it's fixed! 


![Image](https://github.com/user-attachments/assets/0c0366ee-ea9e-4460-98ad-3fea95209db0)
