### ISSUE TITLE
Security: local host binding by default

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#144]
Local Datashare shouldn't use the `0.0.0.0` address binding by default.
Should be a parameter for advanced users.

**Comment by bamthomas** [comment]
fixed with release 1.62.0
tested on linux/mac/windows

**Comment by pirhoo** [comment]
Apparently

**Comment by bamthomas** [comment]
I checked on linux for datashare in embedded mode (debian package) address is bounded on localhost 127.0.0.1

```
tcp6       0      0 127.0.0.1:8080          127.0.0.1:52854         ESTABLISHED 1000       376828     49821/java          
```
