### ISSUE TITLE
design system: document thumbnail

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1440]
![Image](https://github.com/user-attachments/assets/60377ce5-9830-4b20-9850-47faedcceda6)

**Comment by pirhoo** [comment]
It's here: https://icij.github.io/datashare-client/?path=/docs/components-document-documentthumbnail--docs

**Comment by Soliine** [comment]
Awesome! 🎉

- When we [crop](https://icij.github.io/datashare-client/?path=/docs/components-document-documentthumbnail--docs), the cropped version is centered. Could we rather see the top left of the document as headers contain more info in general?

- [Here](https://icij.github.io/datashare-client/?path=/story/components-document-documentthumbnail--with-placeholder&args=size:md;crop:!false) the height of the preview is very small, is it normal?
<img width="185" alt="Screenshot 2024-07-18 at 10 25 14" src="https://github.com/user-attachments/assets/a47ed5df-c9c5-4304-891c-790aa9d6a80f">

**Comment by pirhoo** [comment]
It can be align on top, but not on left since the thumbnail use the whole width.

Here the result with top-left/top-center positioning:

![Screenshot 2024-07-18 at 10-41-50 Components _ Document _ DocumentThumbnail - Docs ⋅ Storybook](https://github.com/user-attachments/assets/31425c9d-a4e8-4c77-8511-6c02b6d06c89)

**Comment by Soliine** [comment]
Perfect!
Thank you

**Comment by pirhoo** [comment]
I've made the changes and fix the non-crop display without image.

**Comment by Soliine** [comment]
Great! I move it to Done
