### ISSUE TITLE
design system: document card

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1441]
* [x] document card title
* [x] document card checkbox
* [x] document card properties
* [x] document card properties entry
* [x] document card properties entry author
* [x] document card properties entry content length
* [x] document card properties entry content text length
* [x] document card properties entry content type
* [x] document card properties entry creation date
* [x] document card properties entry extraction level
* [x] document card properties entry highlights
* [x] document card properties entry language
* [x] document card properties entry path
* [x] document card properties entry project
* [x] document card properties entry tags
* [x] document card actions

**Preview**

![Image](https://github.com/user-attachments/assets/2bc67407-f8a6-4f21-96fb-56e542e851c1)

**Comment by pirhoo** [comment]
component is here: https://icij.github.io/datashare-client/?path=/docs/components-document-documentcard--docs

**Comment by Soliine** [comment]
Huge and perfect 👏
