### ISSUE TITLE
design system: date display

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1442]

**Comment by pirhoo** [comment]
Component here: https://icij.github.io/datashare-client/?path=/docs/components-display-displaydatetime--docs

**Comment by Soliine** [comment]
How about having a shorter version on top of this one with months reduced to their first three letters (Jan, Feb, Mar, Apr, etc)?
It could be useful in tables (for instance, table of batch searches) when we will need room for other columns

**Comment by pirhoo** [comment]
The short version already use 3-letter month: https://icij.github.io/datashare-client/?path=/story/components-display-displaydatetime--default&args=value:!date(2024-07-18T09:22:23.536Z);format:short

**Comment by Soliine** [comment]
Oh great! Sorry I had missed format, it's great!
