### ISSUE TITLE
design system: search in document

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1446]
* [x] search in document input
* [x] search in document occurences
* [x] search in document nav
* [x] search in document nav item

**Preview**

![Image](https://github.com/user-attachments/assets/e49022dd-92f0-4dbd-b947-d67902e7b264)

**Comment by pirhoo** [comment]
Component is here with the latest adjustments https://icij.github.io/datashare-client/?path=/docs/components-document-documentlocalsearch-documentlocalsearchoccurences--docs

**Comment by Soliine** [comment]
Great!
