### ISSUE TITLE
design system: document search nav

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1448]
**Preview**

![Image](https://github.com/user-attachments/assets/f12e31f4-a3b8-40a6-9b65-994fa1e4cec8)

**Comment by pirhoo** [comment]
Component is here: http://localhost:6006/?path=/docs/components-document-documentsearchnav-documentsearchnav--docs

**Comment by Soliine** [comment]
Excellent 👌

**Comment by Soliine** [comment]
A very small detail: can you make the separation line between the two icons as thin as their borders if possible?
Currently it's like this:
<img width="271" alt="Screenshot 2024-07-24 at 10 40 36" src="https://github.com/user-attachments/assets/b4c77c4f-d7eb-475c-ba8b-4936373f955a">
And the expected line is like this:
<img width="524" alt="Screenshot 2024-07-24 at 10 47 21" src="https://github.com/user-attachments/assets/fe99604d-fe00-49ab-b2a5-7d2ffc84080e">

**Comment by pirhoo** [comment]
I've made the border transparent when disabled.

Regarding the tooltip, it's because the storybook page is very small as opposed to a real page. I move the tooltips to the bottom in this story to avoid the problem.

**Comment by Soliine** [comment]
Excellent!

**Comment by Soliine** [comment]
It's strange because [here](https://icij.github.io/datashare-client/?path=/docs/components-document-documentlocalsearch-documentlocalsearchoccurences--docs), the disabled button has borders while the actionnable button has no border and it should be the contrary:
![Image](https://github.com/user-attachments/assets/c2dff87a-8ec2-4758-8e49-e776fead9357)

**Comment by pirhoo** [comment]
Ah yes, it's not the same component but it looks like DocumentLocalSearchOccurences was affected by the global styling of disabled state. Here we use the "outline-secondary" variant. I'm going to tweak that.
