### ISSUE TITLE
design system: linked documents

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1449]
* [x] linked documents toggler
* [x] linked documents section
* [x] linked documents section siblings
* [x] linked documents section children
* [x] linked documents section search

**Comment by caro3801** [comment]
![Image](https://github.com/user-attachments/assets/64549edc-cd07-467e-9e70-1ea55e9e4a66)


https://icij.github.io/datashare-client/?path=/docs/components-linkeddocument-linkeddocumentcard--docs

**Comment by Soliine** [comment]
Awesome 🎉

I only see one thing, it's the top of the letters below when the component is collapsed:


![Image](https://github.com/user-attachments/assets/7029caaf-1522-478a-8cdc-0c0b82bb653e)
