### ISSUE TITLE
design system: document metadata actions

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1450]
* [x] document metadata actions
  * [x] document metadata actions entry

**Preview**

![Image](https://github.com/user-attachments/assets/41130379-d9a3-4a32-af0b-32ecd69e760d)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-document-documentmetadata-documentmetadataactions-documentmetadataactions--docs

**Comment by Soliine** [comment]
Perfect!
