### ISSUE TITLE
designer: contextual links to documentations

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1453]

**Comment by Soliine** [comment]
<img width="377" alt="Screenshot 2024-08-08 at 17 32 46" src="https://github.com/user-attachments/assets/8543b2f1-c35c-4d73-a59d-6a82b989c641">

**Comment by Soliine** [comment]
<img width="330" alt="Screenshot 2024-08-08 at 17 38 46" src="https://github.com/user-attachments/assets/a5251dd4-2de7-442e-a105-c52c1dc31830">

**Comment by Soliine** [comment]
As we finally won't have standalone documentation (documentation will be launched in guided tour), I merged this component with the welcome tour's component called DocumentationPopover:
![Image](https://github.com/user-attachments/assets/fe427156-fa3b-495b-b7b1-c7937abc20e1)

![Image](https://github.com/user-attachments/assets/e884b44c-a428-49f5-99e4-6ee81611344c)
