### ISSUE TITLE
designer: welcome tour

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1454]

**Comment by Soliine** [comment]
I suggest we have several welcome tours:
- one on the landing page (the projects' page) on first visit
- one on each general menu entry's pages of Datashare

Users could access them by hovering the student's icon on the left menu via the Dropdown component:
![Image](https://github.com/user-attachments/assets/1ccdaa41-7cb4-47d0-916f-ff85e498ac18)

Then, users see the chosen guide tour and navigate with this component that I called "DocumentationPopover":
![Image](https://github.com/user-attachments/assets/ee654051-9845-4537-a8c4-0d4e5daddd20)

The component is anchored like this on the pages:
![Image](https://github.com/user-attachments/assets/7826c55d-71e0-4d6c-b9ff-153d0702da59)
![Image](https://github.com/user-attachments/assets/8a2c8d1a-c184-4e8c-afe5-51c4d2d72832)
![Image](https://github.com/user-attachments/assets/4be037e5-7063-47ca-9353-2c3090dbb8e7)

I created a new shadow effect for this, that I called welcome-tour:
![Image](https://github.com/user-attachments/assets/44945117-7cab-4c1d-8c08-a89835a9488d)
