### ISSUE TITLE
design system: tags display

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1462]

**Comment by pirhoo** [comment]
Component here: https://icij.github.io/datashare-client/?path=/docs/components-display-displaytags--docs

**Comment by Soliine** [comment]
Should tags be links everywhere?
They would have a darker/bolder aspect on hover and on click, they would lead to the search page filtered with the clicked tag?

**Comment by pirhoo** [comment]
It would be nice to make them clickable and adding the tag to the current search is a good idea. It's not "pure ui" so we'll do it later :)

**Comment by Soliine** [comment]
Great!
