### ISSUE TITLE
design system: tabs

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1464]
* [x] NavigationTabs
* [x] NavigationTabsEntry

**Preview**

![Image](https://github.com/user-attachments/assets/e30bdbfa-497e-4603-92ed-08ad0cbe8bbb)

**Comment by pirhoo** [comment]
Here is the component: https://icij.github.io/datashare-client/?path=/docs/components-navigationtabs-navigationtabs--docs

**Comment by Soliine** [comment]
It looks great!

Wdyt of having the icon in bold when the tab is active?

**Comment by pirhoo** [comment]
Sure, let me try.

**Comment by pirhoo** [comment]
Done!
