### ISSUE TITLE
design system: app modal

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1465]
* [x] AppModal
* [x] AppModalHeader
* [x] AppModalFooter

**Preview**

![Image](https://github.com/user-attachments/assets/797e4211-42f4-4738-aff6-d8166f54c590)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-appmodal-appmodal--docs

**Comment by Soliine** [comment]
Excellent!

I see a few things:
- The color of the text of "Default slot content" should be tertiary-body-color
- Same for "Cancel" button color: I made a component out of this "Cancel or OK" buttons as we also use them at the end of all forms in the app
- The spacing between Cancel button and OK button should be greater, with 32px

**Comment by pirhoo** [comment]
OK thanks!

I was wondering if the color of the text content was $tertiary on purpose: modals can have a lot of text so I don't see any reason to mute it down. Maybe you want to use this color only for confirmation when the text is indicative?

**Comment by pirhoo** [comment]
I've the color/space changes and used [FormActions](https://icij.github.io/datashare-client/?path=/docs/components-formactions-formactions--docs) to build the footer
