### ISSUE TITLE
Export Import: Export Named Entities as CSV, ODS and xlsx

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#147]
We might cut this story into different stories for the export:
- from 1 document
- from the full corpus
- from a selection of documents
- from the result of a search

**Comment by mtfahey** [comment]
Good morning, has any export function been added to datashare?

**Comment by bamthomas** [comment]
@mtfahey not yet

**Comment by kylemcdonald** [comment]
Would it be possible to connect directly to the redis instance and export to .json? With tools like [redis-dump](https://github.com/delano/redis-dump) or [redis-rdb-tools](https://github.com/sripathikrishnan/redis-rdb-tools)

I tried using the redis-cli to connect:

```
redis-cli -h redis
Could not connect to Redis at redis:6379: Connection refused
not connected>
```

First I added `127.0.0.1 redis` to my `/etc/hosts`.

Is there something else I need to do to connect to the redis instance?

Alternatively, where can I find the .rdb file that backs Datashare?

I am running from the precompiled app in MacOS, not using the Docker image.

cc @nikhil-dharmaraj

**Comment by annelhote** [comment]
Hey @kylemcdonald , thanks for your script. I think that one limitation should be the number of docs extracted as `MAX_DOCS`.

1. No this feature is not yet implemented.
2. We use redis as a queue mainly while indexing. So nothing is stored in it. No need to querying it. So you are right everything is in Elasticsearch.
3. I would advise you to use [`datashare-tarentula`](https://pypi.org/project/tarentula/) to extract your NamedEntities with the `download` command and filtering with `--type NamedEntity`

`tarentula download --type NamedEntity (...)`

**Comment by Soliine** [comment]
This can be done with Tarentula.
