### ISSUE TITLE
design system: status badges

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1472]
* [x] DisplayStatus
* [x] DisplayVisibility

**Preview** 

![Image](https://github.com/user-attachments/assets/6b7c0295-b1ed-480c-8827-da235d9ec6f9)

**Comment by pirhoo** [comment]
Components are here:

* https://icij.github.io/datashare-client/?path=/docs/components-display-displaystatus--docs
* https://icij.github.io/datashare-client/?path=/docs/components-display-displayvisibility--docs

**Comment by Soliine** [comment]
Perfect!

**Comment by Soliine** [comment]
I only see a small bug regarding the text but only on "draft": <img width="174" alt="Screenshot 2024-07-24 at 15 53 33" src="https://github.com/user-attachments/assets/23bf435f-ea21-4c72-80f1-38c73be3ec17">

**Comment by pirhoo** [comment]
Good catch, it's fixed!
