### ISSUE TITLE
design system: document download popover

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1473]
**Preview**

![Image](https://github.com/user-attachments/assets/23b703d1-b092-435c-b940-6d50d6ad712b)

**Comment by pirhoo** [comment]
Component is here with the latest adjustments: https://icij.github.io/datashare-client/?path=/docs/components-document-documentdownloadpopover-documentdownloadpopover--docs

**Comment by Soliine** [comment]
It's great!

- In "with everything", is it possible to have the scroll bar a little more away from the top and right borders?

- We have an accessibility issue in dark mode for the disabled donwload button on its background, the contrast is not enough. Should we use another gray for the download button?
<img width="724" alt="Screenshot 2024-07-29 at 15 13 53" src="https://github.com/user-attachments/assets/2b05bc51-085d-4034-a587-2c390f6116de">

**Comment by pirhoo** [comment]
I cannot move the scroll bar, it's done by the web browser.

The problem with the display of the button in dark more is a more general problem:

https://icij.github.io/datashare-client/?path=/story/layout-button--default

We must define a rule for "action" buttons that applies everywhere.

**Comment by pirhoo** [comment]
With #BFC1C4 in dark mode and an opacity of 0.6 it's AAA:

![Image](https://github.com/user-attachments/assets/6caf8d78-c2f7-41e3-a4ea-08af8ca44fee)
