### ISSUE TITLE
design system: path view

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1475]
* [x] PathView
* [x] PathViewLabel
* [x] PathViewSearch
* [x] PathViewEntry
* [x] PathViewEntryMore
* [x] PathViewEntryName
* [x] PathViewEntryNameCaret
* [x] PathViewEntryNameCheckbox
* [x] PathViewEntryStats
* [x] PathViewEntryStatsDocuments
* [x] PathViewEntryStatsDirectories
* [x] PathViewEntryStatsSize

**Preview**

![Image](https://github.com/user-attachments/assets/73af2968-5d34-4471-a3b9-0783675b434e)
![Image](https://github.com/user-attachments/assets/8248a1b0-de72-4a3c-9954-f8a40bf21039)
![Image](https://github.com/user-attachments/assets/fcb97ffd-003f-4533-ae86-6aa4c2957c3b)
![Image](https://github.com/user-attachments/assets/5c8825f2-79dc-46fa-bbc3-7db06d566698)
![Image](https://github.com/user-attachments/assets/74978713-80e2-48eb-b772-a835ea398559)
![Image](https://github.com/user-attachments/assets/2c8c178f-9cc5-4778-b7a3-7e85fc5f6378)

**Comment by pirhoo** [comment]
Key components are here:

* https://icij.github.io/datashare-client/?path=/docs/components-pathview-pathview--docs
* https://icij.github.io/datashare-client/?path=/docs/components-pathview-pathviewentry--docs
* https://icij.github.io/datashare-client/?path=/docs/components-pathview-pathviewentrystats--docs

And an example of integration into the path filter:

* https://icij.github.io/datashare-client/?path=/story/components-filterspanel-filterspanelsectionfilter--for-path

**Comment by Soliine** [comment]
Great work! It's impressive:)

- Would it be possible to left-align all the folder icons as you did for the documents' icon?
<img width="529" alt="Screenshot 2024-07-29 at 14 08 03" src="https://github.com/user-attachments/assets/d70fec7b-ed1f-46ac-9d6e-1b797807b96a">

- I also [read](https://www.darkhorseanalytics.com/blog/clear-off-the-table/) that users better read and compare numbers in columns when they are right-aligned, especially if there are decimals (which is not the case here) but it's why I right-aligned all the numbers in all Datashare's tables. I applied this to the column for documents and folders number here. Would it be possible to do this?
<img width="536" alt="Screenshot 2024-07-29 at 14 16 48" src="https://github.com/user-attachments/assets/f30b5e3a-615b-4f76-a1ab-bda78e6993bf">

- If I see correctly, the shadow is only on the bottom in Storybook. I designed it to be all around the button if it's possible to implement too:
<img width="273" alt="Screenshot 2024-07-29 at 14 18 05" src="https://github.com/user-attachments/assets/54979a69-97ba-41b2-8a90-7221ef7f7f67">

- I also wonder if we should see the minus checkbox icons in Storybook when a subfolder is selected (or if it's normal that we don't see it in Storybook):
Storybook:
<img width="220" alt="Screenshot 2024-07-29 at 14 22 44" src="https://github.com/user-attachments/assets/c8076669-0dcc-47fa-9439-680d2d96c242">
With the minus checkboxes (Figma - it was in a page and not in the design system so it's normal if you haven't seen it):
<img width="658" alt="Screenshot 2024-07-29 at 14 23 46" src="https://github.com/user-attachments/assets/d6dc3008-8ed0-4345-87c3-ee593f32b865">

- In the compact mode, could you make this padding larger or is it equal to the one on the left?
<img width="231" alt="Screenshot 2024-07-29 at 14 25 26" src="https://github.com/user-attachments/assets/561c9b97-c7f8-4d28-8509-c431a40da09e">

Other than these details, it's great!

**Comment by Soliine** [comment]
Ok got it, thanks!

Yes, we can talk about number alignment and shadow, I will reach out to you.
