### ISSUE TITLE
design system: form control tag

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1476]
**Preview**

![Image](https://github.com/user-attachments/assets/0028e04d-defd-4292-94e2-3589c7c8edf9)

**Comment by pirhoo** [comment]
Component is here:

* As a tag value (default) innput: https://icij.github.io/datashare-client/?path=/docs/components-formcontrol-formcontroltag-formcontroltag--docs
* With many values, for instance, file type: https://icij.github.io/datashare-client/?path=/story/components-formcontrol-formcontroltag-formcontroltag--with-many-values
* Or even with search terms: https://icij.github.io/datashare-client/?path=/docs/components-formcontrol-formcontrolterm--docs

**Comment by Soliine** [comment]
Awesome! Very impressive work!

I have only 2 small remarks: 

- on the file type version, could it be possible to have the cursor and the focus back immediately in the search bar after I selected one item? There is this behavior in the default version and it would be great to have it in the file type version too
<img width="281" alt="Screenshot 2024-07-30 at 17 26 58" src="https://github.com/user-attachments/assets/96336b2c-ef7d-4423-a1c6-b90c8bc016b4">

- if you can, can you space out the last written query and the query which is being written (here between the left rectangle and the text)? 
<img width="62" alt="Screenshot 2024-07-30 at 17 25 23" src="https://github.com/user-attachments/assets/2bca3e06-6f12-48c1-aac8-11e205e0676f">

**Comment by pirhoo** [comment]
Done!

**Comment by Soliine** [comment]
Great!

Should we add a X on the right to delete all tags as we do for search bars?

**Comment by pirhoo** [comment]
Sure!

**Comment by pirhoo** [comment]
Done!
