### ISSUE TITLE
design system: document user action card

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1477]
- [x] Higher order popup
  - [x] card with close button event
  - [x] title
  - [x] content slot

- [x] tags
  - [x] others
  - [x] yours
  - [x] button

  

![Image](https://github.com/user-attachments/assets/e040b008-6945-4f7c-87c4-705ee211667d)

**Comment by caro3801** [comment]
the generic card is here: nothing to review in particular I think
https://icij.github.io/datashare-client/?path=/docs/components-document-documentuseractionscard-documentuseractionscard--docs

**Comment by Soliine** [comment]
Perfecto!
One small thing: can you just horizontally center align the icon+title block with the X icon?
<img width="702" alt="Screenshot 2024-08-08 at 10 42 50" src="https://github.com/user-attachments/assets/c06d3761-4be8-4a01-bf08-7ee0c8036566">
Expected:
![Uploading Screenshot 2024-08-08 at 10.45.00.png…]()

**Comment by caro3801** [comment]
Good catch thanks it's fixed 

![Image](https://github.com/user-attachments/assets/29bfa75c-4a01-424f-bf8c-42dc04246654)

**Comment by Soliine** [comment]
Fantastic!
