### ISSUE TITLE
design system : empty states

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1478]
- text
- image
- opt: image dark
- call to action
- opt: 2nd call to action

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-emptystate-emptystate--docs

**Comment by Soliine** [comment]
Excellent! I see that the illustrations work well in dark mode, that's great!

**Comment by pirhoo** [comment]
Yes, I just did a dark version with the first example but the second one works well too.
