### ISSUE TITLE
Batch star documents

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#148]

**Comment by Soliine** [comment]
Start with the table view.
Add buttons 'Star', 'Unstar' and 'Add a new tag' or the 'dropdown'.

**Comment by Soliine** [comment]
There's a small bug of unselection after starring a first batch of documents. How to reproduce:
- select 2 documents
- star these documents
- select 3 more documents
- star these documents
- click unstar -> only the last 3 documents are unstarred.
We would like to keep the documents selected even if we star them.

**Comment by annelhote** [comment]
If I reload the page, everything seems ok. So the error could come from the front side.
