### ISSUE TITLE
design system: batch search form slider

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1480]
See murmur

![Image](https://github.com/user-attachments/assets/d4fb149a-b473-4976-be91-e9f2bdeba20d)

**Comment by pirhoo** [comment]
Component is here (max value can be configured):

https://icij.github.io/datashare-client/?path=/docs/components-formcontrol-formcontrolrange-formcontrolrange--docs

**Comment by Soliine** [comment]
Perfect!
