### ISSUE TITLE
design system : document batch actions

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1481]
![Image](https://github.com/user-attachments/assets/9bf6d081-44a2-4ef1-a9e5-b8d5db6b4b7e)

**Comment by pirhoo** [comment]
Component is here with the supported features: 

https://icij.github.io/datashare-client/?path=/docs/components-search-searchresults-searchresultsactions--docs

This was the occasion to add a compact mode to `FormActions`

https://icij.github.io/datashare-client/?path=/story/components-form-formactions-formactions--compact

Which can be triggered automatically depending on the window size:

https://icij.github.io/datashare-client/?path=/story/components-form-formactions-formactions--compact-auto

**Comment by Soliine** [comment]
Great great job!

In [Compact](https://icij.github.io/datashare-client/?path=/story/components-form-formactions-formactions--compact):
- The download icon is not the right one, it should be DownloadSimple
- The order of the actions is also not the same than in the other version called [SearchResultsActions](https://icij.github.io/datashare-client/?path=/docs/components-search-searchresults-searchresultsactions--docs&globals=theme:light)
- The icon for the 3 dots are a kind of outlined version of the Phosphor icon, while it should be DotsThreeVertical in Phosphor
- I don't get the usage of the "Menu" with the burger icon, can you tell me the purpose?

**Comment by pirhoo** [comment]
It's just an example of the capacities of the Compact mode, all those buttons will not be used :) The "FormActions" component is a very abstract group of buttons: you can see it in action with [SearchResultAction](https://icij.github.io/datashare-client/?path=/docs/components-search-searchresults-searchresultsactions--docs).

For the 3 dots icon, I used the same as here:

![Screenshot 2024-08-26 at 15-02-07 Datashare – Figma](https://github.com/user-attachments/assets/03ca3213-c5b6-4dd1-bf62-b8718aef7337)

**Comment by caro3801** [comment]
For info, the icon in the compact mode can be changed through the props of FormActions https://github.com/ICIJ/datashare-client/blob/feat/new-design/src/components/Form/FormActions/FormActions.vue#L37-L39
