### ISSUE TITLE
design system: add bagde counter to icon button

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1482]
![Image](https://github.com/user-attachments/assets/0da9449a-4a7f-4f48-92af-e9fc3dc89d21)
![Image](https://github.com/user-attachments/assets/e2fb18fb-1e4e-4db5-b612-926cccd050c1)
![Image](https://github.com/user-attachments/assets/484ed30e-d7e3-456e-b6ab-66036c4c92b7)

**Comment by pirhoo** [comment]
Badge component alone is here:

* https://icij.github.io/datashare-client/?path=/docs/components-button-buttoniconcounter--docs

Or in situation, within the `ButtonIcon`

* https://icij.github.io/datashare-client/?path=/story/components-button-buttonicon--with-counter
* https://icij.github.io/datashare-client/?path=/story/components-button-buttonicon--square-with-counter

**Comment by Soliine** [comment]
Great! 👏
