### ISSUE TITLE
design system: named entity section

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1483]
- [x] named entities section
- [x] named entities section title
- [x] named entities section actions
- [x] named entities section actions entry
- [x] named entities section list
- [x] named entities section list entry
- [x] named entities section more

![Image](https://github.com/user-attachments/assets/54a5bee5-d9d0-449a-b677-e991adcaf413)

**Comment by pirhoo** [comment]
Components are here:

* named entities section https://icij.github.io/datashare-client/?path=/docs/components-namedentity-namedentitysection-namedentitysection--docs
* named entities section actions https://icij.github.io/datashare-client/?path=/docs/components-namedentity-namedentitysection-namedentitysectionactions--docs
* named entities section more https://icij.github.io/datashare-client/?path=/docs/components-namedentity-namedentitysection-namedentitysectionmore--docs

**Comment by Soliine** [comment]
Excellent!

- I see an alignment issue in the NamedEntityButton
<img width="165" alt="Screenshot 2024-08-06 at 14 55 00" src="https://github.com/user-attachments/assets/07bac9fe-22d8-448f-a27e-ff8635524a3c">
<img width="164" alt="Screenshot 2024-08-06 at 14 54 56" src="https://github.com/user-attachments/assets/bad45bb1-d962-41b2-9adf-b17e35ea19e5">

- In this same button, I made a mistake, the icon was 24 x 24 in Figma but it should be 20 x 20 (as everywhere else) while the whole button should still be 44px-tall so I played with the vertical padding of the number (which was at 3.5 and that I turned into 4)

**Comment by pirhoo** [comment]
I've made the adjustment :) It was due to a negative positioning the occurrences badge.

![Screenshot 2024-08-06 at 15-40-17 Components _ NamedEntity _ NamedEntityButton - Docs ⋅ Storybook](https://github.com/user-attachments/assets/c7c51086-f675-4ec8-ab8d-49ccf71c9b5f)

See https://icij.github.io/datashare-client/?path=/docs/components-namedentity-namedentitybutton--docs
