### ISSUE TITLE
design system: search term badge

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1484]
- [ ] query filter type + icon
- [ ] query terms
design question : how to represent negative filters ? 

![Image](https://github.com/user-attachments/assets/8d399b30-82c3-4523-9e78-a707f2abeb0e)

![Image](https://github.com/user-attachments/assets/b2da365b-da92-4e18-88d7-d0d31e1a4165)

**Comment by pirhoo** [comment]
Component is here: 

https://icij.github.io/datashare-client/?path=/docs/components-badge-badgefilter--docs

Even tho we won't use it, it's a good demonstration of all filters' displays.

**Comment by Soliine** [comment]
Great! I hope we will use it so this great work will be useful 🤞
