### ISSUE TITLE
design system: project card

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1485]
- [x] project card
- [x] project card thumbnail
- [x] project card name
- [x] project card description
- [x] project card last indexing date
- [x] project card documents count
- [ ] project card footer

![Image](https://github.com/user-attachments/assets/5a371016-5791-4f7f-9b50-041b042879c5)
![Image](https://github.com/user-attachments/assets/98193650-e024-4624-b85f-5bed98c9cdc5)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-project-projectcard--docs

**Comment by Soliine** [comment]
Awesome!
