### ISSUE TITLE
design system: project row

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1486]
- project list table

![Image](https://github.com/user-attachments/assets/b65ce375-b29c-4498-9f91-25d51c08762e)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/story/components-project-projectrow-projectrow--default

**Comment by pirhoo** [comment]
This component was fixed.

**Comment by Soliine** [comment]
Perfect!

**Comment by Soliine** [comment]
I just see that there are no tooltip on the right icons (edit and delete), should we add some here?

**Comment by pirhoo** [comment]
Done!
