### ISSUE TITLE
design system: batch search actions

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1488]
Batch search actions are present twice: in the table and in the batch search details (see #1487)

![Image](https://github.com/user-attachments/assets/c0c01c78-9c6e-4f66-8c75-b008a313929d)

![Image](https://github.com/user-attachments/assets/615147c5-fe3e-449d-a4b4-ccb3bb3005e4)

**Comment by caro3801** [comment]
component is here: https://icij.github.io/datashare-client/?path=/story/components-batchsearch-batchsearchcardactions--default&globals=theme:light

**Comment by Soliine** [comment]
I detailed my feedback in another ticket: https://github.com/ICIJ/datashare/issues/1487

I hadn't seen there was this one, sorry

**Comment by caro3801** [comment]
I'm closing it because it's not necessary anymore
