### ISSUE TITLE
design system: task progress bar

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1489]
task progress bar
- [x] percent
- [x] color/color scale
- [x] show value
- [x] show bar

(in entity recognition)
![Image](https://github.com/user-attachments/assets/71842d3d-f452-4486-85d8-8af8ae679645)

(in document addition)

![Image](https://github.com/user-attachments/assets/20354f46-52aa-4fc8-a255-6210819e500c)

**Comment by pirhoo** [comment]
I spited it into two components:

* Display Progress alone https://icij.github.io/datashare-client/?path=/docs/components-display-displayprogress--docs
* Display Status Progress which combines the progress bar with the status badge https://icij.github.io/datashare-client/?path=/docs/components-display-displaystatusprogress--docs

The latest has a "fixed width" property which can be set to true for nicer display in tables.

**Comment by Soliine** [comment]
Awesome!

 In dark mode, should we make brighter the rest of the progress bar in order to increase the contrast with the bg?
<img width="234" alt="Screenshot 2024-08-05 at 09 54 53" src="https://github.com/user-attachments/assets/0464aa80-1e5c-40e5-aeb4-846e396d1028">

**Comment by pirhoo** [comment]
I've no preference, here is an example with #6c757d:

![Screenshot 2024-08-05 at 10-00-59 Components _ Display _ DisplayProgress - Docs ⋅ Storybook](https://github.com/user-attachments/assets/5487ece7-3e4e-41a9-abab-4d095a6f0716)
![Screenshot 2024-08-05 at 10-00-48 Components _ Display _ DisplayProgress - Docs ⋅ Storybook](https://github.com/user-attachments/assets/80884fd8-d3da-4187-9ac7-03c339aa31cb)

**Comment by pirhoo** [comment]
Changes done https://icij.github.io/datashare-client/?path=/docs/components-display-displayprogress--docs&globals=theme:dark

**Comment by Soliine** [comment]
Excellent!
