### ISSUE TITLE
Export Import: Import named entities

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#149]
Use case: user exported named entities, they worked on it on OpenRefine and import them back in Datashare.
We must see which formats will be supported (same as named entity export?)

**Comment by Soliine** [comment]
Can we do that with Tarentula?

**Comment by pirhoo** [comment]
This is supported by Tarentula. The next release of Datashare will also include the possibility to copy named entities as CSV. See https://github.com/ICIJ/datashare/issues/937
