### ISSUE TITLE
design system: batch search error modal

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1490]
when a task is in error there is a modal containing the name of the task, the error message, a potential call to action

**Comment by Soliine** [comment]
I suggest this design, it is in the MODAL part of the design system in Figma:
<img width="539" alt="Screenshot 2024-07-30 at 12 31 27" src="https://github.com/user-attachments/assets/b4edc474-c155-4b42-a517-ac2b7435b271">
