### ISSUE TITLE
design system: extracted text translation

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1491]
when a document is translated there is an informative message : 
case 1: translation from guessed original language to another language
case 2: translation from determined (forced) original language to another language

**Comment by Soliine** [comment]
Design is here:

![Image](https://github.com/user-attachments/assets/fabfbc0b-935f-4abb-8127-0cd549fa65da)

A component called "Alert" was created in the design system; the button is the Banner button.

![Image](https://github.com/user-attachments/assets/9618e2c0-e041-4596-8d7c-3c67cb64fa68)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-document-documenttranslationalert-documenttranslationalert--docs

**Comment by Soliine** [comment]
Excellent! I prefer translation rather than translated, thanks for this improvement!

**Comment by pirhoo** [comment]
Ah yes, I didn't even noticed I wrote it differently :upside_down_face:
