### ISSUE TITLE
bug: impossible to delete a Batch Download

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#1492]
**Describe the bug**
On the Batch Download page, it's impossible to delete a download.

**To Reproduce**
1. Go to 'Tasks > Batch Downloads'
2. Click on the three dots on some batch download item in the list
3. Click on 'Delete'

**Additional context**
The problem seem to happen only on staging and production. (works locally)
The Delete HTTP request's answer is 200

**Comment by mvanzalu** [comment]
AMQP issue that should be fixed by merging [add-runner-event-queue](https://github.com/ICIJ/datashare/tree/feat/add-runner-event-queue)

**Comment by bamthomas** [comment]
See with TaskCancel/TaskCancelled messages to udpate tasks persistence map.
