### ISSUE TITLE
design system: display month

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1496]

**Comment by pirhoo** [comment]
Component is here:

https://icij.github.io/datashare-client/?path=/docs/components-display-displaydatetimemonth--docs

I also did other derivatives of the DisplayDatetime component for the other formats:

* https://icij.github.io/datashare-client/?path=/docs/components-display-displaydatetimeshort--docs
* https://icij.github.io/datashare-client/?path=/docs/components-display-displaydatetimelong--docs
* https://icij.github.io/datashare-client/?path=/docs/components-display-displaydatetimefromnow--docs

**Comment by Soliine** [comment]
It's great, well done!

I have a small suggestion: on https://icij.github.io/datashare-client/?path=/docs/components-display-displaydatetimefromnow--docs, have the long version of the date in the tooltip when hovering. What do you think?
