### ISSUE TITLE
refactor: split SearchBreadcrumbEntry components into generic components

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1499]
**What?**

Rename component "[SearchBreadcrumbEntryFilter](SearchBreadcrumbEntryFilter)" into somethingh like "SearchQueryTerm"

**Why?**

Search Entries will be used at multiple places to represent recommendations, tags and filters in saved searches too. Since it does not belong only to the breadcrumb it could be interesting to make it more generic.

**Comment by pirhoo** [comment]
I ended up calling this `SearchParameter` because this can be a search term, or a filter value, or both together: https://icij.github.io/datashare-client/?path=/docs/components-search-searchparameter-searchparameter--docs

**Comment by Soliine** [comment]
Great! And I made the change in Figma
