### ISSUE TITLE
design system : document user action comments

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1501]
- [x] comments
  - [x] 'hide comments'
  - [x] 'go to first'
  - [x] comment card
    - [x] avatar
    - [x] name
    - [x] date
    - [x] link to platform
    - [x] text
  - [x] text area for comment input

addition:
scroll to most recent post

**Comment by caro3801** [comment]
Component is here https://icij.github.io/datashare-client/?path=/story/components-document-documentuseractionscard-documentusercomments-documentusercomments--with-comments&globals=theme:light

**Comment by Soliine** [comment]
Amazing! Congrats :)
