### ISSUE TITLE
design system: document user action tag

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1502]
![Image](https://github.com/user-attachments/assets/106ceccd-e9a0-492c-9daa-3f30008b666c)

**Comment by caro3801** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-document-documentuseractionscard-documentusertags-documentusertags--docs

the issue with the size changing when adding an input is know

**Comment by Soliine** [comment]
It's great!
I just see that all the spacings are too small but other than that, it's great!

**Comment by caro3801** [comment]
Spacing updated 🚀

**Comment by pirhoo** [comment]
I'm going to fix the problem with the changing height of the input.

**Comment by pirhoo** [comment]
All good!

**Comment by Soliine** [comment]
New link: https://icij.github.io/datashare-client/?path=/docs/components-document-documentuser-documentusertags-documentusertags--docs
