### ISSUE TITLE
design system: form step

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1504]
* [x] form step
* [x] form step heading
* [x] form step heading title
* [x] form step heading toggler
* [x] form step heading index
* [x] form step content

**Preview**

![Image](https://github.com/user-attachments/assets/33df1063-4ed8-4661-bf86-9dd13a92096d)
![Image](https://github.com/user-attachments/assets/45840ac6-f299-4dc1-99cd-79db687a5c8b)
![Image](https://github.com/user-attachments/assets/e5641227-5d27-46da-9931-77efcbf2ac9b)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/story/components-form-formstep-formstep--default

I called it just `FormStep` because I assumed we might use it with other forms than the batch search form ;)

**Comment by Soliine** [comment]
All perfect!
Great renaming, I renamed it FormStep in Figma too 🙏
