### ISSUE TITLE
design system: form steps group

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1505]
* [x] form step group
* [x] form step group toggler

**Preview**

![Image](https://github.com/user-attachments/assets/2446409a-ddfc-4a92-9eb4-6bc5fa27ca66)
![Image](https://github.com/user-attachments/assets/3d12fd03-ac73-4187-bda5-2c46959121e0)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/story/components-form-formstepgroup-formstepgroup--default

**Comment by Soliine** [comment]
Stunning!
