### ISSUE TITLE
design system: keyboard shortcuts popover

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1507]
**Preview**

![Image](https://github.com/user-attachments/assets/2469f397-c44d-49b8-bb62-023b89c9c4ad)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-keyboardshortcuts-keyboardshortcutspopover-keyboardshortcutspopover--docs

**Comment by Soliine** [comment]
It's great!

Just one thing: when we hover the "See all shortcuts" button, the caret remains in secondary and I think it would be better if it turned the same color as the text, that is to say white. 

I see that it's a button outline action but couldn't find it's hovered version with a right icon in storybook

**Comment by pirhoo** [comment]
I changed the color to current button color on hover :)

**Comment by Soliine** [comment]
Looks stunning!
