### ISSUE TITLE
design system: keyboard shortcuts section

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1508]
**Preview**

![Image](https://github.com/user-attachments/assets/5467c374-f1ad-4459-bf05-557fccb79876)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-keyboardshortcuts-keyboardshortcutssection-keyboardshortcutssection--docs

**Comment by Soliine** [comment]
Excellent!
