### ISSUE TITLE
refactor: use compact form actions to build document user actions

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1511]
DocumentUserAction can be refactored to use the new FormActions in compact mode:

https://icij.github.io/datashare-client/?path=/story/components-form-formactions-formactions--compact

**Comment by caro3801** [comment]
https://github.com/ICIJ/datashare-client/commit/05ce2e45969200fb6feead5fd3cb8c7392db40d6

**Comment by pirhoo** [comment]
Very good call!
