### ISSUE TITLE
design system: plugin/extention card

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1514]
"AddonCard" could be the generic name

**Preview**

![Image](https://github.com/user-attachments/assets/938ce990-c31e-46ae-9e3a-10e4d5635c46)

**Comment by caro3801** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/story/components-addon-addoncard--docs

**Comment by Soliine** [comment]
Simply perfect!
