### ISSUE TITLE
design system: button toggle batch mode

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1525]
**Preview**

![Image](https://github.com/user-attachments/assets/6716da2d-cd3f-4ee0-be9b-4674f30b6fdc)
![Image](https://github.com/user-attachments/assets/ab551a3e-6c23-4292-8db8-46d02529a728)

**Comment by caro3801** [comment]
component is here: https://icij.github.io/datashare-client/?path=/docs/components-button-buttontogglebatchmode--docs

**Comment by Soliine** [comment]
Top!
