### ISSUE TITLE
design system: login locale dropdown selector

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1527]
**Preview**

![Image](https://github.com/user-attachments/assets/48e17521-b147-4b3b-a25a-44becedf0fe3)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/docs/components-login-loginlocaledropdownselector--docs

**Comment by Soliine** [comment]
Awesome!

- Can you make the left padding here bigger?
![Image](https://github.com/user-attachments/assets/31d85637-2b9a-45a5-a2f9-3a33ed86c428)

- In my browser, I see a disconnection here, do you have it too and if yes, can you fix it if it is possible?
![Image](https://github.com/user-attachments/assets/751e91dc-aeeb-419a-829e-2a477c12a2b9)

**Comment by pirhoo** [comment]
I increased the horizontal padding.

Regarding the arrow crispy pixel, unfortunately we can't do much as it drawn in CSS. But I suppose you only see it when you zoom in? It's the same arrow component that every other popover btw.

**Comment by Soliine** [comment]
It looks fabulous!

It's not only when I zoom in that I see it but it's ok if we can't do anything about it ;)

I notice that in dark mode, when I hover languages, there is the colored background
<img width="322" alt="Screenshot 2024-09-04 at 10 31 06" src="https://github.com/user-attachments/assets/bb21f2d1-c4a1-4c75-b964-d2876a8a4821"> 
while it doesn't appear in light mode
<img width="274" alt="Screenshot 2024-09-04 at 10 51 38" src="https://github.com/user-attachments/assets/1d5f9487-1fc3-46f3-9875-40dbacfc86a0">

**Comment by pirhoo** [comment]
It's legacy from the previous design, in fact both have a hover background but the contrast is not enough to be visible on light theme. I increased it:

![Screenshot from 2024-09-04 11-13-43](https://github.com/user-attachments/assets/ca99d520-1d81-4114-a99d-489678050229)

**Comment by Soliine** [comment]
It looks great! Thanks for the explanations too
