### ISSUE TITLE
refactor: rename "named entity" to "entity"

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1537]

**Comment by pirhoo** [comment]
@Soliine @caro3801 the change was done on new components. That means the documentation on all named-entity related components have a new URLs: 

* https://icij.github.io/datashare-client/?path=/docs/components-entity-entitybutton--docs
* https://icij.github.io/datashare-client/?path=/docs/components-entity-entityoccurrences--docs
* https://icij.github.io/datashare-client/?path=/docs/components-entity-entitypopover-entitypopover--docs
* https://icij.github.io/datashare-client/?path=/docs/components-entity-entitysection-entitysection--docs

**Comment by Soliine** [comment]
Great! 

I see a small thing here https://icij.github.io/datashare-client/?path=/docs/components-entity-entitybutton--docs

<img width="577" alt="Screenshot 2024-09-04 at 16 04 52" src="https://github.com/user-attachments/assets/bf3a7aeb-dba1-478f-9f24-46064bff1178">

The left icon is aligned with the top of the text while it should be vertically centered

Is it possible to fix it?

**Comment by pirhoo** [comment]
The baseline is higher than in your schema because the text take in fact more height for letter with descender like "j",  "q",  "p", or "y". The descender is the portion of a letter that extends below the baseline, which is the line upon which most letters "sit."

The real height of the text is like that: 

![Screenshot from 2024-09-04 16-44-56](https://github.com/user-attachments/assets/de2676b1-94ff-4ffa-bc2b-aa751e448699)

As you can see everything is centered :)

**Comment by Soliine** [comment]
Ok I see! Thanks for explaining :)
