### ISSUE TITLE
Create an online demo of Datashare: datashare-demo.icij.org

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#154]
Users should be able to navigate a sample of documents in Datashare publicly online.

**Comment by Soliine** [comment]
Also, should we index Lux Leaks in the demo website so users could already navigate in Datashare with real data?

**Comment by annelhote** [comment]
Or maybe LuxLeaks as the data are public in DocumentCloud ?

**Comment by Soliine** [comment]
https://github.com/ICIJ/datashare/issues/373
