### ISSUE TITLE
design system: project entries

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1542]
A list of projects that can either be listed in a table or in card.

**Comment by pirhoo** [comment]
The component is here:

* as table: https://icij.github.io/datashare-client/?path=/story/components-project-projectentries-projectentries--default&args=layout:table
* as cards: https://icij.github.io/datashare-client/?path=/story/components-project-projectentries-projectentries--default&args=layout:cards

**Comment by Soliine** [comment]
Awesome! It's great to see things taking shape :)

Small feedback: can we add a sorting icon on the "Updated on" column too?

**Comment by Soliine** [comment]
I just saw that you already did the clickable project name, that's awesome!

**Comment by pirhoo** [comment]
I changed so the buttons of the project row are only visible on hover:

https://icij.github.io/datashare-client/?path=/story/components-project-projectentries-projectentries--default&args=layout:table

I **did not** hide them in the project card otherwise it would create a lot of blank space:

![Image](https://github.com/user-attachments/assets/3f36ea20-3199-4986-9b76-933fd078fb4c)

**Comment by Soliine** [comment]
Great additions!

The fill of the two buttons is transparent. I designed them with a body-bg (white) background on my side. Do we need this transparency somewhere else?
<img width="907" alt="Screenshot 2024-09-12 at 11 38 13" src="https://github.com/user-attachments/assets/c92e30ee-6a45-40c8-b0bd-4ad8f52181ee">

**Comment by pirhoo** [comment]
Oups sorry, it's fixed now!

**Comment by Soliine** [comment]
Awesome!
