### ISSUE TITLE
design sytem: page offcanvas

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1543]
"offcanvas" sidebar based on Bootstrap's offcanvas:

https://getbootstrap.com/docs/5.3/getting-started/introduction/

Useful to build the page settings, for instance.

![Image](https://github.com/user-attachments/assets/0226de13-2074-4c0a-a6f3-a997499fdc2f)

**Comment by pirhoo** [comment]
Component is here: 

https://icij.github.io/datashare-client/?path=/docs/components-pageoffcanvas-pageoffcanvas--docs

**Comment by Soliine** [comment]
Awesome!
