### ISSUE TITLE
Upgrade Tika from 1.18 to 1.21

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#157]
We could upgrade tika to 1.21 like suggested by this https://twitter.com/_tallison/status/1130101805705310208

We must test PDF extraction.

**Comment by Soliine** [comment]
And also Tesseract from v4.0 alpha to v4.1.0 ? https://github.com/tesseract-ocr/tesseract

**Comment by bamthomas** [comment]
done with commit ICIJ/extract@6cc8702505856941396b36ca51ecc5c74fd71c4a
