### ISSUE TITLE
design system: form fieldset

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1571]
Form group with an horizontal layout and an icon:

![Image](https://github.com/user-attachments/assets/ed4cfb67-7c4b-4886-9145-f010d96769c5)

**Comment by pirhoo** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/story/components-form-formfieldset-formfieldset--default

**Comment by Soliine** [comment]
Excellent job!
