### ISSUE TITLE
design system: signle select path mode

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1572]

**Comment by Soliine** [comment]
![Screenshot 2024-09-16 at 17 33 12](https://github.com/user-attachments/assets/2b2d0d6b-8055-420d-8629-c1f27142c9c5)

**Comment by pirhoo** [comment]
New selected state can be seen here: 

https://icij.github.io/datashare-client/?path=/story/components-pathview-pathviewentry--default&args=selected:!true;selectMode:!true;
