### ISSUE TITLE
designer: board view

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#1592]
**How users switch to board view**
-> on all search pages, they open the page settings and tick "board view" (the current search is kept as it is):
![Image](https://github.com/user-attachments/assets/1a9eafa9-13f6-46b4-8a8e-b9a65b1fdde8) 

**How users put / remove document in a column**
-> all documents are by default in the "Uncategorized" column, their DocumentUserActions board entry (with the Phosphor's "kanban" icon) shows "0" when uncategorized and once the document has been put in a column, it shows "1"

-> on a document, users hover the DocumentUserActions board entry and select the desired column:
![Image](https://github.com/user-attachments/assets/17647946-6076-47b6-9917-13b213dec91f)
-> on the board view, they drag and drop one document card to the desired column:
![Image](https://github.com/user-attachments/assets/7ebde586-903c-48ed-b16d-2669986b18b3)

**How users put / remove several documents in a column**
-> on all views, users click the batch action icon ("cards" icon in Phosphor) and click "Move to" (we should see the white kanban icon, sorry I can't find why Figma doesn't show it):
![Image](https://github.com/user-attachments/assets/f3950c9b-dab4-4e35-bbb1-967f3b869ee2)

-> on board view specifically:
static: ![Image](https://github.com/user-attachments/assets/99d63d4b-9850-4598-b5ab-84c6bd60313f)
hover: ![Image](https://github.com/user-attachments/assets/36606d70-bd44-481c-af4d-04a314803bbe)
![Image](https://github.com/user-attachments/assets/ac5a4d9d-587d-4a36-8bc4-07f377a91576)

**How users filter documents by their board column**
![Image](https://github.com/user-attachments/assets/063ac981-b9d3-44d5-a727-02b4f39fd113)

Then they can see and remove the filter in their breadcrumb:
![Image](https://github.com/user-attachments/assets/a3655bef-fe46-40f0-9847-abbfcc2ac8f5)

Other UX questions:

- can users remane columns or not
=> we'll see later

- can users have one board for one search 
=> atm, we encourage users to save their search and switch to board view

**Comment by bamthomas** [comment]
to be discussed
