### ISSUE TITLE
Download child documents

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#165]
How to reproduce:
- open a child document
- click "download"
-> it downloads the parent document whereas it should download the child document.

**Comment by bamthomas** [comment]
Since the 14th of may 2019 the hash of documents has changed cf the 080edb90a6635955ece697b5dd3484881af6f70f commit. 

So it doesn't work for SHA-256.

We've made a workaround by rolling back the hash encoding : cf 9006d0c

**Comment by bamthomas** [comment]
there is still the PNG errors to explain

**Comment by Soliine** [comment]
Bug spotted in Cronus : 7dd28c1b2d9f6e49f8a4f9eade8701da6dafb9e0217f4c11f4ea79dd66d21fc5/0305461f56178e95a7f4406e67239206699e585118a8a603d4f7aa00f9846833
