### ISSUE TITLE
Update translation JSON files on the front

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#168]
Compare 2 json files to find the missing key.
Let's use jq.

**Comment by annelhote** [comment]
Would you translate these sentences in Spanish :
- "Your browsing history"
- "The last 500 documents you opened with Datashare from this computer."
- "Your history is empty"
- "Clear history"
Would you translate these sentences in French :
- "Your browsing history"
- "The last 500 documents you opened with Datashare from this computer."
- "Your history is empty"
- "Clear history"

**Comment by annelhote** [comment]
To compare first level of json keys between English and Spanish translations files :
`diff <(cat src/lang/en.json | jq 'to_entries[].key') <(cat src/lang/es.json | jq 'to_entries[].key')`

**Comment by annelhote** [comment]
@Soliine I assigned you this issue because I need the translation of the sentences listed up there ^.

**Comment by bamthomas** [comment]
maybe you could put a shell script at the root or in a `/tools`, `/bin` or whatever folder in the repo ?

**Comment by annelhote** [comment]
> maybe you could put a shell script at the root or in a `/tools`, `/bin` or whatever folder in the repo ?

Good idea, I'll do that.

**Comment by Soliine** [comment]
**To start with French (I just asked for Spanish and will let you know when it's ready):**

"Creation date" 
Date de création

"Missing date" 
Date manquante

"Thread ID" 
ID du fil de discussion

"Show named entities" 
Afficher les entités nommées

"Warning! The named entities will be highlighted and may replace text underneath. This does not impact your search results."
Attention ! Les entités nommées seront surlignées et cacheront le texte. Ceci n'affectera cependant pas les résultats de recherche.

"Remove all your documents from Datashare"
Effacer tous les documents de Datashare

"To be 100% safe, please remove your documents from the Datashare folder on your computer – don't forget to empty your trash bin of all Datashare documents! Make sure you have a copy of them in another secure place beforehand."
Pour être en sécurité, effacez tous les documents dans le fichier Datashare de votre ordinateur - n'oubliez pas de vider tous les documents Datashare de votre corbeille également ! Assurez-vous d'avoir gardé une copie de vos documents dans un endroit sûr.

**Comment by Soliine** [comment]
French translations pushed.
