### ISSUE TITLE
Facet to filter starred/unstarred documents

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#171]
Users should be able to filter all / starred / unstarred documents:
- the facet will look like other facets with only 3 lines (all, starred, unstarred) and the number of documents for each line. It will have the same behavior as other facets.
- in the server version, it will be in the 2nd position, after "projects" and before "file type".
- in the local version, it will be in the 1st position.

**Comment by annelhote** [comment]
- [ ] Translate items ("Not")
- [ ] If "All" is selected, click on it should have no effect. For now, it unselects "All"
- [ ] Should not display the "Show more"

**Comment by Soliine** [comment]
There seems to be one or two bugs. How to reproduce:
*1*
- go on page 2 of results' page
- star some documents
- tick "Starred" in the Starred facet
-> the results display "No result found"
*2*
Then, click "Reset filters"
-> the "Starred" item goes back to zero.

**Comment by annelhote** [comment]
2 bug are here listed :
- [ ] On click on "Reset", the starred docs count is reset to zero.
- [ ] For each facet, the from attribute of the query is not reset on new item selected / unselected.

**Comment by annelhote** [comment]
- [ ] Rename "Starred" by "All" in the items facet.

**Comment by Soliine** [comment]
There is a bug when users select 'Starred' or 'Not starred' in the facet: the applied filters displays 'all' whereas it should display either 'Starred' or 'Not starred'
<img width="400" alt="Star bug" src="https://user-images.githubusercontent.com/17233829/61207208-cb076000-a6f4-11e9-9622-f3ccb523b57d.png">
