### ISSUE TITLE
The keyboard shortcut does not work for mac

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#172]
**Windows & Linux:** 
- Next document ( ctrl + → )
- Previous document ( ctrl + ← )

**Mac:** 
- Next document ( cmd or ⌘ + → )
- Previous document ( cmd or ⌘ + ← )

**Comment by annelhote** [comment]
To detect the OS, use the getOS function in the src/utils/utils.js file.

**Comment by Soliine** [comment]
The "fn + F3" (to search in document) does not seem to work on Mac.
