### ISSUE TITLE
Apply Elastic Search's rules to the counter in "Researched terms in this document:"

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#174]
How to reproduce:
1. Search for an exact phrase _with any punctuation_ in the main search bar. For example : "Me contacter:" 
2. Elastic Search doesn't take the punctuation into account -> it filters documents that contain "Me contacter:" and "me contacter". 
3. But in these same filtered documents, the count of "Me contacter:" in the "Researched terms in this document:" section is at 0.
4. It would be more consistent to have here the same counting rules as in Elastic Search.
<img width="285" alt="Screen Shot 2019-06-07 at 3 03 04 PM" src="https://user-images.githubusercontent.com/17233829/59105974-8211fe00-8935-11e9-9004-3e25b633fea7.png">

**Comment by annelhote** [comment]
Add support to reserved characters : https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-query-string-query.html#_reserved_characters. But ES would produce the same result with "word:" than with "word".

**Comment by annelhote** [comment]
I try to correct it but it overlaps the advanced functionalities like negation (-) or searching in a specific field (:). So the only option would be the escape the reserved character by a slash (\) in the query field to get some search results. Warning, ES results are the same with or without reserved characters !
