### ISSUE TITLE
Go back to the last result page opened when clicking the grey zone

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#175]
How to reproduce:
- Search for a term
- Go to page 2 (_"from=25"_ in the URL) or more
- Apply a filter
- Open a document
- When you click "Back to the search results", you get back to the page 2 with the same filter applied
- But if you do the same steps but click anywhere on the left greyed out zone, it reset all the filters and get back to page 1 (_"from=0"_ in the URL)
-> it would be more consistent to get to the same page with the same filters, as you do when you click "Back to the search results".

**Comment by annelhote** [comment]
Reproduced in prod. Even worse, the facets are reset but the item is still ticked !
