### ISSUE TITLE
Emails: lower the bodies of emails and show the header of documents

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#181]
Under the current design, when users open an email thread, they cannot see the header of document where there are important functionalities (among which"researched terms in this document" and "show named entities"):
<img width="837" alt="Screen Shot 2019-06-13 at 6 08 28 PM" src="https://user-images.githubusercontent.com/17233829/59449036-9c9d1900-8e06-11e9-98c9-95a405675166.png">

It would be great to lower the bodies of emails and see the header.

**Comment by Soliine** [comment]
This should resolve the problem of not searching all the emails of a thread when users click control+F.
Expected: when users search terms in a document via control+F, the search scope should cover all the emails of a same thread.

**Comment by Soliine** [comment]
During the demo, we reported a bug: the 'show named entities' toggle button is missing on emails. No named entities are shown.

**Comment by pirhoo** [comment]
Looks fine to me:

![Screenshot_2019-07-10 Datashare(1)](https://user-images.githubusercontent.com/471176/60976559-2ec50e00-a32e-11e9-86f7-c18db5691337.png)
![Screenshot_2019-07-10 Datashare(2)](https://user-images.githubusercontent.com/471176/60976563-31276800-a32e-11e9-97c4-e49b5c43e938.png)

Do you have an example?
