### ISSUE TITLE
Tag a document

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#182]
Users should be able to tag single documents (we will develop batch tagging after).

Tags are shared among projects: all members of a project should all be able to create, read and delete tags.

**To create a tag:**
- Users open a document
- Let's recall the tab "DETAILS" into "TAGS & DETAILS" (which will become "TAGS, DETAILS & NOTES" or another name when we will develop annotation later). This tab is at the 2nd place, between "EXTRACTED TEXT" and "NAMED ENTITIES" (when there are named entities).
- When users click this tab, the tab opens and the focus directly goes to the field "New tag", below the details
- When users are finished typing a new tag, they press enter to validate it or press the button "ADD"
- The tag then is listed below in the list of existing tags sorted by alphabetical order

**To read a tag:**
- All users of a project can read tags by opening the tab "TAGS". 

**To delete a tag:**
- Each tag can be deleted by clicking the cross at the end of the tag
- The confirm button of Murmur asks "Do you want to delete this tag?" https://icij.github.io/murmur/#/components/confirm-button

**To edit a tag:**
Users cannot edit a tag. They have to delete the one they want to edit and create a new one.

Linked issues:
- Facet: tags #183 
- Search a tag #185 
- Suggestions of tags #186

**Comment by bamthomas** [comment]
cf :  
f245ba74a1dbee3631120ab29d38a82dda31e775 : [db] adds ner tags for documents
92c51d17959ad878fe9bcf29aa0e66ffe53077b4 : adds a document tags
9b6095fdf8f2cc6773467e7c9a6bbd7edb01b002 : wires document tags
d519da7dce514f6ba1131b7db137382836af6ae4 : adds a distinct for tags
4c0c0072482851e9367d9cdc9850e79c27d1dc60 : adds tags into elasticsearch
3c852f5726ea0fa4858c02bb5981a02b36769582 : adds tags into ES for embeds

**Comment by annelhote** [comment]
Untag several documents.

**Comment by bamthomas** [comment]
the `,`in the tag list for the get is used to request the database with an `IN` operator in SQL. That's why the result is like an `OR`

**Comment by annelhote** [comment]
We here encounter a previous problem about ES strong limitation of the number of total fields in index :
`ElasticsearchStatusException[Elasticsearch exception [type=illegal_argument_exception, reason=Limit of total fields [1000] in index [INDEX_NAME] has been exceeded]]`
This supposed to have been fixed by commit 7eff86a but it is not the case in production, due to AWS limitations (source needed).
So this functionality works on small index, but not on big ones.
@bamthomas @Soliine

**Comment by annelhote** [comment]
The frontend is not refresh after first tag ever on a document. Solution : request for doc after tag add instead of trying to directly add it to the document store.
