### ISSUE TITLE
Facet: tags

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#183]
Users should be able to filter documents by tags thanks to a facet.

- The facet will appear between "Starred" and "File types".
- The title of the facet is "TAGS".
- There is a search functionality: "Search in Tags...". It behaves like the search functionalities in other facets.
- Tags are listed in this facet by order of frequency.
- The number of documents tagged by each tag appears at the end of each line with the hover "XXXX tagged document(s) in this project".

_Linked issues:_
_- Tag a document_ #182
_- Search a tag_ #185 
_- Suggestions of tags_ #186

**Comment by annelhote** [comment]
When I add a tag on a document, it did not refresh the facet.
