### ISSUE TITLE
Configuration parameter for preview host

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#184]

**Comment by bamthomas** [comment]
Datashare is taking every env variable prefixed by `DS_DOCKER_`and converts it into camel case internal variable. So it already works.

cf c72539d and a1ced3b

**Comment by bamthomas** [comment]
Seen with @pirhoo. This issue can be closed.

**Comment by pirhoo** [comment]
Indeed ! This is fantastic tho.
