### ISSUE TITLE
Suggestions of tags in main search bar

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#186]
Let's see if it's interesting that, when a user search a tag in the main search bar, there are suggestion of tags in the drop down menu, as there are named entities.

Server mode: the tags suggested are only the tags of the project (not in other projects).

If possible, suggestions appear in a dropdown in frequency order (most to least frequently used in the project).

Each suggestion can be clicked and is then selected.

**Comment by annelhote** [comment]
Just to say, the defaukt search is only on the Named Entities, and the tags now. Maybe "All fields" is a little bit too much as a label ?

**Comment by pirhoo** [comment]
The suggestion is on named entities and tags, but once you hit enter, it searches on all fields :rocket:
