### ISSUE TITLE
Doc list with status

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#189]
As a user I want to see the list of my filesystem files and their status (None/Indexed/NER).

The path/file name will be on one column. A column size will be added.

A back-end endpoint will be made that sends back as json the list of files. 

The screen will allow to paginate the results

![document_list](https://user-images.githubusercontent.com/551723/59858782-ea240380-937b-11e9-9d0f-bdf45f70127f.png)

**Comment by Soliine** [comment]
We will re-write all the issues regarding indexing when we will start it as an epic.
