### ISSUE TITLE
Bug on CircleCI : "make: execvp: yarn: Permission denied"

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#19]
According to @pirhoo , we should find a workaround on the Circle CI's github. Something about deleting a file.

**Comment by annelhote** [comment]
I simply removed the way to force to install the latest node and the latest yarn on the node image on CirlceCI, see commit #a2e60e96f3629391ddb8771acf67859a9e8ae38c.

**Comment by annelhote** [comment]
To test it, create a new tag and push it. Then CircleCI should create a new image whithout any error.

**Comment by annelhote** [comment]
FYI, I also had to replace the deployment mode into the ansible config file.

**Comment by bamthomas** [comment]
thanks I had forgotten this one
