### ISSUE TITLE
Open single document in a new window

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#191]
When users right click on the title of a document in the results' column, the document open in a new window but in a single view (no search result in the background).

**Comment by pirhoo** [comment]
I added special button to open in separated window:

![Capture d’écran de 2019-07-08 14-59-53](https://user-images.githubusercontent.com/471176/60812142-1c619d80-a191-11e9-9f68-c86fd5a789e4.png)
![Capture d’écran de 2019-07-08 14-59-04](https://user-images.githubusercontent.com/471176/60812143-1c619d80-a191-11e9-9a4b-2925e450e444.png)
