### ISSUE TITLE
User uploads a CSV to run batch searches and gets the results in CSV

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#193]
- User clicks on "Batch search" button
- A new page opens
- User fills 3 fields: 
  * Name
  * Description
  * CVS upload + tip "The CSV file should contain one column with all the searches, one per line."
NB: All batch searches are private by default.
- User can see the list of their own past and current batch searches
- User clicks "Download results" and gets a CSV with the results containing 3 columns (query, document url, path).

**Comment by annelhote** [comment]
- The url will be /#/batch-searches
- The form will have 3 fields :
  - name - textinput - required
  - description - textarea
  - file - file - required - CSV format only

**Comment by annelhote** [comment]
[front] ToDo List :

- [ ] Add a button to download results as a CSV file on BatchSearchResults page.
- [ ] Display the BatchSearch details (number of results, number of query, status, creation date) at the top of the BatchSearchResults page.
- [ ] Display the list of the queries, "All" at the top of this list. On click of the query, display only the results about this query on BatchSearchResults page.
- [ ] For each result, collect the document details (like contentType, documentSize...) and add the dedicated column on BatchSearchResults page.
- [ ] Add a link to batchsearch page in the top menu.

**Comment by bamthomas** [comment]
```
Caused by: java.io.IOException: Tried to send an out-of-range integer as a 2-byte value: 70000
	at org.postgresql.core.PGStream.sendInteger2(PGStream.java:237)
	at org.postgresql.core.v3.QueryExecutorImpl.sendParse(QueryExecutorImpl.java:1442)
	at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1767)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1328)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	... 17 common frames omitted
```

**Comment by Soliine** [comment]
- In the results, there is a column called  "documentId" but there is no URL. Could we have URLs so people can copy paste it? Can make sure the CSV, when opened with Excel, create an hyperlink for the URLs? It would save time to just have to click them instead of copy paste the URL.

- I mistakingly run the batch search for a project in another project. There were results. It seems (but we should investigate more) that each query is not an exact query. The results of the batch search in the project is 60 000 results for the same query "XXX". But there is no results for "XXX" (exact phrase) in the project while there are some results for XXX (without double quotes).

- The column "State" says "Failure" while they are successes.

- The column "Number of results" for the last query says "60 804" and there are 60 804 results. Isn't the limit of 60 000 working?

- It would be great to name the CVS of results with the name of the batch search.

**Comment by Soliine** [comment]
- paginate results
- add content type
- base URL

**Comment by Soliine** [comment]
put the number of results by query between brackets in the contextual column (left)

**Comment by annelhote** [comment]
- [ ] Bruno will implement the filter by query and the sort by content type, query and others
- [ ] Put between brackets the number of results by query
- [ ] Base URL in the CSV : http: is missing
- [ ] Pierre will redesign the results' screen (the contextual window)

**Comment by Soliine** [comment]
Bug: it stays at from=100 in the URL if users change the query after they previously navigate to the second page

**Comment by Soliine** [comment]
After the refactoring, the bug reappeared: it stays at page=2 in the URL if users change the query after they previously navigate to the second page
