### ISSUE TITLE
Avoid extraction of punctuation and single letters

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#194]
In a project (C*s), Mitie was asked to extract named entities. Punctuation and letters came out. It would be great to "clean the named entities" or see what we can do.
<img width="243" alt="NE punctuation" src="https://user-images.githubusercontent.com/17233829/60032585-2cfd1880-96a7-11e9-89f0-727ff97c37eb.png">

**Comment by bamthomas** [comment]
It was Ixapipe pipeline. 
A delete by query has been done on C*s and these characters are not there anymore.
