### ISSUE TITLE
After switching projects, filters remain ticked but not applied

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#196]
Spotted on Chrome.
How to reproduce:
- in one project, select 'PDF' in File Type for example
- go to another project
--> PDF is still ticked but the filter is not applied to the actual results.

Resolution: either reset all filters when switching projects or keep them selected and effective.

**Comment by annelhote** [comment]
Bug reproduced.

**Comment by annelhote** [comment]
It was previously decided to reset all filters on changing selected index #51.
