### ISSUE TITLE
Create shortcuts to navigate tabs

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#200]
Once a document is opened, to go from one tab to the next on the right (ex: from "Extracted text" to "Tags & Details" and then "Preview"), users could press →. And ← to go to the left tab.

We'll see where we show all the shortcuts to users (FAQ, overlay, etc)

**Comment by annelhote** [comment]
- [ ] Find another keyboard shortcut

**Comment by Soliine** [comment]
On my Mac, Control + → (and Control + ←) are available. Can you check on your PCs?

**Comment by annelhote** [comment]
For Mac Users : cmd + option + arrow up
For others : ctrl + alt + pageup
