### ISSUE TITLE
datashare is not http basic auth compatible

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare#202]
Hi,

I was trying to put datashare behind an nginx reverse proxy with the following configuration:

```
# Default server configuration
#
server {
	listen 127.0.01:80;
	server_name xxx.onion;

	location / {
	        auth_basic_user_file /etc/nginx/.htpasswd;
        	auth_basic "Access restricted";

		proxy_pass                            http://localhost:8080/;
		proxy_buffering                       off;
	}
}
```

Now this works fine, I get authenticated and all, but then Datashare thinks it's being authenticated from ```xemx``` and I see a cute kitten, but I can't search.

Specifically, I get redirected to: ```http://xxx.onion/auth/xemx/signin```.

Could this authentication method be supported somehow? :)

I'm running version: Version 1.72.2

**Comment by bamthomas** [comment]
Hello @DrWhax 

Thanks for the issue. You're right, for now datashare doesn't support basic auth. For the server mode we implemented OAUTH.

The parameters by default are in the [datashare.properties](https://github.com/ICIJ/datashare/blob/master/datashare-web/src/main/resources/datashare.properties) but you can override them with the command line.

The parameters related to oauth are the following : 

* `sessionTtlSeconds` : time to live before the session expires (default `43200` = 12h)  
* `oauthClientId` : app id for the authorization server
* `oauthAuthorizeUrl` : authorization server authorize url
* `oauthTokenUrl` : authorization server token url 
* `oauthApiUrl` : authorization server url to retrieve user data (`me.json`)

* `oauthCallbackPath` : datashare url path sent by datashare called by authorization server (default `/auth/xemx/callback`)
* `oauthSigninPath` : signin url in datashare (default `/auth/xemx/signin`)
*` protectedUriPrefix` : protected prefix (defaults to `/api/`)

**Comment by bamthomas** [comment]
We will probably make things change (maybe with basic auth) with the story #154
