### ISSUE TITLE
Flush the database on deleting my index

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#203]
Local version only.

**Comment by bamthomas** [comment]
This raises questions : 

* for now the `IndexResource` has a dependency on a Indexer instance and `DocumentResource` uses a `Repository`. Does it make sense to add a `Repository` instance in `IndexResource` ? Or maybe we could create a new endpoint to clean the database in `DocumentResource` ?
* the query `DELETE /api/index/delete/all` deletes the user's index (local-datashare, or user-datashare in server mode). Do we remove only the project related to the user also ? (local-datashare or user-datashare) ?

**Comment by annelhote** [comment]
- Sorry but I don't get the difference between Index and Repository ?
- I would say yes to the second question.

**Comment by bamthomas** [comment]
the *Resource is the web interface and Indexer/Repository are the "service" layer respectively to Elasticsearch and Database.

So we had IndexResource -> Indexer and DocumentResource -> Repository 

So if we want to remove something into the database, we should add a dependency between IndexResource and Repository.

**Comment by bamthomas** [comment]
cf ad83e8ecf5c0b4d273bc37aa279242b4f4efab60

**Comment by Soliine** [comment]
Yes we need to implement this for batch searches.

**Comment by annelhote** [comment]
Should flush the batchSearches too.
