### ISSUE TITLE
Readonly files not downloading 

### ISSUE THREAD

**Issue by Orocalian** [ICIJ/datashare#206]
Attempted to help user pull files from DS. But there were format errors between .xlsx (2007)and the .xlw (2019) versions of excel, but I got the error messages when I changed the file tag extension name.

**Comment by annelhote** [comment]
File is on Cr... index. Id : 50041258b9cc730cd7db8af8c2b3bae15f98d892a8e5971712cf35c0398d1865. Routing : 3858ccda0eae409b704704efc71b6f350f3643ca56b9cb0f4cffef6365a57761. I was able to download it and to open it with LibreOffice with its extension .xlsx. Can't see anything wrong...
