### ISSUE TITLE
Select date range in date filters

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#207]
Let's discuss which date picker control we opt for (ressource: https://uxplanet.org/how-to-design-a-perfect-date-picker-control-7f47d1290c3a)

**Comment by annelhote** [comment]
Remove date and range popover.

**Comment by annelhote** [comment]
- [ ] Problem while editing the date directly in the input.
- [ ] On active filters, label are timestamp instead of human readable date.

**Comment by Soliine** [comment]
Internationalization: dates in the selector do not switch to new language after new language selected. But it does after page is refreshed.
In applied filters, it never changes.
