### ISSUE TITLE
Main search is not working with document named entities mentions

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#208]
By now if a Document has a named entity "John Doe" and the user is searching "john" the document is selected just because ES finds john in the content. We are not finding the document because it has a named entity "John Doe".

Main user search is made with has parent sub query like :
```
"has_parent": {
   "parent_type": "Document",
   "inner_hits": {
      "size": 30
   },
    "query": {
       "match": {
       "content": "john"
    }
}
```
It should be a `has children` relationship with the mention field matching the query like : 

             {
                "has_child": {
                  "query": {
                    " match": {
                      "mention": {
                        "query": "john",
                      }
                    }
                  },
                  "type": "NamedEntity"
                }
              }

Like shown by this unit test : d613e2c7b2c5c8daa6c659cbecfe48d33bbe30a0

**Comment by annelhote** [comment]
For a complex search, it fails. The simple query should be replaced by a "query_string".

**Comment by bamthomas** [comment]
Yes. For the record, I add the ES issue we discussed with @annelhote : 
https://github.com/elastic/elasticsearch/issues/15627

**Comment by annelhote** [comment]
No need to query the Named Entities specifically because the default_field is "*". Please see this test : https://github.com/ICIJ/datashare-client/blob/faef4dd8daeb30616c3611cb0458c766a6bca8e7/tests/unit/specs/store/modules/search.spec.js#L605
