### ISSUE TITLE
Enlarge the scope of the counter of occurrences to emails' header

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#209]
Currently, if users search for an email address which is the sender or the recipient of an email, the counter of occurrences within a document misses it because the scope of the search is limited to the extracted text of emails.
What we wish is to allow users to see the number of occurrences also in the header of an email: recipient, sender, object, date, and any other data there.

**Comment by annelhote** [comment]
Discussion with @pirhoo. It is not a bug and our users are supposed to understand it. One way to make it clearer would be to replace that :
![Screenshot from 2019-08-09 11-43-10](https://user-images.githubusercontent.com/1478919/62770256-ef0f5480-ba9a-11e9-9120-e30a2d7d7c1f.png)
by "In this document: bthomas is in the metadata".
