### ISSUE TITLE
Put 'Tags' above 'Details'

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#210]
In order to avoid horizontal scroll bars and a blank space behing 'Tags', we can put 'Tags' above 'Details' as it should not take too much room.
<img width="835" alt="Screenshot 2019-07-15 at 13 56 32" src="https://user-images.githubusercontent.com/17233829/61214545-74a41c80-a708-11e9-8256-65bd7bd463cd.png">

**Comment by Soliine** [comment]
We lost the focus on the 'Add a new tag' field. 
When user opens the 'Tags & Details' tab, the focus should directly be on 'Add a new tag' as before.

**Comment by pirhoo** [comment]
Arg yes! It's because I used [a new component](https://alexurquhart.github.io/vue-bootstrap-typeahead/) to implement the suggestion and it doesn't have an autofocus attribute.
