### ISSUE TITLE
Extract email addresses as Named Entities

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#213]
To make the search of emails in the main search bar more efficient, we can extract email addresses as Named Entities in a 'discreet' way:
- without writing 'Find name of people, locations, organizations and email addresses' in the button 
- without creating a new category in the 'Named Entities' tab 

Let's see if we create an 'email addresses' filtering facet.

**Comment by bamthomas** [comment]
I've looked around for email extraction and it seems like it would be better to do it by a [regular expression](https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression) or by a well established API like [java mail](https://javaee.github.io/javamail/) (cf [this thread](https://stackoverflow.com/questions/624581/what-is-the-best-java-email-address-validation-method)).

**Comment by annelhote** [comment]
As discussed with @Soliine and @pirhoo, we will let the Named Entities Emails be listed in the tab "Named Entities" of a document. No facet for now.
