### ISSUE TITLE
Document preview fails to show PDF document sometimes

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#216]
Sometimes OPTION request is not answered by the preview server.

And sometimes we have a json error in the preview :
![Screen Shot 2019-07-23 at 2 15 47 PM](https://user-images.githubusercontent.com/551723/61804161-b97c3180-ae33-11e9-88ce-b131973e1039.png)

In the meantime, the download of the docuemnt is ok.

cf document 30a4c4d0e7985d40a7e70ca378224648f0192623b459b73f3b150234182d91e4/7ddccc736d02cdf1c1db1fb94a90ad78d596ef757b6a9c6c040ac70e4ae869a5 on CH

**Comment by bamthomas** [comment]
Done on datashare preview : 

* added unit tests 
* ported build with setuptools
* added CI on circle CI
* ported web framework from flask to pyramid
* added logs on graylogs

I checked the doc 30a4c4d0e7985d40a7e70ca378224648f0192623b459b73f3b150234182d91e4/7ddccc736d02cdf1c1db1fb94a90ad78d596ef757b6a9c6c040ac70e4ae869a5 and I can see the previews

There are still issues for RTF files and email (message/rfc822).

**Comment by Soliine** [comment]
https://github.com/ICIJ/datashare-preview/issues/2
https://github.com/ICIJ/datashare-preview/issues/1
