### ISSUE TITLE
Stars or tags lost after restarting container

### ISSUE THREAD

**Issue by chriszs** [ICIJ/datashare#220]
I believe the list of starred documents is stored in an [in-memory sqlite database by default](https://github.com/ICIJ/datashare/blob/master/datashare-cli/src/main/java/org/icij/datashare/cli/DatashareCliOptions.java#L156). This appears to cause those to be lost after a restart. Here's what I did to test this:

1. I started a new Datasahare instance on my computer with the latest 4.3 version.
2. I indexed and starred a document.
3. I opened Kitematic (Docker UI on Mac), selected the datashare container and hit the restart button.
4. After a minute, I refreshed the Datashare interface.

I expected to see my document was still starred. Instead, the star was gone.

It appears this can be configured to use a Postgres database in a server context, but it seems like the default should be more persistent for those using the desktop app.

I checked to see if this was persisted to ElasticSearch, but it doesn't appear to be.

~I need to confirm this, but this may have caused us to lose significant work in reviewing documents on a project.~ Edit: The reporter kept separate notes.

**Comment by pirhoo** [comment]
You're right, the sqlite database should be mounted as a volume so we don't loose it when the container is recreated.

**Comment by bamthomas** [comment]
fixed in 4.21.0. Sorry for the delay.
