### ISSUE TITLE
List all keyboard shortcuts into a modal

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#227]
Just like in crowd.in

**Comment by annelhote** [comment]
cf. doc here : https://icij.gitbook.io/datashare/all/use-keyboard-shortcuts

**Comment by Soliine** [comment]
- Next document https://icij.gitbook.io/datashare/all/use-keyboard-shortcuts#go-to-the-next-previous-document
- Find in document https://icij.gitbook.io/datashare/all/use-keyboard-shortcuts#find-in-document
- Next tab https://icij.gitbook.io/datashare/all/use-keyboard-shortcuts#navigate-a-documents-tabs
- Back to results https://icij.gitbook.io/datashare/all/use-keyboard-shortcuts#go-back-to-search-results

**Comment by annelhote** [comment]
- previous : caret-left
- next: caret-right
- back: chevron-circle-left
- previous-tab: long-arrow-alt-left
- next-tab: long-arrow-alt-right
- search: search
- no-search : NONE
- previous-occurrence : angle-up
- next-occurrence : angle-down
