### ISSUE TITLE
Create a dashboard for each project

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#230]
Let's see how we could do that and where we should display this. 
The idea is to create a dashboard per project which shows the main metrics to the user:
- total number of documents in the project
- distribution by creation date over time
- distribution by file type
- number of sent emails by period of time (to be determined)
- number of unique email addresses
- tree map of folders by size

**Comment by annelhote** [comment]
Another need asked by Delphine today : The distribution of documents by creation date by year only for the emails of a specific project.
