### ISSUE TITLE
Batch search: other functionalities

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#231]
Let's see if and how we comply with KC:

- Do phrase matches: Allows you to search for documents containing an exact sentence or phrase rather than comparing a set of keywords in random order.

- Publish: Give other users access to the status and the results of this batch search. You can change this later if you want.

- Sloppiness: Enables proximity matching. Setting it to 2 matches terms within phrases in any order, equivalent to the following search: "John Wayne"~2. The higher the number the more noise you get. It's good to get results when your names may not contain middle names or all the last names, for example.

- Path 

- Filetype 

- Corporate registries

**Comment by annelhote** [comment]
Delete a batch search ?
