### ISSUE TITLE
Batch search: do phrase matches

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#236]
Currently, in KC, 'Do phrase matches' is described as 'Allows you to search for documents containing an exact sentence or phrase rather than comparing a set of keywords in random order'.

**Comment by bamthomas** [comment]
Be warn that fuzziness with phrase match do not make fuzziness for each word but it is making phrase slop : permutations, removals of words.

cf https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html
