### ISSUE TITLE
Batch search: fuzziness

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#238]
Currently in KC, you can set sloppiness. It 'Enables proximity matching. Setting it to 2 matches terms within phrases in any order, equivalent to the following search: "John Wayne"~2. The higher the number the more noise you get. It's good to get results when your names may not contain middle names or all the last names, for example.'

**Comment by annelhote** [comment]
Should be limited : min = 0 and max = 2.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness
