### ISSUE TITLE
Batch searches with operators

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#250]
Search operators currently do not apply in Batch Searches. How to reproduce:
<img width="314" alt="Screenshot 2019-09-26 at 18 53 27" src="https://user-images.githubusercontent.com/17233829/65708497-00361400-e08f-11e9-82fd-e7fbde67cd2c.png">
-> It searched for recognise OR and OR that

We would like search operators to apply even in Batch Searches.

**Comment by Soliine** [comment]
If 'phrase matches' is not ticked, parse the queries and do not apply tilde (~) after any operators (AND, OR, NOT)

**Comment by bamthomas** [comment]
After having dug into it, string queries have a default fuzziness set to AUTO.

If we would really want to add fuzziness, it would change the query string query to a span multi query. 
ex : https://stackoverflow.com/questions/24334188/elasticsearch-query-string-not-performing-fuzzy-query-as-expected-when-using-phr

And that span multi would not take the boolean operators. 

So I think that the best is to detect if there are boolean operators in the query, and if so, fuzziness and phrase match are ignored. And we document that.

What do you think ?

**Comment by bamthomas** [comment]
as in the [previous commit](https://github.com/ICIJ/datashare/commit/400a11d73c57c6afadfbe92247edf2c9e175a9db) we are parsing each request so we could detect a parse error and avoid sending the request to ES thus preventing the batch to stop
