### ISSUE TITLE
Batch Search: weird characters appear in the batch search

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#251]
I cannot share either .csv nor .numbers here. But here is a screenshot of my batch search:
<img width="337" alt="Screenshot 2019-09-26 at 19 08 15" src="https://user-images.githubusercontent.com/17233829/65709493-3eccce00-e091-11e9-9056-59673b28fbb9.png">

And here is the results I got on the front:
<img width="668" alt="Screenshot 2019-09-26 at 19 05 26" src="https://user-images.githubusercontent.com/17233829/65709471-32e10c00-e091-11e9-8c82-5025019e3f9a.png">

Same in the CSV with results:
<img width="285" alt="Screenshot 2019-09-26 at 19 10 30" src="https://user-images.githubusercontent.com/17233829/65709548-54da8e80-e091-11e9-9d6a-00be8463d0d8.png">

**Comment by annelhote** [comment]
This may happen because your csv is semi column separated instead of comma
