### ISSUE TITLE
bad index for Named Entity highlight 

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#254]
In ML the highlights (indexes) for Named Entities are wrong. For example in document 

`_id:fa13cb4ef3750418f156255a0c6ea89fe851b79d02da0e40e1d8198ad4963c38195067d53879180f05453c711b389efa`

**Comment by annelhote** [comment]
Nothing to do with reindex. But the order of the Named Entities was totally messed up for the highlight. So everything was mixed. -_-'
