### ISSUE TITLE
Fuzziness is displayed as applied filter

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#262]
Search for "term~2" will display "term" and "2" as applied filters. "2" should be one!

**Comment by annelhote** [comment]
In ES, the term fuzziness is an integer in [0, 1, 2] : https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl-query-string-query.html#_fuzziness. Eg. `term~1`. In contrary to Lucene where the value is between 0 and 1, with a value closer to 1 only terms with a higher similarity will be matched. : http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Fuzzy%20Searches. Eg. `term~0.8`.

**Comment by annelhote** [comment]
@pirhoo any idea how to fix that ? Can't do a PR on our lucene query parser lib, because it seems to be a difference between Lucene and DSL ... Should I publish my own lib only for this tiny fix ? Or will it be a won't fix ?

**Comment by pirhoo** [comment]
Thanks for the explanation! Why would it be an issue for us?

**Comment by annelhote** [comment]
If I look for "Trump~2", I'll get those applied filters : 
![Datashare](https://user-images.githubusercontent.com/1478919/66495957-691f8200-eaba-11e9-9aae-2676983a8e63.png)

**Comment by annelhote** [comment]
This issue won't be fixed for now.
