### ISSUE TITLE
Change of TCP/IP Port

### ISSUE THREAD

**Issue by StoltHD** [ICIJ/datashare#265]
How do we actually change the port to connect to so that it works?

I can't use 8080, have other software running on that port... and to just change it in the YML file befor install doesn't work

datashare 4.16 and docker for windows desktop 2.1.0.3

It would be nice if you could have some kind of parameter settings in the installer, for possible to set the port at install on Windows, 
same with the data store folders, there are people that do not share C with docker and if they don't, your script fail... 

Third thing, lots of people use paid internet connecctions, and if your script fail and need to be rerun, everything needs to be downloaded again, taking lots of "data" something like 2GB  of download in total...

It would be nice if you stated how large the packages was

**Comment by bamthomas** [comment]
Well you can if you edit the launcher script that should be located in the datashare folder in program files. You can edit the `docker-compose.yml` file :

```
    ports:
      - "127.0.0.1:8080:8080"
``` 
and replace `127.0.0.1:8080` by `127.0.0.1:your_port_number` 

* for the installer options, yes that could be done I'm adding the issue to the backlog. No idea when it will be done as it has not been asked by a lot of people so far

* for the size, yes we could display the total amount of data to be downloaded

**Comment by StoltHD** [comment]
Thanks... but the edit in the .YML file alone didn't work...  Neither with just 127.0.0.1:[port], nor 
127.0.0.1:[port]:[port].

I tried that, thats why im asking because I thought it should be enough...

I will do a clean reinstall of Docker Desktop and reinstall the package on a test workstation with the same config,  to see if it might have been because of the earlier errors with the C-Drive not being shared with Docker shared..

**Comment by bamthomas** [comment]
I think you have to remove the docker container that is called datashare that should be possible from the Docker Desktop or you can do it with the Command Line 

```
docker rm -f datashare
```
You'll have to update also the datashare.bat script to update the port accordingly.

Then launch again datashare with the runner.

**Comment by bamthomas** [comment]
note that as mentioned in #310 we won't update the port in local mode with docker.

**Comment by Soliine** [comment]
You can now change Datashare's settings here : http://localhost:8080/#/settings
