### ISSUE TITLE
Create a "Stop pending tasks" button

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#27]
Tasks can be started for too many documents or by error. User might want to delete pending tasks.

Create a "Stop all pending tasks" button and an individual "Stop task" button on each line dedicated to a task on http://localhost:8080/#/indexing:
![stop pending tasks](https://user-images.githubusercontent.com/17233829/51126807-59715680-1824-11e9-8ef7-ed8815b59875.png)

(Issue initially raised by Emilia on January 11, 2019: [https://jira.icij.org/browse/NNA-29](https://jira.icij.org/browse/NNA-29))

**Comment by annelhote** [comment]
@Soliine could we close this issue ?
