### ISSUE TITLE
Batch search: I should not be able to delete others' batch searches

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#272]
I should be able to delete only the batch searches that I created.

**Comment by annelhote** [comment]
The batchSearches list should first return the batchSearch author.

**Comment by bamthomas** [comment]
I've updated the delete query. Now it cannot delete the batch search if the user doesn't match the user_id stored into the database. 

So the request is sending back a 404 (not found), the record is still there in the list.
