### ISSUE TITLE
ICIJ Datashare Install Issue - Help Appreciated ! 

### ISSUE THREAD

**Issue by victor-von-doom** [ICIJ/datashare#276]
Hello everyone,

I was hoping you can help me out with my install of Datashare.

My OS: Windows 10 Pro
16MB RAM on an Intel i7 ThinkPad.

Did the install of Datashare (4.16.1) and got the following error message when I tried to open Datashare terminal after Docker Destop started running.... since it was a Beta, I tried the same with earlier versions of Datashare, (going all the way back to 4.6)  and the same issue.

I have no idea what I need to do to fix this, hoping some of the more experienced folks here could lend me hand.

Thanks in advance!

This is what I get on the Datashare terminal when I load it:
_____________________________________________________________________________________________
**The system cannot find the file \Program Files\Docker\Docker\Docker for Windows.exe.
waiting for docker to be up............................................................waiting for datashare to be up............................................................KO
Traceback (most recent call last):
File "docker-compose", line 6, in
File "compose\cli\main.py", line 71, in main
File "compose\cli\main.py", line 124, in perform_command
File "compose\cli\command.py", line 39, in project_from_options
File "compose\cli\docker_client.py", line 84, in tls_config_from_options
File "site-packages\docker\tls.py", line 81, in init
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
[4584] Failed to execute script docker-compose
Traceback (most recent call last):
File "docker-compose", line 6, in
File "compose\cli\main.py", line 71, in main
File "compose\cli\main.py", line 124, in perform_command
File "compose\cli\command.py", line 39, in project_from_options
File "compose\cli\docker_client.py", line 84, in tls_config_from_options
File "site-packages\docker\tls.py", line 81, in init
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
[9552] Failed to execute script docker-compose
waiting for datashare to be up.......................**

**Comment by Soliine** [comment]
Hello Victor, thanks a lot for reporting this! We will provide you with an answer as soon as possible.

**Comment by bamthomas** [comment]
It seems that :
* the script can't see docker running
* then it tries to launch it and it fails to find the executable file
 
Did the install process ended up normally ?

**Comment by victor-von-doom** [comment]
As far as I can tell, it did.   Docker seems to run fine outside of that script I posted.

**Comment by Soliine** [comment]
(email sent offering a call)

**Comment by Soliine** [comment]
Hi @victor-von-doom, we just released a standalone version of Datashare for Windows without Docker. Can you try installing this one and tell us how it went? https://icij.gitbook.io/datashare/windows/install-datashare-on-windows#standalone-windows-7-service-pack-2-or-newer-version
Thanks,
SL

**Comment by Soliine** [comment]
As we have had no news on this since  25 days, I am closing this issue.
