### ISSUE TITLE
Improve batch searches

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#278]
**For local mode:**

Name*
_(No description)_

CSV file*
_Only CSV format accepted. The first column should contain the terms to search._

Description
_(No description)_

Do phrase matches
_Allows you to search for documents containing an exact sentence or phrase rather than comparing a set of keywords in random order._

Fuzziness
-- If ‘do phrase matches’ is ticked: 
_Maximum number of operations (insertions, deletions, substitutions and transpositions) on terms needed to make one phrase match the other. [Learn more](https://icij.gitbook.io/datashare/faq/what-is-fuzziness)._

-- If ‘do phrase matches’ is not ticked:
_Maximum number of operations (insertions, deletions, substitutions and transpositions) on characters needed to make one term match the other. [Learn more](https://icij.gitbook.io/datashare/faq/what-is-fuzziness)_

File types **(no uppercase in "types")**
_(No description)_

Path
_(No description)_

**For server mode:**

Name*
_(No description)_

CSV file*
_Only CSV format accepted. The first column should contain the terms to search._

Description
_(No description)_

Project*
_(No description)_

Do phrase matches
_Allows you to search for documents containing an exact sentence or phrase rather than comparing a set of keywords in random order._

Fuzziness
-- If ‘do phrase matches’ is ticked: 
_Maximum number of operations (insertions, deletions, substitutions and transpositions) on terms needed to make one phrase match the other. [Learn more](https://icij.gitbook.io/datashare/faq/what-is-fuzziness)_

-- If ‘do phrase matches’ is not ticked:
_Maximum number of operations (insertions, deletions, substitutions and transpositions) on characters needed to make one term match the other. [Learn more](https://icij.gitbook.io/datashare/faq/what-is-fuzziness)_

File types **(no uppercase in "types")**
_(No description)_

Path
_(No description)_

Published 
_Give other members of the project access to this batch search. You can change this later._

**Comment by annelhote** [comment]
ToDo :
- [ ] Add link into fuzziness description
- [ ] Remove "local-search" as default index
