### ISSUE TITLE
.rtf text extractor not working

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#28]
On macOS High Sierra version 10.13.6, indexing .rtf documents does not work. See attached:[Command line logs .RTF Text Extractor Not Working.txt](https://github.com/ICIJ/datashare/files/2750274/Command.line.logs.RTF.Text.Extractor.Not.Working.txt)

**Comment by bamthomas** [comment]
should be fixed with version 1.6

**Comment by Soliine** [comment]
It works in 1.7. Thanks!
<img width="1373" alt="screen shot 2019-01-16 at 6 03 28 pm" src="https://user-images.githubusercontent.com/17233829/51265491-2f04d200-19b9-11e9-9225-05ca164f448c.png">
