### ISSUE TITLE
"Term1 AND Term2": if I delete Term1, search query is wrong

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#280]
The query becomes "AND Term2" and then it is wrong. Do we want to correct this bug?

**Comment by annelhote** [comment]
Oops, can't reproduce it in prod. @Soliine can you ? If not, let's close this issue...

**Comment by Soliine** [comment]
I can't reproduce it now... I tested with different terms in different projects with operators AND and NOT, in the server and in local DS. Should we close the issue?
