### ISSUE TITLE
Path suggestions are based on the last search (search store state) instead of the project chosen in the form

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#288]
Same for fileType.

**Comment by Soliine** [comment]
In the batch search form, we cannot see the entire path in the dropdown as we see only the beginning of the path which is the same for a lot of path so we cannot distinguish between them. 

One potential solution is to display the whole path when one hovers a path.

Another solution is to create a horizontal scroll bar... ?

**Comment by Soliine** [comment]
We would like to see the whole path on hover. 
On project change, hide path suggestions.
Thanks!

**Comment by annelhote** [comment]
- [ ] Bug in stagging on path suggestions
- [ ] Should empty the input after changing project
- [ ] Should hide fileTypes suggestions while showing path suggestions
- [ ] FileTypes suggestions no correct in prod

**Comment by annelhote** [comment]
- [ ] Hide suggestions on click outside
