### ISSUE TITLE
Batchsearch results after filtering: pages 2 and more are displayed even though they are empty

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#291]
When there are 100 or less results, we should not display the per page navigation bar.
<img width="702" alt="Screenshot 2019-10-31 at 13 40 04" src="https://user-images.githubusercontent.com/17233829/67948272-affa2680-fbe5-11e9-82cc-cddac8bcc44d.png">
To reproduce : it happens after filtering queries only.

**Comment by annelhote** [comment]
Can't reproduce this bug.

**Comment by Soliine** [comment]
It happens only after filtering by query(ies).
