### ISSUE TITLE
Error message when a batch search fails

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#295]
When a query is failing in the batch search, the other queries are not executed, and the error message is stored.

Then the Batch Search has a FAILURE status and an errorMessage field containing the error.

The front end displays an error notice with the error details, but let the user access the results of executed queries.

**Comment by Soliine** [comment]
Error message:
'The system encountered a problem. It can be a syntax error that you made in your CSV or another error. Please refer to this Help page where most common errors are described.'
I am waiting for the system to show error messages to copy them and create a FAQ. I will then share the link here.
