### ISSUE TITLE
"NlpConsumer - error in consumer main loop / couldn't create parent directories"

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#30]
I used macOS High Sierra 10.13.6.
With 4 basic pdf samples, extract text went fine but **finding names did not complete**.

- At http://localhost:8080/#/indexing, tasks were "100%" but still "running".
<img width="1270" alt="screen shot 2019-01-14 at 8 38 34 am" src="https://user-images.githubusercontent.com/17233829/51101184-e2af6b80-17d9-11e9-9ea4-ba97b5e3955f.png">

- Here are the logs from Terminal, signaling "NlpConsumer - error in consumer main loop" and "couldn't create parent directories":
[Bug Datashare Jan 14.pdf](https://github.com/ICIJ/datashare/files/2754339/Bug.Datashare.Jan.14.pdf)

**Comment by bamthomas** [comment]
It was for mac, there were rights problems on Datashare_Models
fixed by the 1.13 (after having tested with Soline)
