### ISSUE TITLE
Table view: 'sort by' doesn't work

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#302]
To reproduce:
- go in table view
- click on 'sort by'
- select any item
-> the selected item appears in the URL but not in the actual sorting.

**Comment by annelhote** [comment]
Changing the 'sort by' rules in the settings should send an event. While on the 'table view', this event should be catched and apply the new sort rule.

**Comment by Soliine** [comment]
"Sort by creation date (newest)" doesn't work on table view.

**Comment by annelhote** [comment]
"Sort by creation date", newest and oldest, works on table view on staging.
Might be confused by another bug : #319
