### ISSUE TITLE
After a new release, blank screen

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#303]
To reproduce :
- Make a new release
- Open datashare in prod
=> You will see a total blank screen

Quick fix :
- Refresh your page without the cache (ctrl + shift + R)

The new release with the index.html page should force the reload of the chunk.

**Comment by annelhote** [comment]
https://webpack.js.org/configuration/optimization/

**Comment by Soliine** [comment]
Anne says she needs @pirhoo on this.

**Comment by Soliine** [comment]
According to Anne and Pierre, the back should manage that @bamthomas: invalidate html index in a cache at each release for each client.

**Comment by pirhoo** [comment]
I think it's been a while since we didn't have this, did we? The only change we made is using parameter chunk versioning (`app.js?ver=af975d3`) instead of file versioning  (`app-af975d3.js`).
