### ISSUE TITLE
Offer Regex

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#305]
Let's allow to use regex between 2 slashes in the main search bar, as Bruno did in batch searches (https://github.com/ICIJ/datashare/issues/315)
Example: mobile /[0-9]{10}/
It will allow to combine standard queries with Regex in the same query.
Example: "Ada Lovelace" AND mobile /[0-9]{10}/

So we won't do our previous plan anymore as it is not needed, it was: "In the field dropdown, add 'All fields with regular expressions' or 'All fields with Regex' if shorter is best for display."

**Comment by Soliine** [comment]
Regex works between 2 slashes. 
- "Note we do not accept anymore the slash / because in the lucene grammar it is used for regular expression." https://github.com/ICIJ/datashare/issues/315
- I changed the User Guide's page 'Search with operators' into 'Search with operators and Regex'. The URL has not changed and remains https://icij.gitbook.io/datashare/all/search-with-operators.

**Comment by annelhote** [comment]
Linked issue #313

**Comment by annelhote** [comment]
- [ ] Stop escaping backslash in front
- [ ] Restore the Path facet
- [ ] Escape backslash if path is selected as field in the main search bar
- [ ] Escape backslash after "path:" in the main search bar
