### ISSUE TITLE
Document page: add tags near the title

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#306]
Lets put the title slightly higher when there is / are tag(s) and display the tags below:

![More visible tags](https://user-images.githubusercontent.com/17233829/68493907-aad45180-024d-11ea-8909-6d36372dbdbe.png)

We will see later if we add a 'Add a new tag' button next to them and if we remove the tags in the 'Tags & Details' tab.

**Comment by annelhote** [comment]
On tag delete under the title, it is not deleted.
