### ISSUE TITLE
Batch search is failing

### ISSUE THREAD

**Issue by cosicje** [ICIJ/datashare#308]
This is a message that I get when I run it:

SearchException: query='"First Group plc' message='org.icij.datashare.batch.SearchException: org.elasticsearch.client.ResponseException: method [POST], host [https://vpc-elasticsearch-1-oblri6n6c3vphmzgcq7iwsqtyi.us-east-1.es.amazonaws.com], URI [/cassandra/doc/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&scroll=60000ms&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 400 Bad Request] {"error":{"root_cause":[{"type":"token_mgr_error","reason":"token_mgr_error: Lexical error at line 1, column 17. Encountered: <EOF> after : \"\\\"First Group plc\""}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"cassandra","node":"niI0YMZJRNWJ27iIX4xirA","reason":{"type":"query_shard_exception","reason":"Failed to parse query [\"First Group plc]","index_uuid":"WLNt1LXUQ82tZqf3jWupSg","index":"cassandra","caused_by":{"type":"parse_exception","reason":"parse_exception: Cannot parse '\"First Group plc': Lexical error at line 1, column 17. Encountered: <EOF> after : \"\\\"First Group plc\"","caused_by":{"type":"token_mgr_error","reason":"token_mgr_error: Lexical error at line 1, column 17. Encountered: <EOF> after : \"\\\"First Group plc\""}}}}],"caused_by":{"type":"token_mgr_error","reason":"token_mgr_error: Lexical error at line 1, column 17. Encountered: <EOF> after : \"\\\"First Group plc\""}},"status":400}'

**Comment by Soliine** [comment]
It is because the query starts with a double quotes and it is not closed after: "First Group plc 
https://icij.gitbook.io/datashare/all/batch-search-documents#querie-s-contain-s-only-one-double-quote-or-a-double-quote-in-a-word
