### ISSUE TITLE
Update configuration file from GUI

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#310]
Most of the time, users don't know how to use command line interface. In Windows and Mac environments all configurations are made using graphical interfaces. 

As a user I would like to update configuration file (for example tcp listen port), without having to edit a file and launch datashare from command line.

**Comment by bamthomas** [comment]
that means : 

[] provide a configuration file with the CLI
[] add a write configuration endpoint in the backend
[] create a screen in the front to edit configuration file

**Comment by annelhote** [comment]
New url is `#/config`.

**Comment by annelhote** [comment]
Hide this url in server mode

**Comment by annelhote** [comment]
Do not call /api/config/user anymore. The load of the user's projects should be in ... (somewhere else). Then delete this endpoint from the back.

**Comment by annelhote** [comment]
- [ ] make the API return JSON object from "/api/users/me" url instead of string
- [ ] rename the projects "datashare_projects" instead of "datashare_indices"
- [ ] even for local user, return the projects list as ["local-datashare"]
- [ ] regenerate API doc
- [ ] updates installers to read configuration for docker-compose (for TCP listen)

**Comment by bamthomas** [comment]
Two more points about this story : 

- [ ] we have to disable the config update for server mode 
- [ ] we have to add a check on the server to avoid config to be changed (403 for ex.)

**Comment by annelhote** [comment]
In server mode, we display an alert message instead of the form. The API endpoint should be protected too.

**Comment by pirhoo** [comment]
I noticed the configuration form will submit all value (even the unchanged) which will add them all to the configuration file. The side effect is that it will override the command line options for all options.

**Comment by bamthomas** [comment]
Note that we won't implement the port change for local datashare with docker.

**Comment by Soliine** [comment]
Add a text : "Don't change these settings if you don't know what you're doing".

**Comment by pirhoo** [comment]
Done for the message :)
