### ISSUE TITLE
Queries order in batchSearch

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#312]
When I submit a new batchSearch in datashare, my queries are submitted in the correct order :

![queries_order](https://user-images.githubusercontent.com/1478919/69068476-1fb14380-0a25-11ea-8903-37c717887362.png)

But then in database, the order is not correct :

![queries_order_db](https://user-images.githubusercontent.com/1478919/69068531-39528b00-0a25-11ea-9951-956e7e6c7a57.png)

**Comment by Soliine** [comment]
@bamthomas we have a weird case (see 'Mario test'): there are a lot of request which has zero results before the first error reported in the 'failure' session (the one with a slash). When we look for some queries in Datashare (for example "GEORGIOU"), we have results in Datashare.
