### ISSUE TITLE
Batch Search failure: see if we can change the limit in results' size

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#314]
There was a failure in Batch search with this error message:
"SearchException: query='XXXX' message='org.icij.datashare.batch.SearchException: java.io.IOException: entity content is too long [155046167] for the configured buffer limit [104857600]'"

**Comment by mvanzalu** [comment]
Can't reproduce the error for now

**Comment by bamthomas** [comment]
either we change the max entity content size (not possible with AWS)
either we can tweak the search parameters scroll size...

**Comment by Soliine** [comment]
We haven't encountered this issue since we improved performance https://github.com/ICIJ/datashare/issues/665
