### ISSUE TITLE
Batch search: when opening a query finding, automatically search for the query

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#321]
- I run a batch search, I open the result
- I click on a document of the results which contains a query
- the document opens in a new tab
--> it would be great to have the query already searched in the document so the user only has to click on it to find the occurrence(s) in the document (at the moment, they have to type the query)

**Comment by annelhote** [comment]
Tooltip : "Execute this search".

**Comment by annelhote** [comment]
Find a way to apply the "Do phrase matches" and "Fuzzyness". Either a new Endpoint or a front query building.

**Comment by mvanzalu** [comment]
Focus on the query isn't working properly
