### ISSUE TITLE
A document could have a note according to its path

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#322]
As a user, I should be able to see one or several notes for a document, which is displayed according to its path.

This note is provided by an API endpoint which lists notes with 3 properties: the path, the note and the variant (`dark`, `light`, `danger`, `info`, `success`, `danger`, `warning`, `primary` or `secondary`). The default variant is `warning`.

For instance:

path | note | variant
--- | --- | ---
/store/bills | This document is  a bill collected by ICIJ | `info`
/store/secrets | This document is secret, don't share it! | `danger`

**Comment by annelhote** [comment]
<img width="1288" alt="Screenshot 2019-12-19 at 11 14 19" src="https://user-images.githubusercontent.com/1478919/71250724-aa38db80-2320-11ea-9fe6-3e7336a689c7.png">

**Comment by bamthomas** [comment]
I guess that a random user should not be able to retrieve all notes of all projects, should she ?

If so we could do an end point like : `/api/:project/note/:path:`
`:project` means one string without slashes (non greedy)
`:path:`means that the end of url  is greedy (all slashes are taken as path value)

Example : 
```
GET /api/myproject/note/store/bills 
[{"note": "This document is a bill collected by ICIJ", "variant": "info", "path": "/store/bills"}]
GET /api/myproject/note/store
[
  {"note": "This document is a bill collected by ICIJ", "variant": "info", "path": "/store/bills"}, 
  {"note": "This document is secret, don't share it!", "variant": "danger", "path": "/store/secrets"}
]
```
if the user has access to `myproject`.

If she doesn't then it gets a `403 Forbidden`
If she is not authenticated she gets a `401 Unauthorized`

Later on, if needed we could implement `PUT` to create a note and `DELETE` to delete a note 
What do you think ?

**Comment by annelhote** [comment]
Improvement:
Load notes at once for each project, and for each document opened, check if there is a matching note.
