### ISSUE TITLE
Batch search: add a 'sort by' for queries

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#328]
In the contextual column which allows to select some queries:
- add a 'Sort by' near 'Filter by queries", allow to sort by "original order" and "results (most to least)
- when 2 or more queries have the same number of results, sort by original or alphabetical order?
- maybe change "Filter by queries" into "Queries" so it is shorter ?

**Comment by annelhote** [comment]
- [ ] Add a 'Sort by' near 'Filter by queries", allow to sort by "original order" and "results (most to least)
- [ ] When 2 or more queries have the same number of results, sort by original or alphabetical order?
- [ ] Change "Filter by queries" into "Queries" so it is shorter ?
