### ISSUE TITLE
Difference of results between batch search and front

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#332]
See public batch search published on December 3, 2019 3:48 PM entitled "Batch search with operators (TRAINING)".

I did the regex query `/.*\..*\@.*\..*/` which had 15 results in the batch search and 16 in the front.

Can we see why? thanks!

**Comment by bamthomas** [comment]
for the record, another issue linked to this with Delphine : 
Java api is adding : 
```
            "default_field": "*",
            "fields": [],
            "type": "best_fields",
            "default_operator": "or",
            "max_determinized_states": 10000,
            "enable_position_increments": true,
            "fuzziness": "AUTO",
            "fuzzy_prefix_length": 0,
            "fuzzy_max_expansions": 50,
            "phrase_slop": 0,
            "escape": false,
            "auto_generate_synonyms_phrase_query": true,
            "fuzzy_transpositions": true,
            "boost": 1.0
            ```
  
in the search queries. When we remove this options, we have the same results as the front

**Comment by bamthomas** [comment]
see 3a51a30545fd9f6db60415f3d9ee94a82813293e
