### ISSUE TITLE
Local version: the author of a tag should be "you"

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#344]
At the moment, it is "object Promise":
<img width="239" alt="Screenshot 2019-12-17 at 10 17 20" src="https://user-images.githubusercontent.com/17233829/72072584-91ec2900-32ee-11ea-953b-b5acb462d5c5.png">

**Comment by annelhote** [comment]
Only if the tag has just been created. It is fixed after a refresh of the page.

**Comment by annelhote** [comment]
Not only in local version

**Comment by annelhote** [comment]
The default is "local", should it be changed ?

**Comment by annelhote** [comment]
Same for the "ReadBy" filter.

**Comment by annelhote** [comment]
Same for "ActiveFilters".
