### ISSUE TITLE
The titles (and possibly metadata) are not searched

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#345]
How to reproduce:
- index a document with a title not present in the Extracted Text
- search for this title
-> the document is not found
We would like the search to apply to all the metadata.

**Comment by annelhote** [comment]
Incorrect. All the metadata are including in the search, title included even if the dedicated field is the path. But the analyzer works like the content one. The separator is the space. So if the title of the field has no space, the only word indexed is the full title. So only a search on the full title will return this document. But maybe I have misunderstood the bug ?

**Comment by Soliine** [comment]
Here is the file on which it doesn't work with the search "monde". <img width="699" alt="Article Le Monde" src="https://user-images.githubusercontent.com/17233829/73181319-496aa300-4117-11ea-8e44-65c787e60870.png">

**Comment by annelhote** [comment]
@Soliine would you please send it to me as attached file. The file name is important. Thanks.

**Comment by annelhote** [comment]
Save file as : "Article Le Monde.png"

**Comment by annelhote** [comment]
Our mapping says that metadata is an object. Which means that its properties are indexed with the default aka standard analyzer : " The standard tokenizer divides text into terms on word boundaries, as defined by the Unicode Text Segmentation algorithm. It removes most punctuation symbols. It is the best choice for most languages.".
