### ISSUE TITLE
The scroll bar in table and grid view prevents to go to next page easily

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#346]
<img width="430" alt="Screenshot 2020-01-09 at 16 21 03" src="https://user-images.githubusercontent.com/17233829/72080459-21003d80-32fd-11ea-99fe-3a2977a26f43.png">

**Comment by Soliine** [comment]
The grid is still problematic. The others work well.

**Comment by pirhoo** [comment]
I think the problem is now specific to Mac OS who uses custom scrollbars.

**Comment by Soliine** [comment]
OK too bad.. Can we do something or nothing for Mac users?

**Comment by pirhoo** [comment]
I'll try something yes :)

**Comment by Soliine** [comment]
Ok great! Let me know if you want me to test.

**Comment by annelhote** [comment]
@pirhoo would vue-perfect-scrollbar be a solution ?

**Comment by annelhote** [comment]
It was not, we added a margin-right instead.
