### ISSUE TITLE
I just added a tag, let's have the focus on 'Add a new tag' again

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#352]
How to reproduce:
- on a document, add a new tag, press Enter
-> the focus is lost. 
It would be great to have the focus back on 'Add a new tag' to make it easy to add multiple tags in a row.

**Comment by annelhote** [comment]
Works in local.

**Comment by annelhote** [comment]
Works in prod.

**Comment by annelhote** [comment]
Error in staging because of a 403 on ES.

**Comment by Soliine** [comment]
Seems not to work on Chrome.
