### ISSUE TITLE
A blank space is at the bottom of the filter column

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#353]
How to reproduce:
- unfold enough filters so that the scroll bar appears
- close some filters
-> a blank space appears at the bottom of "indexing dates"

**Comment by pirhoo** [comment]
I couldn't reproduce this bug, either on Firefox or Chrome. I suspect a bug from (vue-perfect-scrollbar)[https://github.com/lecion/vue-perfect-scrollbar] so we probably won't be able to fix it.

**Comment by Soliine** [comment]
Could not reproduce on Pierre's machine.
