### ISSUE TITLE
After clicking 'Exclude' and 'All', "All" becomes strikethrough 

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#355]
How to reproduce (tested on Chrome and Firefox):
- in File types or Languages filters for instance, click an item
- click 'Exclude'
- click 'All'
-> the All button becomes strikethrough
The documents in results are good though.

<img width="321" alt="Screenshot 2020-01-10 at 15 03 39" src="https://user-images.githubusercontent.com/17233829/72158546-c62d1b80-33ba-11ea-98e6-f68e4078146c.png">
<img width="322" alt="Screenshot 2020-01-10 at 15 04 15" src="https://user-images.githubusercontent.com/17233829/72158547-c6c5b200-33ba-11ea-809d-56847c36e91b.png">

**Comment by annelhote** [comment]
Reproduced

**Comment by annelhote** [comment]
I supposed that on click on "All" the "excluded" property should be reset.
