### ISSUE TITLE
[mac] Installer without docker

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#359]
It would be convenient for small hardware machines to be able to install datashare without docker.

**Comment by bamthomas** [comment]
see #317

**Comment by Soliine** [comment]
Can you add 'To open Datashare, go to http://localhost:8080/ in your browser' at the end of this ?
<img width="680" alt="Screenshot 2020-04-03 at 18 04 41" src="https://user-images.githubusercontent.com/17233829/78381416-9f573d80-75d5-11ea-8df4-f5a57d960e55.png">
