### ISSUE TITLE
Elasticsearch host not found / elasticsearch not launching?

### ISSUE THREAD

**Issue by stucka** [ICIJ/datashare#366]
I'm having a problem with a new install of 5.0.1 within Virtualbox under Ubuntu 18.04.

I get a bunch of errors:
IndexWaiterFilter - Ping failed. Waiting for Elasticsearch to be up java.IOException: elasticsearch

Some are intermingled with supplemental text -- ... java.IOException: elasticsearch: Name does not resolve

Earlier reporting points to elasticsearchAddress=http://elasticsearch:9200

I get no response from that address in a browser, nor from localhost:9200.

**Comment by bamthomas** [comment]
several questions :

* when you say "new install" do you mean it was working before, and latest version broke something ?
* are you able to run docker in the virtual box ? (cf https://stackoverflow.com/questions/44337460/docker-inside-virtualbox)
* how do you install it ?

Thanks for your answers

**Comment by severo** [comment]
Same problem launching datashare.sh on Ubuntu 20.04.

Versions:
```
Docker version 18.09.5, build e8ff056
docker-compose version 1.23.2, build 1110ad01
```

My user is part of the `docker` group.

**Comment by bamthomas** [comment]
@severo I don't know if there is a precise reason for that but could you use the standalone version of datashare, installing it with : 

```
sudo apt install /path/to/datashare.deb
```
see https://icij.gitbook.io/datashare/linux/install-datashare-on-linux
