### ISSUE TITLE
Batch search: select a query doesn't work

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#368]
To reproduce:
- in a batch search result, select one query
- see the results
All the queries are displayed while there should be only one.

**Comment by annelhote** [comment]
To still fix : on reload a page with selected queries, select them by default.

**Comment by annelhote** [comment]
See : https://router.vuejs.org/guide/advanced/data-fetching.html

**Comment by annelhote** [comment]
https://forum.vuejs.org/t/beforerouteenter-beforerouteupdate/21661

**Comment by annelhote** [comment]
This is a bug from https://github.com/ICIJ/murmur. See PR [here](https://github.com/ICIJ/murmur/pull/5).

**Comment by annelhote** [comment]
It seems that if _queries_order_ is selected and some _queries_ are selected, a hard refresh never stop loading data.

**Comment by annelhote** [comment]
Error "NavigationDuplicated"

**Comment by Soliine** [comment]
We need @pirhoo on this.

**Comment by annelhote** [comment]
To reproduce:
1. Open this [link](https://datashare-demo.icij.org/#/batch-search/luxleaks/4b6796f5-89fb-40e8-8484-596951703ec5?page=1&sort=doc_nb&order=asc)
2. Select the query "président"
3. Hard refresh this page
=> No results are displayed anymore
