### ISSUE TITLE
[Performance] Optimize the loading of Batch Searches's page

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#379]
How to reproduce:
- click on "Batch Searches" in the menu
-> the page takes a few seconds to load. It would be great to see if we can load it quicker.

**Comment by annelhote** [comment]
This page should be paginated

**Comment by Soliine** [comment]
Don't load all the queries.

**Comment by annelhote** [comment]
First point would be to change the endpoint [here](https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API#get__api_batch_search) to not return the full list of queries of each batchSearch but instead the number of queries for each batchSearch.
