### ISSUE TITLE
Creation date selector: label is not good

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#380]
How to reproduce:
- select one day
- press 'Enter'
- refresh
-> the label is an ID instead of the date
<img width="251" alt="Screenshot 2020-02-06 at 15 09 00" src="https://user-images.githubusercontent.com/17233829/73944308-a7a33d00-48f2-11ea-880b-bd03b7369e66.png">

**Comment by annelhote** [comment]
It should not work ...

**Comment by annelhote** [comment]
How could I reproduce this bug ?

**Comment by Soliine** [comment]
I can't reproduce now either... Strange! I close the issue

**Comment by Soliine** [comment]
Now I find something related to this bug again. 
On a Mac using Chrome, I select "07/02/2004 - 07/02/2005" in the creation date filter. It finds two documents: https://datashare-demo.icij.org/#/?q=&from=0&size=25&sort=creationDateOldest&index=luxleaks&field=all&f%5BcreationDate%5D=1088719200000&f%5BcreationDate%5D=1120255200000
But then if I refresh this same URL once, it shows these labels:
<img width="655" alt="Screenshot 2020-02-17 at 16 46 30" src="https://user-images.githubusercontent.com/17233829/74668261-2460d180-51a5-11ea-81be-c55a686fe16e.png">

**Comment by annelhote** [comment]
It seems that the url query params are not cast as int but as string !

**Comment by annelhote** [comment]
Same for indexing date
