### ISSUE TITLE
Creation date selector: 'no documents found' until refresh

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#381]
How to reproduce:
- select one day in Creation date
- press 'Enter'
-> it says 'no document founds'
- refresh the page
-> it finds some documents
We would like: not to have to press 'Enter' in the first place

**Comment by annelhote** [comment]
Can't reproduce anything on my computer. Neither on Firefox nor on Chrome. Maybe I would need a file and the specific date ? Thanks.

**Comment by Soliine** [comment]
The bug seems to have changed a little bit. There are two things.
On my Mac using Chrome, I see that [this document](https://datashare-demo.icij.org/#/d/luxleaks/a0d563f8f571776af5305b4fa4704d4f1185a6d68934ab2bd0ea5328d331a3d5fca514869bc610d79cea63e4196beab4/a0d563f8f571776af5305b4fa4704d4f1185a6d68934ab2bd0ea5328d331a3d5fca514869bc610d79cea63e4196beab4?q=)'s creation date is 2004-07-02. 
1. If I select July, 2nd 2004 in the creation date filter, it rightfully writes "07/02/2004 - 07/02/2004" in the filter but it doesn't search for the documents. We would like it to search after I clicked for the second time on the same date, not after refresh.
2. If I refresh the page, I then have a "no documents found" whereas there is a document.
When I search for "07/02/2004 - 07/02/2005", then it finds the document.

**Comment by annelhote** [comment]
1. Can't reproduce.
2. Previously fixed.
