### ISSUE TITLE
Regex mysteriously not supported

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#382]
How to reproduce:
- there is this mention of "IBAN Number: LU46 0141 1398 7650 0000" in document https://datashare-demo.icij.org/#/d/luxleaks/56a81c0d80b80d02de6d5eb3b6a87a629f38662a2b900787c2230f8af4fd8b9c4871cf80762d31b8486336d5610b76f3/56a81c0d80b80d02de6d5eb3b6a87a629f38662a2b900787c2230f8af4fd8b9c4871cf80762d31b8486336d5610b76f3
- if the test below says right, this regex should catch it : LU[0-9]{2}[ ]?[0-9]{4}[ ]?[A-Z0-9]{4}[ ]?[A-Z0-9]{4}[ ]?[A-Z0-9]{4}
<img width="1124" alt="Screenshot 2020-02-07 at 14 59 40" src="https://user-images.githubusercontent.com/17233829/74035405-7db54d80-49ba-11ea-9b21-8b323aac8431.png">
But Datashare says "no document found" https://datashare-demo.icij.org/#/?q=%2FLU%5B0-9%5D%7B2%7D%5B%20%5D%3F%5B0-9%5D%7B4%7D%5B%20%5D%3F%5BA-Z0-9%5D%7B4%7D%5B%20%5D%3F%5BA-Z0-9%5D%7B4%7D%5B%20%5D%3F%5BA-Z0-9%5D%7B4%7D%2F&from=0&size=25&sort=relevance&index=luxleaks&field=all&stamp=yjrwtm

**Comment by Soliine** [comment]
It could be due to the tokenizer we use. https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html
I added this tokenizer to our User Guide so people know which one we use. "Datashare relies on Elastic's Regex syntax as explained here (refer to this page for more details) and uses this tokenizer." https://icij.gitbook.io/datashare/all/search-with-operators#regular-expressions-regex

**Comment by annelhote** [comment]
Another way of saying the same thing :
In any type of search, you won't be able to grab the space character on the content file, because we use the standard tokenizer. The standard tokenizer divides text into terms on word boundaries, as defined by the Unicode Text Segmentation algorithm. That means that the space is not indexed as it is in our search engine.

**Comment by annelhote** [comment]
FYI, here is the ["IBAN REGISTRY – This registry provides detailed information about all ISO 13616-compliant national IBAN formats. – Release 86 – January 2020"](https://www.swift.com/resource/iban-registry-pdf).
