### ISSUE TITLE
Health check endpoint and API status

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#384]
for monitoring and diagnostic it would be nice to have a health status that could give : 

- status of databus connection
- status of database connection
- status of shared queues 
- status of index

That information could be given by 

- an http endpoint `/api/status` in http mode 
- an option --status in CLI mode to check if the parameters are correct

What do you think ?

**Comment by pirhoo** [comment]
That sounds perfect :ok_hand:

**Comment by bamthomas** [comment]
We have to add support for prometheus to fully integrate to the op ecosystem. So we will add a `format=openmetrics` parameter to the url : 

```
GET /api/status -> application/json (default format = JSON)
GET /api/status?format=openmetrics -> text/plain; version=0.0.4
```
As mentioned in [OpenMetrics documentation](https://prometheus.io/docs/instrumenting/exposition_formats/).

The metric type will be made of `datashare_<plateform>`for example `datashare_demo` and will be of the form showed in [this book](https://books.google.fr/books?id=QW1jDwAAQBAJ&pg=PT101&lpg=PT101#v=onepage&q&f=false).

For example : 
```
# HELP gauge The datashare resources
# TYPE gauge datashare_demo
datashare_demo{state="OK",resource="database"} 1 <timestamp>
datashare_demo{state="KO",resource="databus"} 0 <timestamp>
datashare_demo{state="OK",resource="document_queue"} 123 <timestamp>
datashare_demo{state="OK",resource="batch_queue"} 12 <timestamp>
datashare_demo{state="KO",resource="index"} 0 <timestamp>
```
