### ISSUE TITLE
Help link should link to support

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#393]

**Comment by annelhote** [comment]
Should be passed through the bck using `DS_DOCKER_XXX`. Then this option is available in the config via XXX in camelCase.

**Comment by annelhote** [comment]
@pirhoo I think that I don't fully understood your need here. It is already available through env var like we said. Should I remove it from the "mode" and set it through our ansible playbook ?

**Comment by pirhoo** [comment]
This setting should *not* be dependent to the mode.

Just remove the value in the mode settings:

https://github.com/ICIJ/datashare-client/blob/master/src/modes/server.js#L6
https://github.com/ICIJ/datashare-client/blob/master/src/modes/local.js#L4

And add `helpLink: 'https://github.com/ICIJ/datashare/wiki/Datashare-Support'` to the common settings:

https://github.com/ICIJ/datashare-client/blob/master/src/utils/settings.js

This way we can simply override it with an environment value:

```
DS_DOCKER_HELP_LINK: https://whatever.icij.org
```
