### ISSUE TITLE
Highlights in snippets are sometimes not visible

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#400]
Let's investigate why sometimes, highlights in snippets are not visible, as in this example: https://datashare-demo.icij.org/#/?q=france&from=0&size=25&sort=creationDateOldest&index=luxleaks&field=all&stamp=yuvrlm

On a 13-inch Mac using Chrome, I see this:
<img width="659" alt="Screenshot 2020-03-13 at 14 12 09" src="https://user-images.githubusercontent.com/17233829/76623944-a8a03d80-6534-11ea-920a-780dee7028ac.png">

**Comment by annelhote** [comment]
Switch in table view.

**Comment by annelhote** [comment]
As a sumup about the highlights :
- Each highlight is fragment of text of 50 letters.
- There are maximum 3 highlights.
- The search term is between "<mark>" tags.
- All the highlights are joined with "[...]".
