### ISSUE TITLE
Extensions for backend

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#401]
As we wrote a plugin system for the front (see #375) it would be convenient for people that want to extend the backend to do so.

A first step could be the refactoring of the NLP pipelines to transform them into plugins. There is no HTTP API change so it is easier.

For the front, we could expose a property or an endpoint to get the list of loaded NLP pipelines. 

We could have by default CoreNLP.

**Comment by pirhoo** [comment]
We should use a specific directory for the extensions (and so a dedicated `--extensionsDir` to differentiate from `--pluginsDir`).
