### ISSUE TITLE
Reorder menu and create a FAQ link to Gitbook

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#42]
Reorder menu:
1. Analyze documents
2. FAQ > https://icij.gitbook.io/datashare
3. Ask for help
4. About

**Comment by annelhote** [comment]
* Change Add documents link url according to user OS
* Remove logout button on localhost

**Comment by Soliine** [comment]
At question "Which technology do you want to apply in order to find named entities?", add in brackets : "CoreNLP (_by default - CoreNLP offers the highest probability of working in most documents_)"

**Comment by annelhote** [comment]
Comment copied and pasted into #43
