### ISSUE TITLE
In batchSearch, a link on a document should set the query

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#423]
To reproduce:
- Open a batch search
- Select on a query (tick checkbox)
- Open a document which contains this query -> you see that the query is searched within the document and you can click on it (search terms)
- Go back to the batch search
- Open an another query (tick checkbox)
- Open a document which contains this query -> the terms searched in the document correspond to the **first terms searched**

**Comment by annelhote** [comment]
The search query is not reset on document opening.

**Comment by annelhote** [comment]
Solution adopted : for each link on a document, the query term should be set, in order to display the number of occurrences of the query term when I open that document.
