### ISSUE TITLE
See how Regex (doesn't) work and why

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#426]
We noticed some problems with spaces in Luxembourg IBAN in Lux Leaks. And also some issues with @.

**Comment by annelhote** [comment]
See here : https://github.com/ICIJ/datashare/issues/382

**Comment by annelhote** [comment]
And here : https://github.com/ICIJ/datashare/issues/75

**Comment by annelhote** [comment]
1. Here is a simple example of regexp to collect emails : `/.*\@.*/`. Note that the `@` character should be escaped. So no problem from that.

**Comment by annelhote** [comment]
2. For now, in the mapping of ES, the field `content` is index as `text` type with [Standard tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html) aka the default one. The standard tokenizer divides text into terms on word boundaries, as defined by the Unicode Text Segmentation algorithm. That means that the space is not indexed as it is in our search engine. And for the regexp, Elasticsearch will apply the regexp to the terms produced by the tokenizer for that field, and not to the original text of the field.
**SO** one way to solve that, would be to index the content of the file in a second field tokenized with [Keyword Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keyword-tokenizer.html). This would let us search for regexp like `/FR[0-9]{2}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{3}.*/`.
**BUT** this would force us to index the file content twice. As a reminder, I put here the [link](https://talk.icij.org/t/es-retrieve-content-or-not/4191) to see the average size of a document by project. So IMHO, I think it should not be done.

**Comment by annelhote** [comment]
So regexp will definitely not support spaces. Some workaround would be to search for multiple regexp with `AND` in-between like by example `/FR[0-9]{2}.*/ AND /[0-9]{4}.*/ AND /[0-9a-zA-Z]{11}.*/`.
