### ISSUE TITLE
New batch search: must click 2 times to select file type 

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#434]
How to reproduce:
- in version 5.10.12 on Mac on Chrome, I want to run a new batch search
- when I see suggestions of file types, 1. I cannot press Enter to select one 2. I must click 2 times on one selection to have it selected

=> we expect to be able to press Enter or click one time on it to have it selected

**Comment by annelhote** [comment]
The second point is linked to the first one. If you only click on a suggestion (without pressing "Enter"), it will be selected at once.
So only the selection with "Enter" is a problem.

**Comment by Soliine** [comment]
Right! Thanks.

**Comment by annelhote** [comment]
So now you can :
- Select the FileType input
- Start writing letters like "t" by example
- Look at the FileTypeSuggestions
- Navigate through it via up arrow and down arrow keys
- On your selected file type, press "Enter"
