### ISSUE TITLE
Transform this fileType search to be more relevant in BatchSearchForm

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#436]
How to reproduce:

Go to https://datashare-demo.icij.org/#/batch-search and type 'a' in file type.

<img width="312" alt="Screenshot 2020-04-10 at 14 09 13" src="https://user-images.githubusercontent.com/17233829/78989787-e47af280-7b34-11ea-8db2-7dc357db88b5.png">

It show file type which does not contain 'a' or start by 'a'. 

Same in other projects:

<img width="307" alt="Screenshot 2020-04-10 at 14 08 21" src="https://user-images.githubusercontent.com/17233829/78989817-fd83a380-7b34-11ea-9c06-6498d5f48427.png">
<img width="303" alt="Screenshot 2020-04-10 at 14 07 28" src="https://user-images.githubusercontent.com/17233829/78989821-feb4d080-7b34-11ea-885a-b53442817375.png">

Is there a way to show first the file types which start by the letters typed?

**Comment by annelhote** [comment]
1. Yes, there is an "a" in "Portable Document Format (PDF)". Even 2 ;).
2. You are right, there is no "pl" in "Portable Document Format (PDF)" but compare the search string "pl" to the mime type, which is "application/pdf" for PDF. See https://www.iana.org/assignments/media-types/media-types.xhtml.
3. Same than before.

The filtering on MimeType let us do stuff like that :
![MimeType](https://user-images.githubusercontent.com/1478919/79218470-c40ea900-7e50-11ea-8332-a2ad0a4e1e51.png)

Or that :
![FileType2](https://user-images.githubusercontent.com/1478919/79218577-f02a2a00-7e50-11ea-8133-b079ca51942e.png)

**Comment by annelhote** [comment]
The second question about "Is there a way to show first the file types which start by the letters typed?" ask about the relevance of the results. That's a good idea. I will try to do it.

**Comment by annelhote** [comment]
What I did :
- Include extentions to fileTypes to be eable to search on it
- Use [fuse.js](https://fusejs.io/) on this search to add fuzziness and relevance
