### ISSUE TITLE
Wrong count and too long highlight on a searched term in a document

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#447]
How to reproduce:
- search for "président" in the demo website [here](https://datashare-demo.icij.org/#/?q=pr%C3%A9sident&from=0&size=25&sort=sizeLargest&index=luxleaks&field=all&stamp=ljxlcr)
- open the doc entitled: "PE_HE_Angel_Mermaid_010610.pdf" ([this one](https://datashare-demo.icij.org/#/d/luxleaks/5499b664f9da72804ba28e6ff51d894abac7becc86ee2ad3b0a78c6a190eec1c6cb1586abb2dfbb17088b30117340f94/5499b664f9da72804ba28e6ff51d894abac7becc86ee2ad3b0a78c6a190eec1c6cb1586abb2dfbb17088b30117340f94?q=pr%C3%A9sident))
- click on "Président" to find mentions in the document
- go to the sixth mention

The 10th last mentions (from 6 to 16) found by the search engine do not all contain "Président" (only the 6th one) and the highlights are longer than one word

<img width="840" alt="Screenshot 2020-04-27 at 11 31 57" src="https://user-images.githubusercontent.com/17233829/80357180-de964880-887a-11ea-9ab6-8e75cce5c56f.png">

**Comment by annelhote** [comment]
Can't reproduce in prod.

**Comment by Soliine** [comment]
I can't neither now.

**Comment by annelhote** [comment]
I found it, I was on the wrong document. On it now.

**Comment by annelhote** [comment]
It seems that highlighting with the local search replace and truncate the text after `<` caracter.

**Comment by annelhote** [comment]
Reproduced in local :

![step_01](https://user-images.githubusercontent.com/1478919/84485956-01e74c80-ac9d-11ea-8ab9-13009e647a3c.png)

![step_02](https://user-images.githubusercontent.com/1478919/84485980-0875c400-ac9d-11ea-9c39-86451a28944b.png)

**Comment by annelhote** [comment]
Add test about extracted text containing an HTML tag.
