### ISSUE TITLE
Queries with accent: no results to show

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#448]
It seems that accent and special characters causes a bug in showing results of queries in batch search. You can find an example with President/Président in Lux Leaks in staging called "test_sledesert_03" (date: April 27th).
Président with an accent is supposed to lead to 66 results https://datashare-demo.icij.org/#/?q=pr%C3%A9sident&from=0&size=25&sort=sizeLargest&index=luxleaks&field=all&stamp=cbkklu

**Comment by annelhote** [comment]
It seems that the filter action on BatchSearchResultsFilters is the reason of the error.

**Comment by annelhote** [comment]
See the bug here : https://datashare-demo.icij.org/#/batch-search/luxleaks/4b6796f5-89fb-40e8-8484-596951703ec5?order=asc&page=1&queries=pr%C3%A9sident&sort=doc_nb
