### ISSUE TITLE
Filter plugins by project

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#449]
Some plugins shouldn't be injected in Datashare client for all users.

For instance, `Lola` is a member of the  `babka` project. There is a plugin adding special feature to the project `babka` on Datashare. Only member of this project should get this plugin.

Moreover, `Lola` is not a member of the  project `lokum` which also has its own plugin. So `Lola` should not get the plugin for project `lokum`.

Finally, `Bob`, an anonymous user not logged in, shouldn't get any of these 2 plugins as he's not part of any project.

To be private and reserved to a specific projects, [a plugin's **package.json**](https://github.com/ICIJ/datashare/wiki/Datashare-Plugins#create-your-first-plugin) should define to attributes "private" and "datashare.projects".

Bellow a plugin that should only be used with the project `babka`:

```json
{
  "private": true,
  "datashare": {
     "projects": ["babka"]
  }
}
```

Bellow a plugin that should be used with the projects `babka` and `lokum`:

```json
{
  "private": true,
  "datashare": {
     "projects": ["babka", "lokum"]
  }
}
```

Bellow a plugin that should be used by everyone:

```json
{
  "private": false
}
```

**Comment by mvanzalu** [comment]
> Moreover, Lola is not a member of the project Lokum which also has its own plugin. So Lola should not get the plugin for project babka.

@pirhoo you meant Lokum ?

**Comment by pirhoo** [comment]
Correct!
