### ISSUE TITLE
Settings are not synchronized between front and back

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#450]
If I start Datashare with no settings file, while I go on the settings page, do a modification and save it, it will be sent to the back, that will override its default settings by the new ones dynamically and save it on the file. There is no file so the save action fails. So the back return a 404 error to the front, which should revert the last changes. In the end, back and front have different settings.

**Comment by bamthomas** [comment]
After having talked about it, it appears that : 

* as mentioned in [the doc](https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API#patch__api_settings) file settings have a higher priority than CLI. That means that if we set a default file, the CLI parameters are not going to be taken by datashare. That could be misleading
* if a setting file is provided at datashare launch then this issue doesn't occur
* all the installers are using settings file

For now, the front end should rollback a changed setting value if the PATCH request fails.

But as it is still a misleading we will see how we could better handle settings into datashare with the issue #565
