### ISSUE TITLE
Path filter is paginated

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#456]
This filter is currently limited to 8 folders with no way to display more. It shouldn't by paginated.

See https://github.com/ICIJ/datashare-client/issues/99

**Comment by annelhote** [comment]
Only for the first level.

**Comment by annelhote** [comment]
This is a quick and dirty solution to rise the limitation from 8 to 1000. But there is still a limitation. The correct solution would be to use [ES composite aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html) just like be did [here](https://github.com/ICIJ/datashare-client/blob/e3cb7336fd385809476b394aab2c1ab18a5ef443/src/components/BatchSearchForm.vue#L335-L342). But it might be tricky to do it with our current code infrastructure.

**Comment by pirhoo** [comment]
1000 is more than fine for now. The scenario where a user wants to scroll to more than 1000 folders on the first level sounds very unlikely. Like keep it this way for now. Thanks @annelhote !

**Comment by annelhote** [comment]
Ok, thanks for your feedbacks.
