### ISSUE TITLE
Plugin: create an email filter

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#457]

**Comment by pirhoo** [comment]
This might be helpful:

https://github.com/ICIJ/datashare-client/blob/master/public/docs/API.md#FiltersMixin+registerFilterForProject

**Comment by annelhote** [comment]
Plugin enabled on staging on project ML.

**Comment by annelhote** [comment]
Here is the repo of the plugin : https://github.com/ICIJ/datashare-plugin-email-filter.

**Comment by pirhoo** [comment]
Nice!!
