### ISSUE TITLE
Datashare Landing website should point to standalone installers

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#459]
The Docker installation should be only visible as an alternative solution in the "download popup".

Installation instruction should also be offered to the user when downloading an installer.

**Comment by pirhoo** [comment]
User guide for Mac: 
https://icij.gitbook.io/datashare/mac/install-datashare-on-mac#standalone-less-recent-than-os-x-el-capitan-10-11

User guide for Windows:
https://icij.gitbook.io/datashare/windows/install-datashare-on-windows#standard-windows-10-pro

Am I correct @Soliine ?

**Comment by Soliine** [comment]
Yes!

**Comment by Soliine** [comment]
We said we would change: 

1/
Requirements
Windows: Windows 7 Service Pack 2 or higher
Mac: High Sierra or higher
Linux: most recent versions
5 GB of free space on disk
4 GB of RAM

2/ 
Remove the requirement in the "Other platforms and versions" window
