### ISSUE TITLE
Entity recognition not working 

### ISSUE THREAD

**Issue by clombion** [ICIJ/datashare#460]
**Software**
MacOS 10.14
Datashare 6.3.6

**Steps to reproduce**

1. Download reports from a French municipal Council such as this one: http://www.merignac.com/sites/default/files/18_grpt_cde_mutuelle.pdf
As with all such reports, the document lists the names and surnames of all people present at the meeting, in a standardised way. 

2. Import this PDF or any other from the city website's report section http://www.merignac.com/sites/default/files/18_grpt_cde_mutuelle.pdf (I tried with all the PDFs of the first two pages

3. Launch the named entity recognition analysis after indexing and extracting the PDFs

**Expected behaviour**

All people whose names are present in the document should be identified by the algorithm

**Actual behaviour**

Nothing happens

**Comment by annelhote** [comment]
Same problem that @pirhoo and I encountered. In the Elasticsearch mapping, for the type `NameEntity`, the field `isHidden` has been renamed in `hidden`.

**Comment by bamthomas** [comment]
this commit https://github.com/ICIJ/datashare-api/commit/0df6c5254df81908f50cd2f0949b2e5a4f74489d should fix the issue @clombion 

We are going to release a new version of datashare soon

**Comment by bamthomas** [comment]
6.4.0 version should fix that

**Comment by clombion** [comment]
Tested on a new pdf and it works perfectly now, thanks!
