### ISSUE TITLE
Control + F : make text highlighting color more visible

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#469]
Some users find this highlighting color too light:
 <img width="841" alt="Screenshot 2020-05-15 at 13 56 30" src="https://user-images.githubusercontent.com/17233829/82051150-a59f0600-96b9-11ea-8d17-a3c13dd4c059.png">

I suggest we make it more opaque.

**Comment by pirhoo** [comment]
I increased contrast (and fix the highlight of the "active" term, it was broken):
![Capture d’écran de 2020-05-15 15-56-51](https://user-images.githubusercontent.com/471176/82058647-4fd05b00-96c5-11ea-9bcc-c5e5e77ea2a4.png)
