### ISSUE TITLE
Replace "Start a new task" with 2 buttons

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#47]
On http://localhost:8080/#/indexing, replace the button "Start a new task" with:

- **Button 1 : "Extract text"**

When clicking it, it opens the pop-in window "Do you want to extract text also from images and PDFs?" with radio buttons "Yes / No" but just "Next" (**no "Previous"**). And then we remove the recap pop-in window "Ready?".

- **Button 2 : "Find named entities"**

When clicking it, it opens the pop-in window "Which technology do you want to apply in order to find named entities?" with NLP options but just "Next" (**no "Previous"**). And then we remove the recap pop-in window "Ready?".

**Interdependence of these 2 buttons:** 
- If one extracting-text task is **still "running"**, the "Find named entities" button is grey and users **cannot** click on it. When they hover it and/or try to click on it, a message says : "Texts must be extracted before finding named entities". 
- When all extracting-text tasks are **"done"**, the "Find named entities" button is burgundy and users **can** click on it.

![github 2 buttons](https://user-images.githubusercontent.com/17233829/51526625-12dab800-1e33-11e9-8a7f-3413c9fa1031.png)

**Comment by annelhote** [comment]
- Button 1 : "Extract text"
  - Replace label of the button from "Next" by "Go"
- Button 2 : "Find named entities"
  - Replace label of the button from "Next" by "Go"

**Comment by Soliine** [comment]
It's great now. Thanks a lot!
