### ISSUE TITLE
On batchSearchList page, add  "Sort by" on the "Name" column

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#470]
Users are able to sort by Name the list of batch searches but we cannot see the corresponding arrow, as we can see in other sortable columns.

<img width="1015" alt="Screenshot 2020-05-15 at 14 44 11" src="https://user-images.githubusercontent.com/17233829/82051739-bc922800-96ba-11ea-8458-a181d6cd1604.png">

Also, I am able to click once on it but not a second time and I am not sure about the order of the list that is supposed to be sorted. Is it alphabetical or alphanumerical ?

**Comment by annelhote** [comment]
@Soliine :
* It seems that it is not possible to order batchSearches by name for now. If needed, we can add it.
* The default order is by creation date, the most recent at the top.
