### ISSUE TITLE
Batch search list: responsiveness problem?

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#472]
We have a responsiveness problem on /#/batch-search.

"Published" is cut:

<img width="1430" alt="Screenshot 2020-05-19 at 10 45 35" src="https://user-images.githubusercontent.com/17233829/82306392-4bef5200-99bf-11ea-9d3c-af58ed5cfd26.png">

**Comment by annelhote** [comment]
Multiple options :
- [ ] Ellipse the file name, set the whole file name into the `title`. There should be a tooltip by default.
- [ ] Put a CSS maximum width on the columns
- [ ] Add an horizontal scroll if array is too wide
- [ ] Transform the list into cards if column is too narrow
