### ISSUE TITLE
Batch Search: file not reconized properly

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#480]
When uploading a simple file with special chars, the backend is returning a 400 (with an empty error):

```csv
ç
C
Ç
ç
```

**Comment by mvanzalu** [comment]
Hello @pirhoo, a line with less 2 characters is automatically filtered, special char or not.
In this case all lines are too short, since every lines are filtered, an error 400 is returned.
The purpose is to prevent ES to having too many results.
