### ISSUE TITLE
Add a popin or a spinner for path suggestion in new batch search's form

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#481]

**Comment by annelhote** [comment]
Or use the [TreeView component](https://github.com/ICIJ/datashare-client/blob/master/src/components/TreeView.vue).

**Comment by annelhote** [comment]
Use a popin instead of a modal

**Comment by annelhote** [comment]
The popover will not do the tricks because it has no "cancel" and "ok" buttons. So bad idea.

**Comment by annelhote** [comment]
It does not work in production because the index is missing in the request to ES !

**Comment by annelhote** [comment]
Another issue :
- On the `Insights` page
- Select a project `project_01`
- Select a sub folder `folder_01` of this project on the TreeView of the `Number of documents by creation date` graph
- Change of selected project to `project_02`
- Open the TreeView of the `Number of documents by creation date` graph
=> `folder_01` of `project_01` is still selected
