### ISSUE TITLE
Bug with the 'Published' toggle button

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#490]
When a batch search is 'published', the toggle button shows it as not published. It happens on my machine (Mac using Chrome) whether the status of the batch search is queued or others.

<img width="1136" alt="Screenshot 2020-05-29 at 10 10 00" src="https://user-images.githubusercontent.com/17233829/83236959-b741dc80-a194-11ea-8645-97ab83b75e41.png">

<img width="1137" alt="Screenshot 2020-05-29 at 10 10 07" src="https://user-images.githubusercontent.com/17233829/83236966-b9a43680-a194-11ea-992c-cfe6a321e621.png">

Environment: staging
Version: 7.0.0
Machine: MacBookPro
Browser: Chrome

**Comment by annelhote** [comment]
It seems that this bug is happening while the BS is queued...

**Comment by annelhote** [comment]
It has to be my own batch search.
