### ISSUE TITLE
Insights: display number of documents in folder selection popin

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#494]
In this window, we see the size of each folder but not the number of documents. We can read the number of documents only after selecting a folder. It would be helpful to have the number of documents as soon as this window, next to the size :

<img width="791" alt="Screenshot 2020-05-29 at 11 37 40" src="https://user-images.githubusercontent.com/17233829/83245842-9b910300-a1a1-11ea-8b44-ce893e9d4775.png">

**Comment by annelhote** [comment]
Discussion with @Soliine :
- [ ] Let's align the 2 totals (size on disk and number of documents) with the other ones
- [ ] Add "docs" after the number of documents in folder
- [ ] If needed, add a title on the 2 columns like "Size" and "Number of docs"
