### ISSUE TITLE
Batch search query filter: make the popin longer/higher

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#495]
It is very helpful to quickly see the list of most frequent queries in a batch search. It would then be useful to see a longer list of queries in this dropdown:

<img width="371" alt="Screenshot 2020-05-29 at 11 18 37" src="https://user-images.githubusercontent.com/17233829/83246798-ecedc200-a1a2-11ea-93c8-8b6ada2478ee.png">

**Comment by annelhote** [comment]
I displayed the first 10 queries.
