### ISSUE TITLE
Search active filters: the text is not vertically center in the label

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#534]
Here, 'house' is at the bottom of the label while it could be vertically aligned to center:
<img width="70" alt="Screenshot 2020-06-02 at 17 23 35" src="https://user-images.githubusercontent.com/17233829/83538236-df636f80-a4f5-11ea-990f-260a8722beab.png">

**Comment by annelhote** [comment]
I can not reproduce it, what is your screen resolution ? Which env. (local, staging, demo, prod) ? Would you share an url maybe ? Many thanks.

**Comment by Soliine** [comment]
Hi Anne, sure. It was in local. On Mac, using Chrome. I am full screen browser window on a 13-inch MacBook Pro.
