### ISSUE TITLE
Path filter: unable to scroll on Chrome

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#540]
User reported not being to scroll on the paths filter, using Chrome and  Windows 8.1.

**Comment by annelhote** [comment]
Can't reproduce on Chrome on Linux.

**Comment by annelhote** [comment]
Can't reproduce on Chrome on Windows 10

**Comment by annelhote** [comment]
Ping @bamthomas . In case you have a Windows 8 Virtual Machine with Chrome, would you please try to reproduce this bug ? Thank you !

**Comment by annelhote** [comment]
How to reproduce :

**Comment by Soliine** [comment]
FYI not reproduced on Chrome on Mac.

**Comment by Soliine** [comment]
This bug should disappear with Pierre's latest developments.
