### ISSUE TITLE
Error installling

### ISSUE THREAD

**Issue by gsab2** [ICIJ/datashare#543]
Hi,
I'm totally illiterate in coding. Tried my best trying to install Datashare on mac OS Catelina. But getting an error. Not sure how to proceed or give any info here to get some help. Hope its possible and an error on my part.

Any help at all much appreciated.

Glen

![Screenshot 2020-06-23 at 10 24 02 pm](https://user-images.githubusercontent.com/25708366/85466633-1e8b5a80-b5a2-11ea-8413-7ca712577d2e.jpg)

![Screenshot 2020-06-23 at 10 25 24 pm](https://user-images.githubusercontent.com/25708366/85466642-20edb480-b5a2-11ea-8813-5beb74b7ead9.jpg)

![Screenshot 2020-06-23 at 10 23 51 pm](https://user-images.githubusercontent.com/25708366/85466615-192e1000-b5a2-11ea-9c37-3a410816c9f8.jpg)

![Screenshot 2020-06-23 at 10 23 26 pm](https://user-images.githubusercontent.com/25708366/85466574-0c112100-b5a2-11ea-9f6a-b47c6e72eedc.jpg)

**Comment by bamthomas** [comment]
hello @gsab2 thanks for reporting.

Yes you have to accept xcode intallation.

I think it is an xcode issue are you sure that the popups are in this order?

**Comment by gsab2** [comment]
Hi Bamthomas, thanks for getting back to me. The screen shots aren't in the right order. Sorry for that.

I thought the error about Xcode meant I instead I should try to install Xcode from the apple app store. I did that but the install errors still happened.

I accepted all the options I had for installing stuff.

**Comment by Soliine** [comment]
Hi gsab2, have you succeed in installing Datashare since 2 weeks ago? 
I also wondered if you followed our User Guide's steps regarding installation on Mac: https://icij.gitbook.io/datashare/mac/install-datashare-on-mac and how you proceed.

**Comment by gsab2** [comment]
Hi Soliine,
I just tried again but still got the message during installation saying it had failed.   I did follow the instructions on the link you sent

**Comment by bamthomas** [comment]
@gsab2 maybe what we could do is a session with screen sharing, because I don't see how to understand the problem.
Please send a mail to datashare and we will set time and date.
