### ISSUE TITLE
Error on local search

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#548]
When I do an exact search on MacronLeaks like "Emmanuel Macron" I found a doc. But in local search it says "Emmanuel Macron : 0". Because there is a carriage return between "Emmanuel" and "Macron". So the count should be corrected, plus the local search should be correct, and the match should be highlighted.

**Comment by annelhote** [comment]
The issue is fixed but the side effect is that the document's content is not beautifully displayed anymore, because the line breaks have to be deleted.

**Comment by Soliine** [comment]
Let's try to change the Regex in order to get the line breaks.
