### ISSUE TITLE
Set request timeout to 60 seconds

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#549]
Among the errors behind "Something went wrong" on the simple search, one is linked to this timeout which seems to be set at 30 seconds.
<img width="1386" alt="Screenshot 2020-06-26 at 15 04 38" src="https://user-images.githubusercontent.com/17233829/86014865-270be700-ba21-11ea-856a-86a7697f6ebc.png">
Bruno suggested to harmonize it with the other timeout which is set at 60 seconds.

**Comment by annelhote** [comment]
This is now a settings here : https://github.com/ICIJ/datashare-client/blob/master/src/utils/settings.js#L183.
