### ISSUE TITLE
See if we can display another animation for search's progress

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#552]
At the moment, when we press "Search" in Datashare's search bar, an animation in the form of a pink progress bar at the top, is launched.

As we are lengthening the timeout to [60 seconds](https://github.com/ICIJ/datashare/issues/549) instead of 30, we could now display a more transparent pink progress bar which would :
- progress at a pace of 1/60th of the total every second
- go to the end of the progress bar as soon as the query is finished

**Comment by annelhote** [comment]
The progress bar increase of 2% each second, So it will reach the end in 50 seconds instead of 60.
