### ISSUE TITLE
Datashare Local : PDF preview is broken

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#557]
The PDF.js seems to have issues previewing files:

![Capture d’écran de 2020-07-10 15-44-46](https://user-images.githubusercontent.com/471176/87161163-65789000-c2c4-11ea-92a8-22a955b5186d.png)

**Comment by annelhote** [comment]
Can't reproduce it in local. Could it come from your PDF ?

**Comment by pirhoo** [comment]
Same for all PDFs for me. You can try with this one: 

[pg_0037.pdf](https://github.com/ICIJ/datashare/files/4912025/pg_0037.pdf)

Note that you must not use the preview server.
