### ISSUE TITLE
GET apikey 

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#558]
allow to GET a key 

Plus change api for create/delete using userid
```
GET /api/key/bthomas
PUT /api/key/bthomas
DELETE /api/key/bthomas 
```
part of #501

**Comment by mvanzalu** [comment]
The GET would also be a CLI command ?

**Comment by annelhote** [comment]
See doc here : https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API#apikey thanks to @mvanzalu
