### ISSUE TITLE
Datashare fails to call backend after install on MacOS

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#560]
On MacOS is Catalina 10.15.5 the install process is running well. 

Indexing documents also.

but when using the front app on safari we get 401 errors :

```
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (_search, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (_search, line 0)
[Error] Unhandled Promise Rejection: net.codestory.http.errors.UnauthorizedException :: {"path":"/datashare/doc/_search","query":{},"body":"{\"size\":0,\"query\":{\"match\":{\"type\":\"Document\"}},\"aggs\":{\"extractionDate\":{\"date_histogram\":{\"field\":\"extractionDate\",\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1,\"interval\":\"1M\",\"format\":\"yyyy-MM\",\"missing\":\"0000-01\"},\"aggs\":{\"bucket_sort_truncate\":{\"bucket_sort\":{\"size\":1000}}}}}}","statusCode":401,"response":"{\"error\":\"net.codestory.http.errors.UnauthorizedException\"}"}
(anonymous function)
promiseReactionJob
[Error] Unhandled Promise Rejection: net.codestory.http.errors.UnauthorizedException :: {"path":"/datashare/doc/_search","query":{},"body":"{\"from\":0,\"size\":25,\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"path\":{\"order\":\"asc\"}}],\"_source\":{\"includes\":[\"\"],\"excludes\":[\"content\"]},\"highlight\":{\"fields\":{\"content\":{\"fragment_size\":50,\"number_of_fragments\":3,\"pre_tags\":[\"<mark>\"],\"post_tags\":[\"</mark>\"]}}},\"query\":{\"bool\":{\"must\":[{\"match_all\":{}},{\"bool\":{\"should\":[{\"query_string\":{\"query\":\"\",\"default_field\":\"\"}},{\"has_child\":{\"type\":\"NamedEntity\",\"query\":{\"query_string\":{\"query\":\"\",\"default_field\":\"mentionNorm\"}}}}]}},{\"match\":{\"type\":\"Document\"}}]}}}","statusCode":401,"response":"{\"error\":\"net.codestory.http.errors.UnauthorizedException\"}"}
[Warning] The resource http://localhost:8080/app.app.js.map?ver=a395488e45a0cb0eb8fc was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Warning] The resource http://localhost:8080/chunk-vendors.chunk-vendors.js.map?ver=6efbbc0f7fc2a7fce7f5 
```

**Comment by bamthomas** [comment]
I made tests with your corpus without errors. That said :

1. it was with MacOS Mojave 10.14.6 (core i5)
2. indexing of the corpus took 2 hours and 42mn
3. I tested with FF

When I use Safari I have weird errors in the console.

**Comment by mvanzalu** [comment]
Some mac users get an error during the installation (Catalina 10.15.5) 

`Aug 18 15:43:55 MacBook-Pro-XXX Installer[68323]: Package Authoring Error: <background_scaling> has an unsupported MIME type: X-NSObject/NSNumber
Aug 18 15:43:55 MacBook-Pro-XXX  Installer[68323]: Package Authoring Error: <background_alignment> has an unsupported MIME type: X-NSObject/NSNumber
Aug 18 15:43:55 MacBook-Pro-XXX  Installer[68323]: Package Authoring Error: <layout-direction> has an unsupported MIME type: X-NSObject/NSNumber
Aug 18 15:43:55 MacBook-Pro-XXX  Installer[68323]: Failed to load specified background image
Aug 18 15:43:55 MacBook-Pro-XXX  Installer[68323]: Could not load resource readme: (null)
Aug 18 15:43:55 MacBook-Pro-XXX  Installer[68323]: Could not load resource license: (null)
`

**Comment by bamthomas** [comment]
We've had a report from Catalina 10.15.6 and it worked well : installation OK and indexing/NER finding.
