### ISSUE TITLE
Batch searches queued but empty and never finished

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#566]
**Describe the bug**
I ran batch searches on Macron Leaks between May 19 and May 29, they are queued but empty and I can’t delete them.

**To Reproduce**
1. Go to Datashare.
2. Click on Batch Searches, filter by status, go to queued batch searches.
3. See that all of them are empty
4. If I try to download the queries, it leads to "An error occurred on the server"

**Expected behavior**
I expect either a success or a failure and I expect to be able to delete them from the interface.

**Screenshots**
<img width="1119" alt="Screenshot 2020-07-27 at 16 23 17" src="https://user-images.githubusercontent.com/17233829/88553522-a93dfa00-d025-11ea-9f56-94dbe52fe6ea.png">

**Desktop (please complete the following information):**
 - OS: MacBookPro, iOS
 - Browser Chrome
 - Version 7.2.2

**Comment by bamthomas** [comment]
I removed by hand the batch searches. 
I added a rule in BatchSearch constructor to avoid the existence of empty batch searches (with null or empty query list). see 02b5d0a 

Normally this should not happen anymore
