### ISSUE TITLE
handsometable - adds a textarea

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#57]
To reproduce this bug :
1. preview an xsls or a csv
2. Click on "Analyze my documents"
=> The textarea is visible on the right

**Comment by annelhote** [comment]
This upgrade raises a "JavaScript heap out of memory" on "make dist". Try to find a better lib instead.

**Comment by annelhote** [comment]
In the end, I removed the papaparse and handsontable libs, i upgraded the lib xlsx to version 0.14.1 and use only this one to display CSV and XLSX. This solved the bug and make it cleaner. And I added some unit tests on this feature.

**Comment by bamthomas** [comment]
seen on demo
