### ISSUE TITLE
[DaaP Plugins] Integrate the list of installed plugins with the list of plugins

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#571]
**Is your feature request related to a problem? Please describe.**
When I use the option `--pluginList` or the REST API, I'd like to see the installed plugins as well.

**Describe the solution you'd like**
adds the installed plugins list with for example an Installed/Uninstalled property

**Comment by bamthomas** [comment]
part of #502

**Comment by Soliine** [comment]
Let's add an "update" button too.

**Comment by annelhote** [comment]
* I added an "update" button, but I can not check if there really is a more up-to-date version of the plugin than the one installed
* When I do a search, I loose the title and description of the installed plugins
* After installing a plugin from a url, I can't see the title and description of the newly installed plugin

**Comment by mvanzalu** [comment]
@annelhote the fix fixes the broken research and your second point.
About the third one, when a plugin is installed from url, title and description are by default to **Null**. 
Furthermore if the extension/plugin file or folder are named like this _my-plugin-X.Y.Z_ the id will be _my-plugin_ and the version _X.Y.Z_, if not the id has the same name as the file/folder

**Comment by annelhote** [comment]
* Could we set the fields "titl" and "description" as searchable ?

**Comment by mvanzalu** [comment]
I think yes, I'll do it

**Comment by annelhote** [comment]
Linked to #637.
