### ISSUE TITLE
"Drop your file" in new batch search's form is broken

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#572]
**Describe the bug**
When adding a new batch search, the "drop your files here" functionality doesn't work.

**To Reproduce**
1. Go to 'Add a new batch search'
2. Drop a file above "Choose a file" => it becomes "Drop your file here" and the file's name is correctly displayed
3. Add the new batch search
4. See error, it says "Please select a file"

**Expected behavior**
We expect to have the file added.

**Screenshots**
<img width="486" alt="Screenshot 2020-07-30 at 12 02 51" src="https://user-images.githubusercontent.com/17233829/88911163-b9d8b500-d25d-11ea-9f41-72ebb57894e2.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.2.2

**Comment by annelhote** [comment]
This is a [bug](https://github.com/bootstrap-vue/bootstrap-vue/issues/3673) from bootstrap-vue which is not and will not be fixed. Sadly the workaround explain here is not usable for us because we have a complex form.
