### ISSUE TITLE
Special characters modify the query searching only characters after

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#575]
**Describe the bug**
It looks as if special characters like ç, ï or ñ modify the query and Datashare searches only for the characters after the special character in the string.

**To Reproduce**
1. Go to https://datashare-demo.icij.org/#/?q=ma%C3%B1ana&from=0&size=25&sort=relevance&index=luxleaks&field=all&stamp=klovyr or https://datashare-demo.icij.org/#/?q=fa%C3%A7on&from=0&size=25&sort=relevance&index=luxleaks&field=all&stamp=pbzbla or https://datashare-demo.icij.org/#/?q=la%C3%AFque&from=0&size=25&sort=relevance&index=luxleaks&field=all&stamp=kiptrv
2. See that the results look for "ana", "on" or "que".

**Expected behavior**
The results should search the special characters and the string as it is typed.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.4.0

**Comment by annelhote** [comment]
Duplicated of #576.
