### ISSUE TITLE
Search for string with accent leads to strange results 

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#576]
1. Search for ['Président' (with an accent) in Lux Leaks ](https://datashare-demo.icij.org/#/?q=pr%C3%A9sident&from=0&size=25&sort=relevance&index=luxleaks&field=all&stamp=htxlke)
2. It finds [one document](https://datashare-demo.icij.org/#/d/luxleaks/37000f34687eba16ce44c6b19875bab6f53a76caf6569551d77eb3ece991434ac79d645d058d80f419e5b1757ddc15eb/37000f34687eba16ce44c6b19875bab6f53a76caf6569551d77eb3ece991434ac79d645d058d80f419e5b1757ddc15eb?q=pr%C3%A9sident) 
3. I can't find the mention 'président' with the accent in the document. Plus, the label next to 'Président' in the document says 9 mentions. The control+F search engine finds 0 'président' and 5 'president'.

**Expected behavior**
Both for the main search bar and for the control+F search bar within a document, we'd like to be able to search for exact queries, with or without accent. If I search for 'Président', I find documents with 'Président' and the control+F search bar finds all the 'Président'. If I search for 'President', I find documents with 'President' (not 'Président') and the control+F search bar finds all the 'President'.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.4.4

**Comment by annelhote** [comment]
* It works in LOCAL mode
* It does not work in SERVER mode
=> So I guess that there is an encoding problem while transmitting the query through the API
