### ISSUE TITLE
Add a graceful stop to the batch runner daemon

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#579]
**Describe the bug**
Batch searches who are "running" (not "queued") are not launched again after a new version of Datashare is deployed.

**To Reproduce**
1. Launch a batch search
2. Deploy while it is running
3. See error: it is not launched again and it keeps "running"

**Expected behavior**
New batch runner should also look for "running" batch searches

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 7.4.3

**Additional context**
There is an example on our server titled "Test performance 11" by sledesert on August 3, 2020 11:02 AM.

**Comment by bamthomas** [comment]
Problem here is that a batch runner process can be parallelized, that means we deploy as much batch runner as we need when we have delay issue on batch search execution.

So if we take the RUNNING state then batch search runners are going to run several times the same batch search.

Ideally a batch search runner should catch a stop signal then reset the state of the current batch search to QUEUED. But depending on the context (docker ...) the event could be different (SIGTERM, ....).

**Comment by bamthomas** [comment]
After having mentioned this issue in our daily a bit more search showed that [when stopping a docker container](https://docs.docker.com/engine/reference/commandline/stop/) : 

> The main process inside the container will receive `SIGTERM`, and after a grace period, `SIGKILL`.

So the batch runner could add a shutdown hook : 

```
Runtime.getRuntime().addShutdownHook(new Thread() {
        @Override
         public void run() {
            // stop the current batch, remove results, and set status to QUEUED
         }   
        }); 
}
```
