### ISSUE TITLE
Insights: discrepancy between "Filter by folder" documents' count and "Search in documents" count

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#589]
**Describe the bug**
There might be an error of counting between "Filter by folder" documents' count in Insight and "Search in documents" count. In local Datashare, I see 33 documents in "Search in document" and only 31 in "Filter by folder" in Insights.

**To Reproduce**
1. Index documents in local Datashare
2. See how many are counted in "Search in documents" and how many are counted in the "Filter by folder" in Insights.

**Expected behavior**
We'd like to see the same total number of documents in both places.

**Screenshots**
<img width="910" alt="Screenshot 2020-08-11 at 15 21 41" src="https://user-images.githubusercontent.com/17233829/89902649-02da2300-dbe7-11ea-94f8-69fccb752f48.png">
<img width="797" alt="Screenshot 2020-08-11 at 14 59 39" src="https://user-images.githubusercontent.com/17233829/89902660-05d51380-dbe7-11ea-899d-d1302512b5c9.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.5.2

**Comment by Soliine** [comment]
I just saw that there are 31 documents on disk. Do the "Filter by folder" counts only the documents on Disk? 
<img width="279" alt="Screenshot 2020-08-11 at 15 28 47" src="https://user-images.githubusercontent.com/17233829/89903037-74b26c80-dbe7-11ea-9177-5f89c0d36a5b.png">

**Comment by annelhote** [comment]
No, it depends on the level of extraction. In the search view, have a look at your "Extraction level" filter. You should see that 2 documents have an extraction level of 1, and the others are on 0 which mean disk level.

**Comment by Soliine** [comment]
Ok - I didn't understand that this number counts only documents on disk even though it is written under my eyes. I confirm it's the case:
<img width="328" alt="Screenshot 2020-08-13 at 10 29 52" src="https://user-images.githubusercontent.com/17233829/90112239-04732a80-dd50-11ea-9492-9873d0814f55.png">
