### ISSUE TITLE
Length of search bar within a doc varies

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#594]
**Describe the bug**
It's not a bug but a detail. The length of search bar (within a doc) varies if it is one-digit number of mentions compared to 2 or more digit numbers.

**To Reproduce**
1. Go to a document (for instance [this one](https://datashare-demo.icij.org/#/d/luxleaks/e4d40cb50f4f21789acafd2d062948258a0f19666d9b4b1b509177e1e7360d58bc547babc5a16c8ecaa72d891477f733/e4d40cb50f4f21789acafd2d062948258a0f19666d9b4b1b509177e1e7360d58bc547babc5a16c8ecaa72d891477f733?q=%2a) and search for "le")
2. Search in the document for a query that appears more than 10 times
3. Go to the 9th and then to the 10th
4. See error: you see that the length of the search bar is greater at the 10th or more mentions

**Expected behavior**
It'd be better to set the length to a number with 3 digits (e.g. 111 of 888) so it doesn't move.

**Screenshots**
<img width="373" alt="Screenshot 2020-08-13 at 14 38 02" src="https://user-images.githubusercontent.com/17233829/90135435-f256b380-dd72-11ea-829d-73aa6208e5c6.png"> 
<img width="374" alt="Screenshot 2020-08-13 at 14 38 10" src="https://user-images.githubusercontent.com/17233829/90135433-f1258680-dd72-11ea-8f85-20d3e35b78b6.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.5.2

**Comment by Soliine** [comment]
When there are very long numbers, we can add the right not shortened text on hover.

**Comment by annelhote** [comment]
Add tooltip on over with the complete text.
