### ISSUE TITLE
Wrong Twitter link on datashare.icij.org

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#597]
**Describe the bug**
The link goes to https://twitter.com/ICIJ. 
(Facebook and Linkedin links are good)

**To Reproduce**
1. Go to datashare.icij.org
2. Click on Follow ICIJ
3. See page opened: https://twitter.com/icij => this account doesn't exist

**Expected behavior**
It should go to https://twitter.com/ICIJorg

**Screenshots**
<img width="1042" alt="Screenshot 2020-08-20 at 10 09 50" src="https://user-images.githubusercontent.com/17233829/90733786-54606d00-e2cd-11ea-84c0-54e594deaf8c.png">

**Comment by pirhoo** [comment]
Good one!
