### ISSUE TITLE
Batch search: sort queries by "query" isn't working at first

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#599]
**Describe the bug**
To sort queries by reverse alphabetical order works only after a third click.

**To Reproduce**
1. Go to https://datashare-demo.icij.org/#/batch-search/luxleaks/24cca19c-2f5e-418b-a66e-bf9aed4c9ad2?page=1&sort=query&order=desc
2. Click on 'Query' to sort results by reverse alphabetical order
3. See error that it keep Argentina at first

If you click again and again, it sorts the right way, it's just the first time. I could reproduce this on local.

**Expected behavior**
Sort queries by reverse alphabetical order as soon as the first click.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.5.3

**Comment by annelhote** [comment]
Just keep in mind that by default, the batch search results are sort by "Rank" asc as you can see on the top little triangle black.
So if you click on "Query" column, they will be sorted by query name asc.
And if you click again on "Query" column, they will be sorted by query name desc.
