### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by brainsqueezer** [ICIJ/datashare#6]
While installing in a brand new Debian Stretch came to this error. I supposed that version 0.17 would be mostly stable. It's for a small but urgent and 0 money project so I have to be time efficient on it.

Here is the full log from brand new machine (as root user):
$   wget https://raw.githubusercontent.com/ICIJ/datashare/master/datashare-dist/src/main/datashare.sh
$  apt-get install apt-transport-https dirmngr
$  echo 'deb https://apt.dockerproject.org/repo debian-stretch main' >> /etc/apt/sources.list
$ apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys F76221572C52609D
$ apt-get update
$  apt-get install docker git curl docker-compose vim htop
$  apt-get install docker-engine
$  mkdir  /mnt/data/
$  mkdir  /mnt/data/documents/
$  cd /mnt/data/documents/
$  chmod a+x /home/user/datashare.sh
$  /home/user/datashare.sh -w
Creating network "datashare_default" with the default driver
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:6.3.0)...
6.3.0: Pulling from elasticsearch/elasticsearch
7dc0dca2b151: Pull complete
a50481268b4a: Pull complete
ee5228de771f: Pull complete
da55b983e8eb: Pull complete
f2b07ded3946: Pull complete
667f672695bc: Pull complete
243fca89bf48: Pull complete
Digest: sha256:3169b4009903c47245d3bf81d8a7b11ab22ce2965598823384e5c4bbd4298316
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:6.3.0
Pulling redis (redis:4.0.1-alpine)...
4.0.1-alpine: Pulling from library/redis
88286f41530e: Pull complete
5b66139f3b4e: Pull complete
111233a1622e: Pull complete
df34d5b23fd6: Pull complete
d313ea2920e6: Pull complete
b82e355658cc: Pull complete
Digest: sha256:ff5db5ad4c91771af708c05aa2b44fccd5107687cf5caed4618c9a1f9471d226
Status: Downloaded newer image for redis:4.0.1-alpine
Creating datashare_elasticsearch_1
Creating datashare_redis_1
Folder path that contains documents [/mnt/data/documents] : /mnt/data/documents/
Folder path for cache (datashare will store models here) [/tmp/dist] :
waiting for index to be up...OK
Unable to find image 'icij/datashare:0.17' locally
0.17: Pulling from icij/datashare
8e3ba11ec2a2: Pull complete 
3dd014c6e448: Pull complete 
8b6257160d2f: Pull complete 
91e262098646: Pull complete 
03d86f381922: Pull complete 
8798e221b80a: Pull complete 
9fb071007ffc: Pull complete 
e1eeb27a4711: Pull complete 
19f3d1c18994: Pull complete 
f1fc0ab88ab6: Pull complete 
Digest: sha256:219dee5b161c4fee04780531db6c137389f4ae6f9a5081e2139cfb32b17beeec
Status: Downloaded newer image for icij/datashare:0.17
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-gate-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-cli-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-opennlp-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-mitie-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-ixapipe-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-corenlp-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-web-0.17-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
14:02:11,124 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:02:11,124 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:02:11,124 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/datashare/lib/datashare-nlp-gate-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,125 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
14:02:11,126 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-mitie-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,126 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-ixapipe-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,126 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-gate-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,126 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-opennlp-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,126 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-corenlp-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,126 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-cli-0.17-jar-with-dependencies.jar!/logback.xml]
14:02:11,151 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6cc4c815 - URL [jar:file:/home/datashare/lib/datashare-nlp-gate-0.17-jar-with-dependencies.jar!/logback.xml] is not of type file
14:02:11,316 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:02:11,324 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:02:11,335 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:02:11,345 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:02:11,426 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:02:11,429 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
14:02:11,441 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@981661423 - No compression will be used
14:02:11,443 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@981661423 - Will use the pattern ./logs/datashare_gatenlp.%d{yyyy-MM-dd}.log for the active file
14:02:11,449 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/datashare_gatenlp.%d{yyyy-MM-dd}.log'.
14:02:11,449 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
14:02:11,454 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Aug 03 14:02:11 GMT 2018
14:02:11,456 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:02:11,459 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ./logs/datashare.log
14:02:11,459 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [./logs/datashare.log]
14:02:11,461 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:02:11,461 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:02:11,462 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
14:02:11,462 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:02:11,463 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@100fc185 - Registering current configuration as safe fallback point

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2018-08-03 14:02:11,596 [main] INFO  DatashareCli - Running datashare web server
2018-08-03 14:02:11,603 [main] INFO  DatashareCli - with properties: {nlpParallelism=1, parserParallelism=1, stages=SCAN,INDEX,NLP, elasticsearchAddress=http://elasticsearch:9200, messageBusAddress=redis, resume=false, parallelism=2, help=false, web=true, mode=LOCAL, enableOcr=false, nlpPipelines=CORENLP,GATENLP,IXAPIPE,MITIE,OPENNLP, cors=no-cors, redisAddress=redis://redis:6379, clusterName=datashare, indexName=local-datashare, dataDir=/home/datashare/data}
2018-08-03 14:02:11,610 [main] INFO  PropertiesProvider - reading properties from jar:file:/home/datashare/lib/datashare-web-0.17-jar-with-dependencies.jar!/datashare.properties
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.HttpHost.create(Ljava/lang/String;)Lorg/apache/http/HttpHost;
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchConfiguration.createESClient(ElasticsearchConfiguration.java:66)
	at org.icij.datashare.mode.LocalMode.configure(LocalMode.java:33)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.codestory.http.injection.GuiceAdapter.<init>(GuiceAdapter.java:28)
	at org.icij.datashare.mode.CommonMode.defaultRoutes(CommonMode.java:53)
	at org.icij.datashare.mode.CommonMode.lambda$createWebConfiguration$c4402707$1(CommonMode.java:47)
	at net.codestory.http.routes.RouteCollection.configure(RouteCollection.java:88)
	at net.codestory.http.reload.FixedRoutesProvider.<init>(FixedRoutesProvider.java:27)
	at net.codestory.http.reload.RoutesProvider.fixed(RoutesProvider.java:29)
	at net.codestory.http.AbstractWebServer.configure(AbstractWebServer.java:62)
	at org.icij.datashare.WebApp.start(WebApp.java:36)
	at org.icij.datashare.cli.DatashareCli.main(DatashareCli.java:31)

**Comment by bamthomas** [comment]
Sorry for the delay.
it is weird, it seems that the jars are not aligned it this release. Have you solved the problem ?

If not and if you still want to try to use it, could you pull the latest version ?

**Comment by brainsqueezer** [comment]
Didn't saw the message from 6 days ago. I understand that the issue is not fixed. Let me know when there is a solution and I will try again.

**Comment by bamthomas** [comment]
should be fixed in 0.30 version thank you for reopening if it's not solving the issue
