### ISSUE TITLE
Can't search among tags on "TableView".

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#600]
**Describe the bug**
Can't search among tags on "TableView".

**To Reproduce**
1. Open Datashare
2. Go to "TableView"
3. Select one document
4. Type one letter in the tag search bar
=> You will see error in the console logs and in the network tab

**Comment by annelhote** [comment]
It does work in localhost:9009 but not in staging.

**Comment by annelhote** [comment]
It seems that the ES index is not well set !

**Comment by Soliine** [comment]
It works! The only problem now is a problem of alignment when users start typing tags:
<img width="340" alt="Screenshot 2020-09-07 at 15 05 46" src="https://user-images.githubusercontent.com/17233829/92390948-1f9d4400-f11c-11ea-8868-55899a033fa9.png">
