### ISSUE TITLE
Named Entity filters: wrong total

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#603]
**Describe the bug**
The "All" line in the Named Entity filters do not correspond to the total of documents.

**To Reproduce**
1. Go to https://datashare-demo.icij.org/, there are 1086 documents in Lux Leaks
2. Click on People filter
3. See "All" is 47,154. Anne says it corresponds to the total number of People-type Named Entity in the whole project.
<img width="352" alt="Capture d’écran 2020-09-29 à 10 46 06" src="https://user-images.githubusercontent.com/17233829/94534737-0b42f780-0241-11eb-9234-8860f65500fe.png">

**Expected behavior**
Let's display the total number of documents here (1086).

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.6.0

**Comment by annelhote** [comment]
I don't have this number and do not see how to do that without adding a new query.

**Comment by Soliine** [comment]
Let's see how much it would take in terms of performance and development time to add a new query.
