### ISSUE TITLE
'Contextualize Filters' doesn't apply for some filters

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#604]
**Describe the bug**
'Contextualize Filters' doesn't apply to Named Entity filters in some case(s).

**To Reproduce**
1. Go to https://datashare-demo.icij.org/#/?q=%2a&from=0&size=100&sort=relevance&index=luxleaks&field=all&f%5Blanguage%5D=ENGLISH
2. Click on the People Filter
3. See the number for "All" and the People Named entity. On Anne's computer, she says "I have no NE anymore in the filters". On my computer, "Contextualize filters" seemed to work:

With Contextualize Filters:
<img width="349" alt="Screenshot 2020-08-27 at 16 11 34" src="https://user-images.githubusercontent.com/17233829/91453498-18567a80-e880-11ea-8569-2f03311c5c32.png">

Without Contextualize Filters:
<img width="344" alt="Screenshot 2020-08-27 at 16 11 45" src="https://user-images.githubusercontent.com/17233829/91453506-1bea0180-e880-11ea-81fa-9125a2555338.png">

**Expected behavior**
Always have Contextualize Filters work in the Named Entity filters.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 7.6.0

**Comment by annelhote** [comment]
Same for "RecommendedBy".

**Comment by Soliine** [comment]
At the moment, as the functionality applies only to about 50% of the filters, to be fully transparent with users, the tooltip should say "Totals for each item displayed in the filters Tags, File Types, Languages, Paths and Extraction Levels will only count documents that correspond to the ticked items." So we are going to see if we could find alternatives.
