### ISSUE TITLE
Named Entities tab: 'Show more' could show more than 50 named entities?

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#605]
**Is your feature request related to a problem? Please describe.**
I have a large document which has 2197 People Named Entities (6218 Organizations and 6351 Locations). I'd like to search (with command F) and see all named entities but it loads only 50 by 50.

**Describe the solution you'd like**
I'd like to have two buttons: 
- "Show 50 more" (instead of one "Show more") 
- "Show all" (that would unfold all the named entities of this category - People, Organization or Locations)

But maybe it can raise issues in terms of performance?

**Comment by annelhote** [comment]
I find a really interesting idea ! About the performance, it could be long for sure. And chunking this load was a way of lighten the load of NE. Maybe we could warn this user by repeating the number of NE like : "Show all the 2197 People" ?

**Comment by Soliine** [comment]
It will lead to performance problems so we close this issue.
