### ISSUE TITLE
On the document view, list all the Named Entities, including the custom ones

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#607]
If a user adds its own NE with their own categories, it would like to see them in the "Named Entities" tab of the document.

**Comment by bamthomas** [comment]
see if there are some impacts on the back (deserialization) as named entities types are an Enum

**Comment by Soliine** [comment]
It is not currently possible but could be possible after we do lazy loading of Extracted Text: https://github.com/ICIJ/datashare/issues/767

**Comment by pirhoo** [comment]
We decided not to include named entities in the extracted text anymore.
