### ISSUE TITLE
Add animation on task progress bars in /indexing

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#61]
In order to show to users that Datashare is not freezing, we can animate progress bars of running tasks:
https://getbootstrap.com/docs/4.0/components/progress/#animated-stripes

**Comment by annelhote** [comment]
Set 99 as maximum progress number as long as the task is not "DONE".

**Comment by annelhote** [comment]
To reproduce it:
1. Empty your ES index
2. Launch an "extract text" action
=> In the progress bar, there a while where the progress number is 100% but the task is not done.

**Comment by annelhote** [comment]
I also encounter the case where the task.state was "RUNNING" but the the task.progress was "1". So I had to check the task.state too.

**Comment by bamthomas** [comment]
seen on demo
