### ISSUE TITLE
Display titles in the collapsed left menu and show it by default

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#617]
**Is your feature request related to a problem? Please describe.**
Users don't see the history, some have trouble navigating in Datashare and some use very small screens.

**Describe the solution you'd like**
- Display titles under icons in the collapsed left menu
- Show the collapsed left menu by default

![Menu](https://user-images.githubusercontent.com/17233829/91733971-99787f00-ebaa-11ea-82f4-13c0ad7beb13.png)

**Comment by annelhote** [comment]
The user guide is not visible in reduced sidebar. Shouldn't we show it with a link to the gitbook homepage ?

**Comment by annelhote** [comment]
One solution might be : Add the user guide entrance in the sidebar and display a popover on hover with the contextualized user guide pages, each link of the popover can be click and open the dedicated page in Datashare.

**Comment by pirhoo** [comment]
What about this?

![Screen Shot 2021-01-14 at 15 26 01](https://user-images.githubusercontent.com/471176/104603621-e4d48b00-567c-11eb-8699-90941d9d3936.png)
