### ISSUE TITLE
Tags finishing with "-type" are not visible in documents

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#620]
**Describe the bug**
Administratively added tags finishing by "-type" in the C project are not visible below the title nor in the 'Tag and Details' tab. 

**To Reproduce**
1. Go to to the C project
2. Filter on a tag ending with "-type"
3. Open a document
4. See error: there is no tags below the title nor in the 'Tag and Details' tab. 

**Expected behavior**
See tags at both places as other tags.

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Chrome
 - Version: 7.8.0

**Comment by annelhote** [comment]
The reason is that we recently changed the logic of tags. Now the tags should be in the ES index AND in the PSQL database. The recording in database is missing for these tags on this project. A "migration" should be done.

**Comment by annelhote** [comment]
The 2 projects Ca. and Cr. are concerned.

**Comment by annelhote** [comment]
The [related issue](https://github.com/ICIJ/datashare-tarentula/issues/1) remains open in tarentula.
