### ISSUE TITLE
Tags finishing with "-clusters" can be deleted

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#621]
Describe the bug
Administratively added tags ending by "-clusters"  in the C project can be deleted by users.

**To Reproduce**
1. Go to to the C project
2. Filter on a tag ending with "-clusters"
3. Open a document
4. See error: you can delete the tag

**Expected behavior**
They shouldn't be deletable.

**Desktop (please complete the following information):**
- OS: iOS
- Browser: Chrome
- Version: 7.8.0

**Comment by annelhote** [comment]
The logical should be : a tag created by user "icij" should not be deletable.

**Comment by annelhote** [comment]
Should the admin user "icij" be an environment variable ?

**Comment by annelhote** [comment]
Set admin user as env var.
