### ISSUE TITLE
Download Gitbook on demand (not by default)

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#624]
**Is your feature request related to a problem? Please describe.**
The size of the Gitbook with the images is heavy.

**Describe the solution you'd like**
We're thinking of allowing users to download Gitbook on demand (by clicking on a button). Let's see if we notify the user of any new version of the Gitbook (I don't think so as we don't do it for Datashare's new versions).

**Describe alternatives you've considered**
Be able to download the User Guide as a PDF, which is already possible on the Gitbook's webpage. https://icij.gitbook.io/datashare/

**Additional context**
Related to[ Can't see images from the gitbook #611](https://github.com/ICIJ/datashare/issues/611)

**Comment by pirhoo** [comment]
The team is currently considering to remove the Offline doc from Datashare Client.
