### ISSUE TITLE
Installing on Windows stops after a while

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#63]
This issue is to be completed after our call with the person who reported the bug.

"I am running Windows 10 Enterprise, version 1703, OS-version 15063.1446.
"Docker Desktop" was installed though, I noticed when I restarted my computer."

"I have a PC and Windows warned of the software but I could choose to ignore the warning. Nevertheless, after that, the installing stopped. Or should one choose "ignore" in this warning? Screenshot below (the Swedish buttons read "Cancel", "Try again" and "Ignore")."

![image](https://user-images.githubusercontent.com/17233829/52217258-5eac4900-2898-11e9-8763-b5b7a3e02a63.png)

**Comment by bamthomas** [comment]
This error occurs because datashare installer has been launched by a user that is not Administrator. We've achieve to install it running the installDatashare as Admin.

Then we found that curl was not installed in the computer.

**Comment by bamthomas** [comment]
to use native windows instructions, we used the powershell Test-NetConnection and Socket.Connect. 

see #76
