### ISSUE TITLE
'Back to search results' tooltip hides its arrow

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#630]
**Describe the bug**
'Back to search results' tooltip hides its arrow.

**To Reproduce**
1. Go to a long document (with small resolution of screen)
2. Scroll down
3. Hover the arrow to go back to search results
4. See error: the 'Back to search results' tooltip hides the arrow and prevents from clicking the button

**Expected behavior**
The tooltip shouldn't cover the arrow.

**Screenshots**
![Clipboard - September 10, 2020 9_31 AM](https://user-images.githubusercontent.com/17233829/92737782-b6b40700-f37b-11ea-93d3-980c8509a5e7.png)

**Desktop (please complete the following information):**
 - OS: unknown
 - Browser: Chrome
 - Version: unknown

**Additional context**
It was reported by a journalist who took the screenshot but I **can't reproduce it** on my Mac with Chrome.

**Comment by annelhote** [comment]
The only way I was able to reproduce was with a zoom on my browser. Is that the case ?
If not I would probably need a call with that journalist if possible ?

**Comment by Soliine** [comment]
The issue didn't appear anymore on the users' end.
