### ISSUE TITLE
Identify and count "big" files

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#633]
**Is your feature request related to a problem? Please describe.**
Users say it's very slow, sometimes impossible, to load and search in "large" files.

**Describe the solution you'd like**
Let's define "large" and analyze how many "large" files there are, in particular large txt, pdf and excel files.

**Comment by annelhote** [comment]
Let's create a new chart in "Insights" like number of documents by size.

**Comment by Soliine** [comment]
- "Big" files are files that have a big number of text characters
- We don't count this
- In the future during extraction or a posteriori, we could add a "Extracted text's length"

**Comment by bamthomas** [comment]
we will add a extractedTextLength that will be set on extraction phase

**Comment by annelhote** [comment]
Could it be the `contentLength` that we already have ?

**Comment by annelhote** [comment]
This field should be named `contentTextLength`

**Comment by annelhote** [comment]
This new field should be added to the mapping (back and front) and inserted while indexing.

**Comment by annelhote** [comment]
- [ ] staging
- [ ] demo
- [ ] prod

**Comment by annelhote** [comment]
We should create fields `mentionTextLength` that will count the number of characters in the field `mention`, `mentionNormTextLength` that will count the number of characters in the field `mentionNorm`.

**Comment by annelhote** [comment]
Delete `mentionTextLength` from existing indices in ES.
- [ ] Staging
- [ ] Demo
- [ ] Prod
