### ISSUE TITLE
Create a search bar to search in Batch searches

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#635]
**Is your feature request related to a problem? Please describe.**
More and more batch searches are listed [in this page](https://datashare-demo.icij.org/#/batch-search). The "sort by" features are not enough to find specific and relevant batch searches.

**Describe the solution you'd like**
Create a search bar to search in Batch searches' titles, descriptions and author' fields.

I suggest this design:
<img width="855" alt="Capture d’écran 2020-09-14 à 16 59 34" src="https://user-images.githubusercontent.com/17233829/93103169-9900dd80-f6ac-11ea-952c-680956f9d7dc.png">
<img width="945" alt="Capture d’écran 2020-09-14 à 17 05 40" src="https://user-images.githubusercontent.com/17233829/93103172-9acaa100-f6ac-11ea-80f6-e6a0023a7cc6.png">

**Comment by annelhote** [comment]
I added 2 query strings to [this endpoint](https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API#-post-apibatchsearch) :
- query, string, default is '*', string to search in fields.
- field, string, default is 'all', values : ['all', 'title', 'description', 'author'], 'all' means in 'title', 'description' and 'author'. The query should be searched in the selected field(s).

**Comment by mvanzalu** [comment]
- [ Hide 'author' field in LOCAL mode ]
- [ Allow search like %foo% by default ]

**Comment by mvanzalu** [comment]
Related [commit](https://github.com/ICIJ/datashare-client/commit/0c18761aec7141e72474cf57ed3c8a8fc7f75fdd) to author field

**Comment by mvanzalu** [comment]
Related [commit](https://github.com/ICIJ/datashare-client/commit/6e44d55115568e06fb8a5ecbe7d8eb02a6efebb7) to search button
