### ISSUE TITLE
[DaaP Extensions] Check if latest version of official extension is installed

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#637]
**Is your feature request related to a problem? Please describe.**
For now we can't see if an installed extension is the latest version, so we have an "update" button which is always clickable and reinstall it

**Describe the solution you'd like**
If the latest version is already installed, the update button isn't clickable

**Comment by annelhote** [comment]
Even : If the latest version is already installed, the update button isn't **present**.

**Comment by mvanzalu** [comment]
Would it be done with a new field (for exemple "latest") in the returned JSON ?
