### ISSUE TITLE
Update existing facets

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#64]
- [x] Checkboxes
- [x] Add "All" as first field
- [x] "Reset" for each facet [abandoned]
- [x] See where to put the "exclude" button
![update existing facets](https://user-images.githubusercontent.com/17233829/52286454-879c0f00-2968-11e9-982b-62ccd21abb65.png)

**Comment by annelhote** [comment]
- [ ] By default, "All" is selected and not the others checkboxes
- [ ] Add it on all the facets
- [ ] No "Reset" button
- [ ] Put in bold everything selected
- [ ] If "All" is selected and I click on it, nothing happens
- [ ] If "All" is selected and I click on "PDF", it should filters on "PDF" and selects it
- [ ] If "PDF" is selected and I click on "All", it should unfilters and selects "All"
- [ ] On the Named Entities Facets, put the icon only once next to the category name

**Comment by annelhote** [comment]
Should the "All" item appears when there is only one item ? What if after a research with only one result ?

**Comment by bamthomas** [comment]
@annelhote don't want to speak for our PO but if it adds complexity (ifs...) I don't know if it is worth 
At least I've already seen this kind of results panels always having the "All" displayed

**Comment by annelhote** [comment]
- [ ] Remove margin bottom on "All" item
