### ISSUE TITLE
Tesseract last version

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#65]
User added documents with Norwegian text and Datashare correctly identified Norwegian text and language:
![unnamed](https://user-images.githubusercontent.com/17233829/52289257-ff206d00-296d-11e9-9d6e-3fd588962a47.png)

**But it seems that the OCR can't recognize Æ,Ø and Å:** 

![unnamed 1](https://user-images.githubusercontent.com/17233829/52289278-06477b00-296e-11e9-93dd-fa29493657ca.png)
![unnamed 2](https://user-images.githubusercontent.com/17233829/52289282-0778a800-296e-11e9-8f4a-9724bd842430.png)

I read this issue here: https://github.com/tesseract-ocr/langdata/issues/36, it sounds like the issue was fixed but not sure...

Shall we check the last version of Tesseract ?

**Comment by bamthomas** [comment]
The container is rebuilt at each release with the latest alpine tesseract-ocr package. It seems to be the latest.

    /home/datashare # apk info tesseract-ocr
    tesseract-ocr-4.0.0-r0 description:
    open source OCR engine
    
    tesseract-ocr-4.0.0-r0 webpage:
    https://github.com/tesseract-ocr/tesseract/releases
    
    tesseract-ocr-4.0.0-r0 installed size:
    40067072

But another issue is mentioning that there is still Ø and Å missing : 
https://github.com/tesseract-ocr/langdata/issues/91

**Comment by bamthomas** [comment]
Waiting for issue 91 fixing in tesseract
