### ISSUE TITLE
[DaaP Extensions] Can't delete custom extension/plugin

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#653]
**Describe the bug**
When clicking on delete extension/plugin button from UI, it displays "Error while deleting the plugin." (404)
Delete function from CLI mode works

**Comment by annelhote** [comment]
Can't reproduce in local, neither for plugins nor extensions.

**Comment by mvanzalu** [comment]
It seems it's only the case for custom extensions/plugins

**Comment by annelhote** [comment]
Indeed

**Comment by annelhote** [comment]
CLI does not work either.
