### ISSUE TITLE
[Guided Tour] Keep showing the Menu step when collapsing the Menu column

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#658]
**Is your feature request related to a problem? Please describe.**
When we hide the Filters column as suggested, we leave the guided tour, we cannot see the next step.

**Describe the solution you'd like**
Would it be possible to keep displaying the Menu step, even though we collapse the Filters column?
<img width="319" alt="Screenshot 2020-11-03 at 14 45 22" src="https://user-images.githubusercontent.com/17233829/98000166-7bb6d880-1dec-11eb-966a-ef270f755926.png">

I am using Chrome Version 86.0.4240.111 on MacBookPro Catalina 10.15.7.

**Comment by annelhote** [comment]
We can not keep displaying the tour step if Filters column is collapsed as it is about the Filters column. We should find another way to do that.
