### ISSUE TITLE
[Guided Tour] History step is pointing to Insights icon on Chrome

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#661]
**Is your feature request related to a problem? Please describe.**
I am using Chrome Version 86.0.4240.111 on MacBookPro Catalina 10.15.7.
<img width="528" alt="Screenshot 2020-11-03 at 17 10 30" src="https://user-images.githubusercontent.com/17233829/98010995-9fcbe700-1df7-11eb-8761-522d2a32815f.png">

**Describe the solution you'd like**
Point the step to the History icon.

**Comment by Soliine** [comment]
I am trying to make texts shorter. I would suggest to remplace: "At any time, if you’re lost in your searches, go see Your History here" by "Lost in your searches? Go see Your History here!"

**Comment by annelhote** [comment]
Same in Firefox.
