### ISSUE TITLE
Datashare Installed successfully ( folder does not appear)

### ISSUE THREAD

**Issue by GTvin** [ICIJ/datashare#664]
I have tried various methods of trying to install it and it installs fine however the Datashare folder does not appear on the desktop.

I have read through the guidance you have on your website and cannot find any workaround or solutions to get this working for our user. I was wondering if you could provide some guidance on whether this would work on the following spec below:

Windows
Windows 10 enterprise 64bit operating system with 16GB
The Datashare folder on the desktop is appearing after downloading software via the website.
I checked through all of the C and D drives to try and locate folder but there is no files found or located.

**Comment by bamthomas** [comment]
Hello @GTvin the datashare folder is not on the desktop (we found that it was too invasive).

It is in `%APPDATA%\Datashare\data` : generally `\Users\ your_user\AppData\roaming\Datashare\data`
see https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/
