### ISSUE TITLE
Circuit breaking exception : data too large

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#665]
**Describe the bug**

When doing a search on a big index with large documents we have sometimes a failure for batch searches with the exception 

**To Reproduce**

The reproduction depends on a lots of parameters, but the error is : 

```
{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [14801586834/13.7gb], which is larger than the limit of [13716003225/12.7gb], real usage: [14801585528/13.7gb], new bytes reserved: [1306/1.2kb]","bytes_wanted":14801586834,"bytes_limit":13716003225}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [14801586834/13.7gb], which is larger than the limit of [13716003225/12.7gb], real usage: [14801585528/13.7gb], new bytes reserved: [1306/1.2kb]","bytes_wanted":14801586834,"bytes_limit":13716003225},"status":429}
```

**Expected behavior**

Have no error.

**Additional context**

By default the scroll size is 1000 in our production instance it is 100. We could change this parameter to see if it could lower the amount of data to be downloaded.

**Comment by Soliine** [comment]
I created this issue in parallel: https://github.com/ICIJ/datashare/issues/679

**Comment by bamthomas** [comment]
Latest findings. People [here](https://stackoverflow.com/questions/61870751/circuit-breaking-exception-parent-data-too-large-data-for-http-request) or [here](https://discuss.elastic.co/t/i-got-issue-about-data-too-large/185087/2) suggest to raise the memory.

AWS documentation [shows](https://docs.aws.amazon.com/fr_fr/elasticsearch-service/latest/developerguide/aes-limits.html) that the heap memory size is 32GB. In the [Heap Sizing page](https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html) of ES, they advice to give 32GB and twice for the total server memory (for Lucene that doesn't use heap memory), but that it is not useful (and could even be counterproductive) to give more to 32GB to the JVM.

 That means that the AWS servers are at a maximum for memory setting.
