### ISSUE TITLE
[Guided Tour] Opt for a constrained tour (click only on the steps)

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#666]
**Is your feature request related to a problem? Please describe.**
The problem is that user is kicked out of the tour if they click on the interface on the buttons described in the steps.

**Describe the solution you'd like**
- [x] Let's see if we opt for a tour in which users cannot click on the interface but only on the previous/next steps' buttons or the "skip tour" button 
- [x] Add "skip tour" at each step in that case so users can escape the tour at anytime
- [x] Add a cookie for the tour to appear just the first time on demo

**Describe alternatives you've considered**
We thought of [keep showing the steps](https://github.com/ICIJ/datashare/issues/658) and [having the steps following the users' navigation](https://github.com/ICIJ/datashare/issues/659) but steps are linked to the interface's elements so we cannot do that.

**Comment by annelhote** [comment]
@Soliine Instead of adding a "Skip" button on each step, there is a cross on the top right of each step to close the tour. But maybe it is not clear enough ?

**Comment by pirhoo** [comment]
I added the skip button already :)
![Screenshot_2020-11-04 Datashare(1)](https://user-images.githubusercontent.com/471176/98265953-fc5f0b80-1f89-11eb-8657-8c04b0a2ce24.png)

**Comment by pirhoo** [comment]
(it replaces the close button)

**Comment by annelhote** [comment]
For the first part of the solution, use [portal-vue](https://github.com/LinusBorg/portal-vue).

**Comment by annelhote** [comment]
Cookie name : "_ds_plugin_tour"
