### ISSUE TITLE
[DaaP] Create plugins/extensions dir in installers

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#667]
**Is your feature request related to a problem? Please describe.**

When running datashare from windows or Mac, we can't use the extensions/plugins feature because the directories are neither created nor mapped in the command line

**Describe the solution you'd like**

Being able to use them

**Comment by mvanzalu** [comment]
Related commit [fix extensions dir for datashare script ](https://github.com/ICIJ/datashare/commit/bae2fda4f1c5061ccfff96d560d19dff1a6a6d1e)
