### ISSUE TITLE
Unable to run the program on Linux Ubuntu

### ISSUE THREAD

**Issue by pachevalier** [ICIJ/datashare#67]
I've tried to run datashare.sh on Ubuntu 18.10 and I've got the following error 

```
$ sh datashare.sh 
datashare.sh: 13: datashare.sh: [[: not found
datashare.sh: 17: datashare.sh: function: not found
datashare.sh: 40: datashare.sh: Syntax error: "}" unexpected
```

**Comment by bamthomas** [comment]
Yes, datashare.sh is a bash script. So you either have to run it with `bash datashare.sh`or :

```
$ chmod +x datashare.sh
$ ./datashare.sh
```

**Comment by pachevalier** [comment]
Thanks for your answer. My error was due to a  wrong version of Docker CE (https://docs.docker.com/install/linux/docker-ce/ubuntu/).
