### ISSUE TITLE
Display a warning on "big" files

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#672]
**Is your feature request related to a problem? Please describe.**
Users can find big files and have issues searching within them.

**Describe the solution you'd like**
Display a text for big files. We need to define what are "big" files. The text could be for instance: "This file is large. To search within this file, please consider downloading it if your environment is secure enough."

**Comment by pirhoo** [comment]
How big is a "big file" :smiling_imp: ?

**Comment by annelhote** [comment]
See #633 .

**Comment by Soliine** [comment]
I suggest we add: "The search within a file can be long. Please consider downloading the file if your environment is secure."
