### ISSUE TITLE
Files not listed

### ISSUE THREAD

**Issue by johnnyblackday** [ICIJ/datashare#677]
**Describe the bug**
I have added couple of .docx and pdf files (cca 2 MB together) to the Datashare Data folder. 
I analyzed and indexed them. 
Then wanted to search.
No files were listed 

**To Reproduce**
1. Go to 'Analyze'
2. Click on 'Extract'
3. Click on Search in documents'
4. See error: 'No documents found'

**Expected behavior**
To be able to search in documents.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/75033487/100271377-b0383300-2f59-11eb-9439-4a2dba6acbf4.png)
![obrazek](https://user-images.githubusercontent.com/75033487/100271453-ca721100-2f59-11eb-96a1-33a9cd64d56a.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox
 - Version:  8.1.6. (docker desktop)

**Additional context**
Tried to reinstall. The same result

**(Optional) Your contact, availabilities and timezone if a video call with screensharing is needed**
For any private information, please consider sending an email to datashare@icij.org.

**Comment by annelhote** [comment]
Hey @johnnyblackday,

1. As a first step, please check that you do have your files listed in the Datashare Data folder. To do so, you can click on the path at the bottom of the left column, right under the app version :
![path](https://user-images.githubusercontent.com/1478919/100466230-e0eea880-30d0-11eb-8f71-e7e25b85df19.png)
Then you should be able to see a modal with all you files listed in it.

2. As a Windows user, we definitely advise you to use the "stand-alone version" of Datashare. You can find it [here](https://github.com/ICIJ/datashare-installer/releases/download/8.2.0/installDatashareStandalone.exe).

Please let us know if you still have an issue after that,

The Datashare team

**Comment by mvanzalu** [comment]
I couldn't reproduce : 
    OS: W10 Home
    Browser: Chrome
    Version: 8.1.6. (docker desktop)

**Comment by annelhote** [comment]
Close for inactivity
