### ISSUE TITLE
Batch search: change the failure button to show that it is clickable

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#679]
**Is your feature request related to a problem? Please describe.**
Users seem to not understand that they can see the error message of a batch search when it is a failure. The red failure button is clickable but it is not clear that it is clickable.

**Describe the solution you'd like**

- [ ] Turn "failure" text's button into "See failure", "See error" or "See error message".
- [ ] To be consistant, as "success" is not a button but a label, we should differentiate the design of the "success" label from the "failure" button. I suggest we write "success" in green with no container.

**Comment by annelhote** [comment]
Do not forget to change the "QUEUED" state.

**Comment by annelhote** [comment]
I did it but it is pretty ugly (according to me) :
![batchsearch_state](https://user-images.githubusercontent.com/1478919/100646581-7d69b280-333e-11eb-94f7-cc2c4c5b3b3a.png)

**Comment by Soliine** [comment]
![Group 40 (1)](https://user-images.githubusercontent.com/17233829/100865906-3a235700-3498-11eb-8683-e26456459a31.jpg)

**Comment by annelhote** [comment]
Icons :

**Comment by annelhote** [comment]
Use font color [here](https://github.com/ICIJ/datashare-client/blob/master/src/utils/settings.scss).
Succes : #00BB84
Failure : #DC3545
