### ISSUE TITLE
Batch search's filters: by status

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#683]
**Is your feature request related to a problem? Please describe.**
Batch searches add up over time and lots of batch searches make it difficult to find one or several specific batch search(es).

**Describe the solution you'd like**
Create a dropdown filter by status on this page above the table https://datashare-demo.icij.org/#/batch-search.
If there is no results, display "No result".
Create a "reset filters" button.

**Comment by Soliine** [comment]
As there are only 3 or 4 status (failure, success, pending, running - if I am correct), we shouldn't put any search bar here but just check boxes so the user can select one or several statuses in the dropdown.

**Comment by caro3801** [comment]
- [ ]  in API endpoint change status from string to Int since we use int in database
