### ISSUE TITLE
Batch search's filters: by publication status

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#685]
**Is your feature request related to a problem? Please describe.**
Batch searches add up over time and lots of batch searches make it difficult to find one or several specific batch search(es).

**Describe the solution you'd like**
Create a dropdown filter to select publication status (yes or no) on this page above the table https://datashare-demo.icij.org/#/batch-search
If there is no results, display "No result".
Create a "reset filters" button.

**Comment by mvanzalu** [comment]
- [ ] DB implementation
- [ ] Create API endpoints
- [ ] Frontend implementation
