### ISSUE TITLE
Can't navigate through pages of search results after filtering on a tag

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#689]
**Describe the bug**
I can not see the second page of search results if I filter on a tag.

**To Reproduce**
1. Open this [link](https://datashare-demo.icij.org/#/?q=%2a&from=0&size=25&sort=relevance&index=luxleaks&field=all&f%5Btags%5D=hello)
2. Click to go to the next page of results
=> You still see the same search results page

**Expected behavior**
I would like to see the second page of results

**Desktop (please complete the following information):**
Reproduced on Chrome and Firefox

**Additional context**
Even after clearing cache or modifying the url directly.

**Comment by annelhote** [comment]
Can't reproduce anymore ???

**Comment by Soliine** [comment]
I can't reproduce it neither. I tested on Chrome, Firefox and Safari, I tested it with selecting new tags too and it worked everywhere.
