### ISSUE TITLE
Allow users with docker toolbox to use datashare (windows < 10 pro)

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#69]
when datashare is used with a version of windows < 10 without VT-x/AMD-V virtualization the install script can detect it and install docker toolbox.

But the datashare launch script does not work.

**Comment by Soliine** [comment]
We published a FAQ about it : https://icij.gitbook.io/datashare/faq/how-can-i-install-datashare-on-a-windows-prior-to-windows-10-pro
