### ISSUE TITLE
Display a button to download the root file

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#693]
**Is your feature request related to a problem? Please describe.**
Users can't download children documents sometimes. Before tackling Tika errors, a workaround consists in downloading the parent document.

**Describe the solution you'd like**
As a user, in the case of children documents, when clicking on "Download", I see a pop-in window which asks: "Do you want to download:" with 2 buttons:
- "This document (891 Ko)"
- "Parent file (1,2 Go)"
... and a text above the "Parent file" button: "If the download of the document fails, please download the parent file. It will contain the children document".

The sizes of files displayed here consist in a separate issue https://github.com/ICIJ/datashare/issues/694

**Describe alternatives you've considered**
- catch the 500 error and let the app propose to download the parent
- generate the doc in let say /tmp and redirect on another url that would download and remove file
- download the file as not attached

**Comment by annelhote** [comment]
@Soliine what about adding a second button like "Download parent document" in order to save one click ?

**Comment by pirhoo** [comment]
The content-type displayed in the preview is wrong (it's from the parent instead of the root).
