### ISSUE TITLE
Display size of document and root file in popin window

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#694]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/ICIJ/datashare/issues/693

**Describe the solution you'd like**
Display the sizes of the children document and of the root parent file.

**Comment by annelhote** [comment]
Add a `Content-Length` header in the request ?

**Comment by Soliine** [comment]
Duplicate: https://github.com/ICIJ/datashare/issues/678
