### ISSUE TITLE
Display File Path in Batch Search results

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#695]
**Is your feature request related to a problem? Please describe.**
Users need to open a document to see which subfolder they are in. In the CSV, "DocumentPath" column only displays the end of the doc's path.

**Describe the solution you'd like**
As a user, when I am on the [Batch Search's results page](https://datashare-demo.icij.org/#/batch-search/luxleaks/c6da83aa-75e0-4b73-a8e6-4a5081474f54?page=1&sort=doc_nb&order=asc), after "Document Name" column, I also see a "Path" column which displays the path of the document.

**Additional context**
In the results' CSV : see issue #

**Comment by annelhote** [comment]
I will need the help of our backend dev to adapt the return of the batchSearch results.

**Comment by bamthomas** [comment]
we have to do the reverse of this  commit :/ https://github.com/ICIJ/datashare/commit/9ad45c997486a1d9e4f488d85091e277579a1716

**Comment by Soliine** [comment]
Document Path replaces Document Name and we display it fully on multiple lines so users can read all the folders of the path.

**Comment by mvanzalu** [comment]
There is one remaining to do, it's to apply a style on "Document Path" column to inline when text is long

**Comment by mvanzalu** [comment]
Next step is to add a popup with complete path

**Comment by annelhote** [comment]
https://bootstrap-vue.org/docs/components/tooltip
