### ISSUE TITLE
In batch search's CSV results, add a column for complete path

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#696]
**Is your feature request related to a problem? Please describe.**
Users need to open a document to see which subfolder they are in. In the CSV, "DocumentPath" column only displays the end of the doc's path. See: https://github.com/ICIJ/datashare/issues/695

**Describe the solution you'd like**
In batch search's CSV results, add a column for complete path. We can keep DocumentPath as it is and add new column with the complete path.

**Comment by mvanzalu** [comment]
Linked to #695
