### ISSUE TITLE
Exclude button excludes all

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#698]
**Is your feature request related to a problem? Please describe.**
To reproduce:
- go to French-excluded Luxleaks documents
https://datashare-demo.icij.org/#/?q=&from=0&size=25&sort=relevance&index=luxleaks&field=all&f%5B-language%5D=FRENCH
- click "German"
=> it excludes also German. We can either exclude all selected items or not exclude all of them but we cannot exclude some of them only.

**Describe the solution you'd like**
I'd like to be able to exclude French but select German (not exclude German). I think it is what we had before but I am not sure.

**Comment by annelhote** [comment]
No it was not the case before. As the "exclude" option is at the level of the filter, either you exclude all the selected values of the filter, or you include all the selected values of the filter.
To be able to do what you say, we would have an exclude filter on each value, which is more complicated in design and in understanding.
But you can use the field search

**Comment by annelhote** [comment]
However to answer your need, remember that you can use the ["field" query](https://icij.gitbook.io/datashare/all/search-with-operators#advanced-searches-using-metadata-fields). So to filter on the German language only, you could put "language:GERMAN" in the main search field. [And voilà](https://datashare-demo.icij.org/#/?q=language%3AGERMAN&from=0&size=25&sort=relevance&index=luxleaks&field=all&f%5B-language%5D=FRENCH&stamp=odogkj).

PS : As the language is a mono valuated field, it make no sense to exclude a value AND include another one. But I am sure it was for the example, which was great ... ;)
