### ISSUE TITLE
Display of "failure" is changed by column's width

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#700]
**Describe the bug**
<img width="282" alt="Screenshot 2020-12-10 at 11 52 47" src="https://user-images.githubusercontent.com/17233829/101789614-cde0cd00-3b01-11eb-830f-b984867ad0c0.png">

**To Reproduce**
1. Go to the batch searches' list
2. Find a "failure"
3.  See screenshot above
It happens on prod but not on the demo website on my side: https://datashare-demo.icij.org/#/batch-search
I am using Chrome V 87.0.4280.67 on MacBookPro 13 inches

**Expected behavior**
<img width="184" alt="Screenshot 2020-12-10 at 16 08 43" src="https://user-images.githubusercontent.com/17233829/101789791-fd8fd500-3b01-11eb-8ce0-1de38ac687b4.png">

**Comment by annelhote** [comment]
Fixed by #617
