### ISSUE TITLE
BasicAuth is not working

### ISSUE THREAD

**Issue by millaguie** [ICIJ/datashare#702]
**Describe the bug**
BasicAuth option is not working since version 7.2.0, it works on 7.1.4.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone https://github.com/ICIJ/datashare-keycloak-integration repo
2. Change about line 52: `command: "--dataSourceUrl jdbc:postgresql://ds-postgres/datashare?user=datashare&password=datasharepassword --mode SERVER --oauthClientId=datashare --oauthClientSecret=bb72e6db-5473-44ab-b950-27ffac4ade7a --oauthCallbackPath=/auth/callback --oauthAuthorizeUrl=http://keycloak:9080/auth/realms/main/protocol/openid-connect/auth --oauthTokenUrl=http://keycloak:9080/auth/realms/main/protocol/openid-connect/token --oauthApiUrl=http://keycloak:9080/auth/realms/main/protocol/openid-connect/userinfo"` to `command: "--dataSourceUrl jdbc:postgresql://ds-postgres/datashare?user=datashare&password=datasharepassword --mode SERVER --rootHost https://datashare:8080  --authFilter org.icij.datashare.session.BasicAuthAdaptorFilter"` this should change authentication to BasicAuth.
3. Fire up the environment `docker-compose up` 
4. When running, in another terminal run `docker exec -ti datashare-keycloak-integration_redis_1 redis-cli` and create the user's key `set foo '{"uid":"foo", "password":"fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9", "datashare_projects":["local-datashare"]}'`
5. Go to http://datashare:8080 and try to log in, the authentication page is not found. You can also try http://foo:bar@datashare:8080 no result. 

If you follow these steps with 7.2.0 or below this works.

**Expected behaviour**
A login should pop-up, or the login should work.

**Comment by pirhoo** [comment]
I think this can be closed https://github.com/ICIJ/datashare/commit/11129ebd1a791365014fa5fdbdcddbbc7f389d52#comments
