### ISSUE TITLE
[DataConnect] Deploy dataconnect into staging

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#703]
Here is the ToDo :
- [x] Include CI on extension and plugin github repo
- [x] Manage releases via github CL
- [x] Add extension and plugin into the repository of the back
- [x] Release a new version of Datashare
- [x] On the Ansible playbook of Datashare, set the env var for the Discourse host
- [x] On the Ansible playbook of Datashare, invoke the command to install the extension and the plugin [by CLI](https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API#-put-apipluginsinstall)

**Comment by mvanzalu** [comment]
This [commit](https://github.com/ICIJ/datashare-extension-dataconnect/commit/18ad654316e2eb8698d3545ba6bdd550edda95f7) and this [one](https://github.com/ICIJ/datashare-extension-dataconnect/commit/e78602350316a607d378c64ba5cd0128c0ff1a7c) are related to the issue

**Comment by annelhote** [comment]
There is still an issue in staging because the Datashare machine can not see the I-Hub machine.

**Comment by annelhote** [comment]
See #722 that should be resolved first.
