### ISSUE TITLE
'In this document' in document view always displays '0' as the number of results for a search term

### ISSUE THREAD

**Issue by madoleary** [ICIJ/datashare#709]
**Describe the bug**
A user searches for a specific term, then selects a document in which the term occurs. In document view, the number that appears next to the search term at `In this document` is always showing `0`, even if there are many matching results within the document for the search term.

**To Reproduce**
1. Search for an obvious term,
2. Select a document that contains the term,
3. See that the number displayed at `In this document` does not accurately reflect the number of results, and is always `0`, or `in metadata`

**Expected behavior**
The number should reflect the number of results for the search term in the selected document.

**Comment by annelhote** [comment]
Due to lazy loading of document's content. See [this commit](https://github.com/ICIJ/datashare-client/commit/030e269b6d5a150300deda57e8956fff8a5dd919).
