### ISSUE TITLE
As a user I would like to be able to rerun an ended batch search

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#718]
**Is your feature request related to a problem? Please describe.**
In the case of documents newly added to Datashare, it might be good to rerun a batch search to get additional results. This would also help us to "resume" batch searches [interrupted by a deployment](https://github.com/ICIJ/datashare/issues/579).

**Describe the solution you'd like**
On a [batch search page](https://datashare-demo.icij.org/#/batch-search/luxleaks/2e9db6f5-d7c8-4dfb-a6e1-fc19e9fd1096), next to the filter button, it would be good to have a "Rerun" button (with the [redo icon](https://fontawesome.com/icons/redo?style=solid)) with a confirmation step ("Are you sure you want to rerun this batch search? This will remove existing results").

Only failed or succeeded batch search can be rerun. On the backend, this operation will change the status to "queued" and delete all existing results.

**Comment by annelhote** [comment]
- Only the author of the BS can rerun it
- The user should be able to delete the previous BS with its results but it is not mandatory
- What about the new BS name
- Delete the previous results as soon as the new BS ended correctly
- Other issue : should be able to keep the previous results if wanted
- Which BS could be rerun ?

MVP : Duplicate and rerun a BS without deleting the previous one.

**Comment by annelhote** [comment]
For the other issue :
- The user should be able to delete the previous BS with its results but it is not mandatory
- Delete the previous results as soon as the new BS ended correctly
- Other issue : should be able to keep the previous results if wanted

**Comment by annelhote** [comment]
- No tooltip
- Label : "Rerun Batch search"

**Comment by annelhote** [comment]
Create a new endpoint `POST /api/batch/search/copy/:sourceBatchid` that will return the id of the newly created batchSearch. The batchSearch AND the batchSearch queries will be duplicated in DB. The name of the new batchSearch will be prefix by "[RERUN] ".
