### ISSUE TITLE
Hide Filters

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#72]
Note: the list doc column has always the same width.

![l9](https://user-images.githubusercontent.com/17233829/52479630-90c7ee80-2ba9-11e9-8144-97565949ca43.png)
![l10](https://user-images.githubusercontent.com/17233829/52479632-91608500-2ba9-11e9-8fcd-6f294bd9fe8b.png)

**Comment by annelhote** [comment]
@Soliine : FYI, on the preview, we forget the paging...

**Comment by annelhote** [comment]
- [ ] If filters are hidden, display the document part on full width

**Comment by Soliine** [comment]
> @Soliine : FYI, on the preview, we forget the paging...

In this design, we planned to have infinite scroll - which would kill the paging. But we could still discuss this later, nothing definitive yet!
