### ISSUE TITLE
Reduce size of some shards (40G to 20G)

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#729]
To reduce the size of some shards from 40G to 20G as indicated here: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/size-your-shards.html

**Comment by annelhote** [comment]
How to reindex : https://www.elastic.co/guide/en/elasticsearch/reference/6.8/reindex-upgrade-inplace.html

**Comment by annelhote** [comment]
I encounter a few problems during the reindex because of the size of our indexes, so I had to reindex like that :
