### ISSUE TITLE
Exact matches are separated by [...] in highlights

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#741]
**Is your feature request related to a problem? Please describe.**
It's misleading when you search for "[bureau d'imposition](https://datashare-demo.icij.org/#/?q=%22bureau%20d%27imposition%22&from=0&size=100&sort=relevance&index=luxleaks&field=all&stamp=hsdnbj)" for instance and in the results' highlights, they are sometimes separated by [...] while they are separated only by a space in the original document.

**Describe the solution you'd like**
It'd be better not to see [...] when the searched terms are separated only by a space.

**Comment by annelhote** [comment]
It seems it is an issue of [ES](https://github.com/elastic/elasticsearch/issues/29561). We can't use the `fvh` highlighter because our documents are not indexed with the `term_vector` type. We could increase the fragment size as a workaround but it won't solve the issue.
