### ISSUE TITLE
Download search results in CSV

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#749]
**Is your feature request related to a problem? Please describe.**
A user asks to be able to download the results of a simple search in a CSV format in order to go through them in a methodological way and make sure they've reviewed each document.

**Describe the solution you'd like**
In the table view,  let's see how we could create a 'Download in CSV' button: what fields would be downloaded (document name, highlight field, file type, creation date, link to the document), how many results could be written in the CSV (all? less? only selected?). Notes: If we do it with the front, we could use Tarentula but we need to work on the pagination (currently limited to 10k results). If we do it with the back, it would be a bigger work.

**Comment by annelhote** [comment]
We will do that through the [Tarentula](https://github.com/ICIJ/datashare-tarentula) tool.
