### ISSUE TITLE
In the path filter, the alphabetical order makes a difference between lowercase and uppercase

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#752]
In a folder, if I have the folders `Abcd`, `aabcd`, the alphabetical order will sort the folders in this order :
- Abcd
- aabcd

I would have to see :
- aabcd
- Abcd

**Comment by annelhote** [comment]
See [here](https://discuss.elastic.co/t/case-insensitive-sort-doesnt-work/143192/7).

**Comment by annelhote** [comment]
This bug is now fixed for the future projects that will be indexed into Datashare. A [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) is needed to fix it on the already indexed projects. The issue #729 will do it for the current project.

**Comment by pirhoo** [comment]
This commit add retro-compatibility for existing indexes:
https://github.com/ICIJ/datashare-client/commit/3942247fef22677f185a82d1b9db030a6b07bcad
