### ISSUE TITLE
Set maximum of queries in Batch Search to 60K

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#756]
**Is your feature request related to a problem? Please describe.**
Some users can make batch search with more than 60K and it leads to long processing and potential issues.

**Describe the solution you'd like**
Detect CSV with more than 60K and block them.

**Comment by bamthomas** [comment]
there are at least two http statuses that could be answered by the back : 

- a generic 400 "bad request" from client (usually it is related to the syntax)
- a more precise [413 Payload too large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413)

What do you think ?

**Comment by mvanzalu** [comment]
I think the 413 is fine
