### ISSUE TITLE
Extracted text not displayed when error while formatting the content to be displayed

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#759]
**Describe the bug**
After getting the message "This document is huge" and clicking on "Open anyway", the content of "Extracted Text" tab stays empty.

**Expected behavior**
Having the content of the extracted text.

**Comment by annelhote** [comment]
Indexing the guilty document takes a really long time...

**Comment by annelhote** [comment]
`contentTextLength | 2562833` in prod
docId : 5bc65bfc5e397df06e1bcffb64a53c16c17a06b38676ccde13a13db20c3cc4862cf2cde3978ebd438470d01437d39bf7 in prod

**Comment by annelhote** [comment]
In localhost, the text is correctly displayed.

**Comment by annelhote** [comment]
This seems to be a problem with the content itself.

**Comment by annelhote** [comment]
The error is due to the `xss` lib used to sanitize the HTML, because the content has a lot of `<p` and because of [our xss config](https://github.com/ICIJ/datashare-client/blob/master/src/store/pipelines/SanitizeHtml.js#L6), it raises an error.
