### ISSUE TITLE
curl command not installed

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#76]
in one of ICIJ partners' computer under windows 10 pro, there is no curl command. The datashare run script is not working.

**Comment by yilmazbingo** [comment]
curl is a unix command. in order to use this on windows:

download curl from https://curl.haxx.se/download.html for windows
  -extract the zip file. 
  -navigate to curl.exe and run it in command line.

**Comment by bamthomas** [comment]
thanks @yilmazbingo but I wanted to avoid the dependency on another download (that could break, that could evolve, etc.).
I've rewritten the batch script in powershell and will test it on our partners' computers.

**Comment by bamthomas** [comment]
The problem with powershell is that to be able to execute powershell scripts, we have to `Set-ExecutionPolicy` to `Unrestricted` . This could lead to security leaks.
