### ISSUE TITLE
"Open anyway": create keyboard shortcut

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#760]
**Is your feature request related to a problem? Please describe.**
When users open a lot of large documents in a row, it would be useful to save time and to click the "Open anyway" button with a shortcut.

**Describe the solution you'd like**
I suggest we use O and we indicate : "The search within this document can be long. Please consider downloading it if your environment is secure. Press O to open it anyway, or click the button".

Also, can we write "anyway" and not "Anyway" in the "Open anyway" button to harmonize with the rest of Datashare in general?

**Comment by annelhote** [comment]
Add it into the `Keyboard Shortcuts` modal.

**Comment by annelhote** [comment]
Icon suggestion : https://fontawesome.com/icons/envelope-open-text?style=solid. Poke @Soliine
