### ISSUE TITLE
Doesn't filter properly checked paths

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#761]
**Describe the bug**
On search mode, Datashare doesn't filter documents paths properly if checked path name is contained in an another path name.
Example : 
2 paths : foo and foo-bar
If foo is checked, the query will return results of foo and foo-bar.

**Expected behavior**
Filter exactly related documents.
For the example : return results of foo.

**Comment by annelhote** [comment]
Correction : the bug appears when path_2 starts by path_1 (and not when path_1 is container in path_2).
As mentioned before, the solution simplest would be to add an extra backslash at the end of the path in the ES query.
