### ISSUE TITLE
Add link to download in the demo website

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#765]
**Is your feature request related to a problem? Please describe.**
If you discover Datashare through the [demo website](https://datashare-demo.icij.org/#/), there is no link to the landpage where to download it.

**Describe the solution you'd like**
Change the banner text "Welcome to Datashare demo! You are connected as focused_euclid, a temporary user." into "Welcome to Datashare demo! You are connected as focused_euclid, a temporary user. [Download Datashare here](https://datashare.icij.org/)"

**Comment by pirhoo** [comment]
I configure the site alert plugin with the following lines:

```js
const appAlertMessage = 'Welcome to Datashare demo! You are connected as <strong>{username}</strong>, a temporary user. <a class="btn btn-sm btn-secondary py-0" target="_blank" href=" target="_blank" href="https://datashare.icij.org/">Download Datashare here</a>'
datashare.config.set('appAlertMessage', appAlertMessage)
```
