### ISSUE TITLE
Sharing button: have Formatted Text in first place among tabs

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#771]
**Is your feature request related to a problem? Please describe.**
In a [document](https://datashare-demo.icij.org/#/d/luxleaks/e4d40cb50f4f21789acafd2d062948258a0f19666d9b4b1b509177e1e7360d58bc547babc5a16c8ecaa72d891477f733/e4d40cb50f4f21789acafd2d062948258a0f19666d9b4b1b509177e1e7360d58bc547babc5a16c8ecaa72d891477f733?q=%2a), the sharing button shows option in this order: 

![Screenshot 2021-03-16 at 11 18 06](https://user-images.githubusercontent.com/17233829/111293319-6cbd1e00-8649-11eb-976e-1f9ccf274d1e.png) 
The first one (Text) is the URL which is already 0 click away. To send clean links, "Formatted Text" is one click away. 
 

**Describe the solution you'd like**
I suggest we put "Formatted Text" in the first position (which appears by default) so it becomes one click away. The new order would be: Formatted Text, Text, Markdown, HTML

**Comment by annelhote** [comment]
See [Murmur](https://icij.github.io/murmur/#/components/advanced-link-form).
