### ISSUE TITLE
DataConnect: paginate comments with infinite scroll

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#773]
**Is your feature request related to a problem? Please describe.**
We can see only the 20 first comments, not the next.

**Describe the solution you'd like**
Paginate comments with infinite scroll. See: https://github.com/ICIJ/custom-fields-api/commit/020d2724d0674740c3af1cba7a618182c0d3af9d

**Comment by pirhoo** [comment]
Blocked by https://github.com/ICIJ/datashare/issues/777

**Comment by pirhoo** [comment]
The infinite scroll should work both ways (scrolling to the top or to the bottom) so we can jump directly to the last posted message.

**Comment by Soliine** [comment]
We keep it open because it has never been tested on production or staging because we need a huge conversation with many comments.
