### ISSUE TITLE
Batch search: search only on documents with some tags

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#778]
**Is your feature request related to a problem? Please describe.**
As requested by users, it would be useful to select some tags and have the batch search run only on selected documents.

**Describe the solution you'd like**
![Screenshot 2021-03-24 at 09 05 29](https://user-images.githubusercontent.com/17233829/112275752-35b9be80-8c80-11eb-98ac-dffede94f985.png)
In the new batch search form > Advanced filters, add a 'Tags' above 'File types' (to keep the same order as there are in the search's filters). Design-wise, we could do as for 'File types': a field with suggestions when user types first letters of tags.

**Comment by annelhote** [comment]
As an immediate workaround, any search of tagged documents can be done by adding "tags:my_tag" to the (batch)search.

**Comment by Soliine** [comment]
I documented this in the user guide: https://icij.gitbook.io/datashare/all/batch-search-documents#want-to-search-only-on-some-documents
