### ISSUE TITLE
A batch search's results: have a better page selector

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#779]
**Is your feature request related to a problem? Please describe.**
The issue is for batch search with a lot of results like this one: https://datashare-demo.icij.org/#/batch-search/luxleaks/2e9db6f5-d7c8-4dfb-a6e1-fc19e9fd1096
If user wants to access page 24, they need to go page by page until 24. If they change the page number in the URL (for instance, https://datashare-demo.icij.org/#/batch-search/luxleaks/2e9db6f5-d7c8-4dfb-a6e1-fc19e9fd1096?page=24&sort=doc_nb&order=asc), then the page selector is at pages 1,2,3,4. so one cannot go from one page to another.
![Screenshot 2021-03-24 at 15 17 39](https://user-images.githubusercontent.com/17233829/112326216-a084ed00-8cb4-11eb-8da5-47225e89872e.png)
![Screenshot 2021-03-24 at 15 22 29](https://user-images.githubusercontent.com/17233829/112326383-c4e0c980-8cb4-11eb-98b2-05859f0de10e.png)

**Describe the solution you'd like**
I suggest to add a page selector in a drop down or a field to enter the page's number.

**Comment by Soliine** [comment]
It would also be great to have the clickable total number of pages at the end of the selector.

**Comment by madoleary** [comment]
Currently using this for inspiration : https://dribbble.com/shots/9553069-Pagination-Day-85
