### ISSUE TITLE
Facial/Photo recognition feature

### ISSUE THREAD

**Issue by kaerumy** [ICIJ/datashare#784]
**Is your feature request related to a problem? Please describe.**

No. 

**Describe the solution you'd like**

A lot of documents/images contain photos either as part of a report document, publicity materials or photo id. It would be good for datashare to also have a detect faces and a search tag, and have ability to upload a face photo to be matched against documents that are likely matches.

**Describe alternatives you've considered**

* Writing custom scripts using existing open source python facial matching libraries for folder of documents.
* Writing scripts to detect faces and extract images, and import images into photo management tools with facial recognition

**Additional context**

Some use cases here, but using Google Photos https://medium.com/@kaerumy/using-google-photos-facial-recognition-feature-for-investigations-7e24149b06e6

**Comment by Soliine** [comment]
Hi! Thanks a lof for this suggestion that I put in our backlog so we can see what we could do in this area.
