### ISSUE TITLE
Sign Datashare exe for Windows

### ISSUE THREAD

**Issue by doanviettrung** [ICIJ/datashare#788]
SentinelOne (Static ML) and Static AI engines said that the downloaded file was suspicious.

Then, when I tried to run the .exe, Windows 10 advised not to run. I ran anyway, and Windows said publisher was unknown

**Comment by bamthomas** [comment]
we don't have a MS certificate for the app (like we did for Apple) that maybe explains the message

**Comment by Soliine** [comment]
We should sign our app for Windows as we did for Mac.

**Comment by pirhoo** [comment]
After careful consideration, we decided not to buy a certificate to sign Datashare on Windows. As a free and open source software, we don't want to engage in fee-based signature processes at the moment.
