### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by jasonbrown1965** [ICIJ/datashare#79]
Probably missed it somewhere, but no mention in the news release about this being open source?

**Comment by Soliine** [comment]
Hello Jason,
I am not sure which news release you are mentioning. On https://datashare.icij.org/, it is mentioned three times that Datashare is an open-source project. Please let us know if you talk about another news release.
Thank you for your interest in Datashare.
Best regards,
ICIJ Datashare team

**Comment by jasonbrown1965** [comment]
Heya, came to it through the newsletter which had a link to this page https://www.icij.org/blog/2019/02/datashare-help-test-and-improve-our-latest-journalism-tool/

As you'll see there is no mention there or from what i could see on git either
________________________________

**Comment by bamthomas** [comment]
Hello @jasonbrown1965 thank you for your message. Yes maybe we could have emphasized more in the article that the project is opensource. 

However, the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.html) is set on this repository, and we try to keep issues here related to defects in the code. So I'm closing this issue. If you want to discuss more about this, please react on the article.

Thank you,
Bruno Thomas

**Comment by jasonbrown1965** [comment]
Thanks Bruno, and no dispute with the closure, just that article comments e.g. via Facebook, no longer appear, hence my posting here. All good!
