### ISSUE TITLE
First search in batch searches makes Datashare starts again

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#790]
**To Reproduce**
1. Go to https://datashare-demo.icij.org/#/batch-search
2. Search anything in the search bar for the first time
3. See Datashare is restarting. It doesn't happen the next times we search.

**Expected behavior**
We expect Datashare not to start on the first time we search in Batch Searches.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 9.7.2

**Comment by mvanzalu** [comment]
Cannot reproduce on Datashare 9.10.3
