### ISSUE TITLE
Created-at filter : not correctly filtering results

### ISSUE THREAD

**Issue by madoleary** [ICIJ/datashare#794]
**Describe the bug**
The 'created at' filter is displaying results that do not conform to the filter.

**To Reproduce**
1. Choose a date by which to filter results
2. Inspect the creation dates of several different results to see that the filter is not being respected

**Expected behavior**
The results should respect the filter

**Comment by bamthomas** [comment]
the creation date is read from metadata of different file parsers, that could explain that it is not always of the same format

**Comment by bamthomas** [comment]
see also #380
