### ISSUE TITLE
Insights: documents count cannot except 10k

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#796]
**Describe the bug**

Since the migration to Elasticsearch 7, the documents count is limited to 10k. This is due to a new option:

https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-track-total-hits

**To Reproduce**
1. Index more than 10k document
2. Go to the "insights" page
3. Check the "number of documents" and "number of duplicates" widgets

**Expected behavior**

Insights widgets should display the correct number of documents.

**Screenshots**

![Screenshot_2021-05-07 Insights - Datashare(1)](https://user-images.githubusercontent.com/471176/117472488-3a4ce480-af59-11eb-8d51-104512c59731.png)
![Screenshot_2021-05-07 Insights - Datashare](https://user-images.githubusercontent.com/471176/117472492-3ae57b00-af59-11eb-9f89-b340a39cf61d.png)

**Comment by madoleary** [comment]
https://github.com/ICIJ/datashare-client/commit/c2818a5e556f35752cbbd3ad92f0dbdfaf1679ee
