### ISSUE TITLE
Do not add defaultProject if it is not in the users project list

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#799]
**Describe the bug**

Datashare has a defaultProjet setting.
In server mode, users have projects they can access data.
If the defaultProject setting is not in the project list, it should not be used as default value.

**To Reproduce**
1. launch datashare in server mode with a defaultProject set to "default" 
2. provision a user with "MyProject" in its project list
3. log in the user and click on the "MyProject" index 
4. in the dropdown you should see 2 projects : "MyProject" and "default"

**Expected behavior**

A user that is not granted for the default project should not see it in the dropdown

**Comment by madoleary** [comment]
https://github.com/ICIJ/datashare-client/commit/870f7954e4a07bd4f7fa44aa88cba9be903c59a2

**Comment by madoleary** [comment]
fixes filtration of projects in dropdown : https://github.com/ICIJ/datashare-client/commit/9e4e89d9b7c603432fe17d3c588e3c18a6c6ca26
