### ISSUE TITLE
Performance : avoid  /api/index/all ajax call

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#80]
refactor : move indices endpoint to config
The indices available for a user are given by `/api/index/all`

We want to move `/config` to `/api/config` authenticated name space, and include user's indices.

**Comment by annelhote** [comment]
Let's complete this task :
- [ ]  Move the `/config` endpoint `/api/config`
- [ ] Include the user's indices to `/config`
- [ ] In SERVER mode, don't return "user-datashare" as an available indice
- [ ] In SERVER mode, on the interface, hide the actions menu ("Analyze documents" and "How to add documents")
