### ISSUE TITLE
Problem Completing Tasks

### ISSUE THREAD

**Issue by scunder** [ICIJ/datashare#800]
The "Extract Text" and "Find People..." tasks are running very slowly.  They either never reach 100% or reach 100% with an error message.

Any suggestions?

Thanks

**Comment by Soliine** [comment]
Hello, it all depends on the documents you are trying to analyze. It can take several hours or even weeks if the documents are long, scanned (in that case, OCR can take a long time), handwritten, in certain languages, with columns, etc. You can have a look at how Apache Tika and Tesseract OCR work as they are the text extracting open-source technologies used by Datashare, and it is the same for the NLP pipeline used by Datashare, which is CoreNLP.
