### ISSUE TITLE
[Local] Change text in "Find people etc" window

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#801]
**Is your feature request related to a problem? Please describe.**
In local Datashare, we have changed the 'Find people, organizations, locations' window over the time and it doesn't make sense anymore:
<img width="512" alt="Screenshot 2021-05-27 at 11 29 54" src="https://user-images.githubusercontent.com/17233829/119802574-f22d3c00-bede-11eb-983e-f4e7ca23c42f.png">

**Describe the solution you'd like**
I suggest to replace:
- "Which technology do you want to apply in order to find people, organizations and locations?" by "What would you like to do?"
- "Datashare uses Natural Language Processing models. Please choose one of them:" by "Datashare uses Natural Language Processing models."

And:

- Email 
- Corenlp _By default - Offers the highest probability of working in most documents_

...by:

- Find email addresses
- Find people, organizations and locations with Corenlp _By default - Offers the highest probability of working in most documents_

In the plugins for other NLP models, we can also adopt the model "Find people, organizations and locations with [name of the model]"

**Comment by madoleary** [comment]
https://github.com/ICIJ/datashare-client/commit/86f831225dfc4a81fa6eeb4b6a2c8cbb657de179
