### ISSUE TITLE
Batch download (UI): create 'Tasks' page to access batch searches, analysis and downloads

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#808]
**Is your feature request related to a problem? Please describe.**
Access the Downloads page.

**Describe the solution you'd like**
The Tasks page will have 3 tabs:
- Batch searches _(first by default)_
- Document analysis
- Downloads

(The Tasks page will have its own entry in the left column menu which will replace the current Batch Searches entry)

In the #804 epic.

**Comment by bamthomas** [comment]
part of the #804  epic
