### ISSUE TITLE
batch download documents

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#809]
**Is your feature request related to a problem? Please describe.**

I would like to download documents in an archive file from a search request.

**Describe the solution you'd like**

I'd like to : 
1. make a request on datashare
2. being able to create a background task that creates an archive file
3. then download this archive

**Additional context**

To avoid creating load  by these tasks in datashare server, we will delegate to another process the archive creation.
It could be made with a similar code as the batch runner.

This story is part of #804 epic

**Comment by bamthomas** [comment]
the creation API will take the following parameters : 
- name of the download file
- ES request body or string query
- expiration date
- user

**Comment by bamthomas** [comment]
As this issue is quite big, here are the tasks that needs to be done : 

[] back: do not interrupt zip creation  when there is an error accessing/extracting file
[] back: add the zip remover 
[] back: add a download backend url to download zips (:warning: security issues)
[] back: add the server mode (listen on a redis queue)
[] all: add the ansible deploy role/playbook update
[] front: display toaster when clicking on the download button with a link on the downloads
[] front: display BatchDownloadRunner tasks in the batch download task tab
[] front: add the download button in the download task when task is done

**Comment by madoleary** [comment]
https://github.com/ICIJ/datashare-client/commit/e5cd4ac107100335db29c1636b3604b4999251bc builds out the ajax request test for SearchResultHeader.spec download button + batch download service (sorry, I did not reference the issue correctly in the commit message!)

**Comment by bamthomas** [comment]
here are explanations about the diff between batchsearch and batchdownload sequence

![datashare-batch](https://user-images.githubusercontent.com/551723/127887600-422120d9-b4ac-49ec-b03e-980ac32f6b16.png)
