### ISSUE TITLE
Batch Download (UI): create a Downloads page

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#812]
We'll access the Downloads page by clicking the corresponding tab in [the 'Tasks' page](https://github.com/ICIJ/datashare/issues/808).

The download page should contain at least:
- the name of the current download
- the size of the current download
- the day and hour of the current download
- the URL of query which led to the current download

In the #804 epic.

**Comment by mvanzalu** [comment]
Clarification : 
- size is the total size of the documents (and not the size of the archive)
- name of the download and the number of documents are not needed

**Comment by Soliine** [comment]
At the moment, when we add a new download, it is on top of the list while it is loading but when it is finished, it goes at the bottom of the list. 
I suggest we always have most recent to less recent as the order of the archives' list.

**Comment by mvanzalu** [comment]
- [ ] Display size of total documents
