### ISSUE TITLE
Indexing documents: whitelist for metadata fields

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#818]
While indexing documents, Datashare should use a whitelist to ensure not every fields extracted from tika are indexed. This should improve performances and avoid changing the `max_clause_count` on Elasticsearch.

We need to build that list first.

This apart of https://github.com/ICIJ/datashare/issues/727

**Comment by pirhoo** [comment]
Instead of squashing values, we decided to use the `index.query.default_field` setting to explicetly target only a limited number of fields: 

```
content
content_translated
metadata.tika_metadata_author
metadata.tika_metadata_creator
metadata.tika_metadata_dc_creator
metadata.tika_metadata_dc_title
metadata.tika_metadata_message_from
metadata.tika_metadata_message_to
metadata.tika_metadata_meta_author
metadata.tika_metadata_subject
metadata.tika_metadata_title
name
path
tags
```

This setting should be set when an index is created.

**Comment by bamthomas** [comment]
it seems it has not been implemented

**Comment by pirhoo** [comment]
This should fix https://github.com/ICIJ/datashare/issues/886
