### ISSUE TITLE
Browsers' "previous" on filtered batch searches: keep the searched terms

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#829]
**Is your feature request related to a problem? Please describe.**
1. Go to https://datashare-demo.icij.org/#/tasks/batch-search
2. Search for a term in the batch searches
3. Open a batch search
4. Click "Previous" on your browser
5. See issue: the batch searches are still filtered but the search term doesn't appear in the search bar

**Describe the solution you'd like**
Show the search terms in the search bar

**Comment by madoleary** [comment]
2ba956de5bc655a7f80ce2ad5b007793e5c4e178

**Comment by madoleary** [comment]
commit: https://github.com/ICIJ/datashare-client/commit/57fe9bf2f55da36d7fc4bb444a4c5b7f59370a16
