### ISSUE TITLE
Possible incorrect document scanning and indexing

### ISSUE THREAD

**Issue by adieyal** [ICIJ/datashare#834]
**Describe the bug**
I am in the process of setting up a server instance of Datashare. According to the [documentation](https://github.com/ICIJ/datashare/wiki/Datashare-Server-Mode#processing-data), the following command will start a scan:
```
docker run -ti -v host/data/path:datashare/container/path ICIJ/datashare:version --mode CLI
    -s SCAN
    -d datashare/container/path
    --redisAddress {{ ds_reddis_url }}
    --queueName {{ ds_queue_name }}
```

This returns a null pointer exception on this line: https://github.com/ICIJ/datashare/blob/806eca71deb4d28b450372c805c102f4b38f77c6/datashare-app/src/main/java/org/icij/datashare/PipelineHelper.java#L18

I suspect that `-s` should change to `--stages`

**Comment by mvanzalu** [comment]
Hello @adieyal, indeed -s should be changed to --stages.

**Comment by mvanzalu** [comment]
Hello @adieyal,

Indeed -s should be changed to --stages, to was used before for the latter but now it's tied to --settings option
