### ISSUE TITLE
Display of extracted text removes part of the original document

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#835]
**Describe the bug**

We searched a term in datashare. A list of matching documents were returned.
When looking at the displayed text from a matched document in the "Extracted text" tab, there was no occurrences of the term that has been found previously.
When looking at the text in elasticsearch, the term was there.

**To Reproduce**

See the message of @Soliine 21st of July (today) at 14:48 on the support channel.

**Expected behavior**

The original text should be displayed

**Comment by pirhoo** [comment]
Is it still the case? We completely rebuild the display of the extracted text since 2021.

**Comment by mvanzalu** [comment]
Seems to be fixed so far
