### ISSUE TITLE
Doesn't start on Windows 10 Docker 

### ISSUE THREAD

**Issue by ivbeg** [ICIJ/datashare#845]
**Describe the bug**
I've installed laters 9.20.1 docker installer and installed it on Windows 10 with Docker . After installation two containers are running but datashare_elasticsearch_1 container continiously stops and restarts. Datashare website isn't starting as result
Docker version 3.6.0, uses WSL2 based engine

**To Reproduce**
1. Go to 'datashare.icij.org'
2. Download version  9.20.1 docker installer for Windows
3. Install it
4. After installation container "datashare_elasticsearch_1" stop and restart continiously

**Expected behavior**
Software is installed, running and website works.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: e.g. Chrome, Safari
 - Version: 9.20.1
 - Docker: 3.6.0, WS2 Engine

**Additional context**

**(Optional) Your contact, availabilities and timezone if a video call with screensharing is needed**
GMT+3 (MSK) timezone

**Comment by ivbeg** [comment]
[elasticsearch.zip](https://github.com/ICIJ/datashare/files/7276361/elasticsearch.zip)
Log file from elasticsearch container

**Comment by mvanzalu** [comment]
Can't reproduce with Docker Desktop 4.1.0 and WSL2
@ivbeg are your running W10 Home or W10 Pro ?

**Comment by ivbeg** [comment]
@mvanzalu I am running Windows 10 Pro version 21H1. 
I've updated docker up to 4.0.1 version, but error is the same.

**Comment by pirhoo** [comment]
Closing due inactivity.
