### ISSUE TITLE
Scan Task not working

### ISSUE THREAD

**Issue by turkeyphant** [ICIJ/datashare#849]
**Describe the bug**
My OCR Scan Task marks as "DONE" but there's no text extracted by OCR.

**To Reproduce**
1. Go to Tasks
2. Click on Analyze Your Documents, Extract Text
3. Check "Do you want to extract text also from images and PDFs?"
4. Go to Search as open an image file to see no preview text

**Expected behavior**
Text extracted from images and searchable

**Screenshots**
![image](https://user-images.githubusercontent.com/8129583/137717973-7e3c4e79-4c51-4658-815c-8903740142db.png)
![Screenshot 2021-10-18 11 54 16](https://user-images.githubusercontent.com/8129583/137717927-9761784f-8072-49d1-8276-85257c60c2df.png)
![Screenshot 2021-10-18 11 54 22](https://user-images.githubusercontent.com/8129583/137717931-11a12736-a7f5-459b-8ac8-b0395c2289ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 9.20.3

**Comment by pirhoo** [comment]
Is this bug still occurring?
