### ISSUE TITLE
Download encryption: I am asked for password as early as I open the zip

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#856]
As seen with Bruno, let's see 2 things:
- what it takes to ask for password as early as I open the zip (at the zip's level, not at the documents' level. The goal is to also protect the paths and documents' names)
- if it is possible, if we ask for the password also at the documents' level ie each time users opens each document of the zip file

**Comment by bamthomas** [comment]
It seems that zip encryption doesn't work that way : the zip file is not encrypted but individual zipped files are ciphered.

There is a workaround : double zip

1. the filesystem is zipped not encrypted in a zip file
2. then the zip is zipped in a wrapped zip that is encrypted

see https://support.winzip.com/hc/en-us/articles/115011613067-Filenames-display-without-entering-the-password-when-an-encrypted-Zip-file-is-opened
