### ISSUE TITLE
Doesn't launch on Mac BigSur embedded ES

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#858]
**Describe the bug**
Installation works but when I launch Datashare, it can't open because of an error (see attached report). I have Homebrew. I am using MacBigSur version 11.4 and Datashare's latest version is 9.23.0.

**To Reproduce**
1. Download version 9.23.0 embedded ES for Mac
2. Install it
3. After installation, launch Datashare 

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Mac BigSur version 11.4 
 - Datashare: version 9.23.0.

**Additional context**
Might be related to #845 

[crash_report_datashare_ 9.23.0_macbigsur_21_11_09.txt](https://github.com/ICIJ/datashare/files/7506551/crash_report_datashare_.9.23.0_macbigsur_21_11_09.txt)

**Comment by bamthomas** [comment]
hypothesis : it is an old index read by an updated version of ES engine
I asked to remove `/Users/<username>/Library/Datashare/index`

then to reload

**Comment by Soliine** [comment]
It worked!

**Comment by bamthomas** [comment]
TODO: add a log when starting datashare to display a more explicit message telling that the version of index files is not correct and a workaround is to remove the old index (or migrate it)
