### ISSUE TITLE
Batch download doesn't work on demo

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#860]
**Describe the bug**
Batch Download doesn't work on demo, it's possible launch a batch download but it stays on _RUNNING_ state.

**Expected behavior**
The launched batch download is expected to be _DONE_ and be downloadable.

**Screenshots**
![image](https://user-images.githubusercontent.com/35509100/142597909-39560b1d-02ab-4da5-84de-de0a4416f982.png)

**Comment by bamthomas** [comment]
batch download daemon is not deployed on demo
there is datashare-demo_batch_search_1 but no instance for batch_download.

In serverMode taskManager is bound to RedisInstance :

```
bind(TaskManager.class).toInstance(new TaskManagerRedis(propertiesProvider, getBlockingQueue(propertiesProvider, batchQueueType, "ds:batchdownload:queue")));
```
So we need to run a batch download instance
