### ISSUE TITLE
upgrade ES client library to 7.17.7

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#864]
**Is your feature request related to a problem? Please describe.**
To follow the upgrades of the ES backend server we need to upgrade the client library

**Describe the solution you'd like**
upgrade ES libs in pom.xml

**Comment by mvanzalu** [comment]
[Reverted](https://github.com/ICIJ/datashare/pull/961) for now, opensearch isn't compatible with ES client > 7.10
