### ISSUE TITLE
As a user, I want to be able to perform a simple search on several project

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#867]
**Describe the solution you'd like**

From the main search bar and the filter panel, I want to be able to select several projects instead of just one.

**Additional context**

Only the server version of Datashare is multi-project (and multi-tenant).

**Comment by mvanzalu** [comment]
- [ x] Adapt the API proxy to allow multiple indices
- [ x] Adapt the frontend to be multi project
- [ ] Add a relationship table in the database for saved searches
- [ ] Adapt batch download to be multi project
