### ISSUE TITLE
Add a 'all' in Project's filter

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#876]
**Is your feature request related to a problem? Please describe.**
If I'd like to search in all projects, I need to tick all the checkboxes one by one in the Project filter.

**Describe the solution you'd like**
Add a 'All' button. We don't tick 'All' by default like in other filters and we keep the selected project as it is.

**Comment by pirhoo** [comment]
We need to gather feedbacks from users to know if they tend to check all projects in the filter.
