### ISSUE TITLE
Add a (personal) trash filter

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#877]
Design and tech solution not done yet

**Comment by wagnerpaul** [comment]
Would this be a true "trash" in that it would/could be deleted from the dataset at some point?  Perhaps its just another specialized tag like the "star" tag?  If its the latter then a conceptual model similar to eDiscovery software of "culling" might be appropriate and recognizable.  Several systems I've worked with use this term and its essentially just a special tag applied to  "culled" items and are excluded from all queries.  If a user wishes to see culled items and inclued them back in the data set they can toggle this behavior to see all the culled items and un-cull them.

**Comment by pirhoo** [comment]
Yep, that's the idea @wagnerpaul! We are not sure yet about the terminology tho. In that issue we used the term "trash" as it's the one used in user feedbacks :)
