### ISSUE TITLE
Tasks not performed

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#880]
**Describe the bug**
When launching text extraction and email addresses extraction, the front in "Tasks > Analyze your documents" says the tasks are completed and successful but there is no document in "Search".

**Screenshots**
![IMG_2197](https://user-images.githubusercontent.com/17233829/160865564-319021fd-e797-4886-b8b6-22c99a24b17d.jpg)

**Desktop:**
 - OS: iOS Mojave 10.14.6
 - Browser: Chrome

**Comment by mvanzalu** [comment]
Couldn't reproduce on Datashare 10.5.0 / iOS Mojave 10.14.4
