### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by randolphgow** [ICIJ/datashare#883]
I have set-up DataShare server via Docker. However, when I try and log-out via the logout button, I get the fiollowing screeen:

**To Reproduce**
1. Login to data share server using a username and password
2. Click on Logout

**Expected behavior**
A window should come up asking for credentials. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3090126/162463128-2ef5a97f-8618-412f-adb8-c4d8f786662f.png)

**Desktop:**
 - OS: e.g. WINDOWS
 - Browser: e.g. Chrome, Edge
 - Version: e.g. Version 100.0.1185.29

**Comment by randolphgow** [comment]
> Hello @randolphgow, do you still experience this issue ?

Yes. I just tested it with version 10.13.0 The same issue still exists with the server version. Once a user logsout he gets the page not found error

**Comment by pirhoo** [comment]
To create the user, did you use redis + basic auth?

**Comment by randolphgow** [comment]
Yes. The users are created in redis. No other settings were configured. We followed the manual for basic auth.

**Comment by caro3801** [comment]
Hello @randolphgow 
The standard behavior of basic auth does not provide log out feature. The session will remain until the browser is closed or the browser's data is cleaned (ctrl+shift+del)
Thanks to your feedback we will plan to enhance our UX/UI to prevent seeing a 404 page on "signout" in basic auth mode.
