### ISSUE TITLE
Datashare http server is frozen

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#890]
**Describe the bug**

After random period of time, datashare server seems to be frozen : the HTTP port is open but it doesn't answer.

**To Reproduce**

Not sure how to reproduce. It maybe a pool saturated (for example requests to elasticsearch ?).

**Expected behavior**

That datashare server keeps responding to requests.

**Comment by pirhoo** [comment]
We did not observed this behavior since it was reported. Closing.
