### ISSUE TITLE
Create a paginated API endpoint for document's extracted text 

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#894]
### Create a paginated API endpoint for document's extracted text in order to slice text content.
> Related to Lazy load paginated Extracted Text #767 

* Currently the extracted text is available through this request 
curl -XGET -H 'Content-Type: application/json' http://localhost:8080/api/index/search/:indexName/_doc/:docId | jq ._source.content

- create endpoint /api/index/search/:indexName/_doc/:docId/content?type=character&limit=300&page=1
- parameters:
  - paging_type: (character/sentence/paragraph/page)
  - limit : default 300
  - page: default 1

- back end returns JSON:
  - (sliced) content: " ..."
  - content_length: 300
  - number_of_characters:300
  - number_of_paragraphs:10
  - number_of_pages:1
  - paging_type:"characters"
  - page: 1
  - number_of_pages: 20

**Comment by pirhoo** [comment]
Maybe "words" instead of sentence for the paging type?

**Comment by caro3801** [comment]
We are using the search API of elastic search with a (painless) script to execute the substring while the search is running.
The script is passed as a payload in the GET search request. 
Since DS GET request does not support payload we use the documentsResource endpoint as a proxy to hide the script payload.
* The DS API endpoint is on document with this URL  
` /api/:indexName/documents/content/:docId?offset=0&limit=4`

and returns 200 with a JSON
```
{
  maxOffset: 12,
  offset: 0,
  limit: 4,
  content:'test'
}
```
* out of range limit or offset returns HTTP 400
* and docId not found returns HTTP 404

#### Improvement: 
add a *unit* parameter (character, word, paragraph, page) . Currently the unit is character, based on the original content string.
