### ISSUE TITLE
Filter batch search results by project in multiproject batch search

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#898]
**Is your feature request related to a problem? Please describe.**

When a user is looking at the results of a batch search in multiproject batch search it would be convenient to filter by project.

**Describe the solution you'd like**

I would like to filter (for exmaple with a dropdown in the header) by or sort (with a new column) by project the results of a batch search.

**Describe alternatives you've considered**

**Additional context**

There is no database index for now on the prj_id column. This feature would need one, else the results could be very slow to compute.

**Comment by mvanzalu** [comment]
So far we added the column when a Batch Search is multiproject, we are able to sort by projects.
About the filter feature, we have to decide if we integrate it to the component in the issue #912

**Comment by pirhoo** [comment]
This was done in #912
