### ISSUE TITLE
When updating Docker, Elastic volume seems gone?

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare#90]
So I just updated Docker on my Debian Stretch machine and I noticed that Docker is kinda eager to get rid of any volumes after that. I had a bunch of OCR information in the search engine that was gone after restarting through ./datashare.sh.

However, I'm not sure if this is typical Docker behavior? My knowledge doesn't go deep enough to provide you with an answer to this.

If this is standard docker behavior, this might be good to add as a warning in the Documentation?

How-to reproduce:

- Have OCR job running (I was on 1.44, but data didn't come back after downloading the 1.45 datashare.sh script)
- Update Docker
- Docker kills the containers and doesn't restart it.
- Docker seems to throw away the Elastic volume.

Happy to answer any additional questions if they arise.

Thanks :heart:

**Comment by bamthomas** [comment]
could this be related to https://github.com/docker/for-mac/issues/1175 ?

for now we are not mounting persistent storage for ES indices. I wonder if mounting a volume for ES could change this behavior.

**Comment by DrWhax** [comment]
@bamthomas Not sure, it's not a Mac i'm trying this on. But same thing happens, after an upgrade, all docker images are gone. Probably more a Docker problem than a Datashare problem.

**Comment by RickBahague** [comment]
I updated to 2.1.0.0 on mac, all images gone after.

**Comment by bamthomas** [comment]
I've tested with windows 10pro, macOS 10.14 Mojave :

* running datashare and indexing files/NE recognition
* reinstalling docker desktop
* re-run datashare and see that the index is still here

**Comment by DrWhax** [comment]
Solved this for me as well. Awesome!
