### ISSUE TITLE
make SERVER mode run with memory and OAuth

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#902]
**Is your feature request related to a problem? Please describe.**

Datashare cannot be launched in server mode without a Redis instance, even when specifying `memory` as `busType` and `queueType` with users provieded by oauth identity provider.

This is because the sessions are stored in Redis.

**Describe the solution you'd like**

That could be convenient to make SERVER/LOCAL mode _orthogonal_ to Redis/Memory.

There are 2 services that are hard coded with Redis: 
```
bind(SessionIdStore.class).to(RedisSessionIdStore.class);
bind(TaskManager.class).toInstance(new TaskManagerRedis(propertiesProvider, getBlockingQueue(propertiesProvider, batchQueueType, "ds:batchdownload:queue")));
```

**Comment by pirhoo** [comment]
@bamthomas can you confirm this is not the case anymore?

**Comment by bamthomas** [comment]
Yes it is fixed
