### ISSUE TITLE
Chrome: no space between pasted named entities

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#906]
**To Reproduce**
1. With Chrome, go to https://datashare-demo.icij.org/#/d/luxleaks/a5f7e8b86a13505d52de7bdfb29d2c8071e1c6117f16fd573896deee62104c8fdbdd3d3314ff165fa6b89a241c593ea9/a5f7e8b86a13505d52de7bdfb29d2c8071e1c6117f16fd573896deee62104c8fdbdd3d3314ff165fa6b89a241c593ea9?q=%2a
2. Go to the Named Entities tab
3. Copy the named entities for Organizations (for instance) and paste them in a text editor
4. See error: the spaces between the pasted named entities does not appear in the pasted text:
<img width="468" alt="Screenshot 2022-05-31 at 16 10 53" src="https://user-images.githubusercontent.com/17233829/171194025-26831a3d-1eb3-4f88-bd8c-72aea8b23cf9.png">

**Expected behavior**
There should be spaces between the named entities. It is useful to then use the named entities.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version of Datashare: 10.3.1

**Comment by pirhoo** [comment]
Should be fixed in the next release. We also added a new user story: https://github.com/ICIJ/datashare/issues/937
