### ISSUE TITLE
Add a desktop client that can be used for data import [SERVER]

### ISSUE THREAD

**Issue by yakomisar** [ICIJ/datashare#907]
Currently, data import can only be accomplished via a docker-containers using CLI, which is not user-friendly and difficult to manage. Adding desktop client for data import purposes will enable investigators to easily upload data and start a new cases and/or enrich data for ongoing investigations.
### Please use the following screenshots as an example:
![import](https://user-images.githubusercontent.com/20434122/171198239-9c47debf-7298-4e24-ab6c-4b3c403701d2.png)
![Untitled picture](https://user-images.githubusercontent.com/20434122/171198592-b736542f-6d84-4d7b-9c8c-599b8f9900e9.png)

**Comment by Soliine** [comment]
Thanks for the great suggestion! On Datashare server mode, we have to build an admin mode to display features related to the server. At the moment, it cannot be in our priorities so I move this ticket to our legacy taskboard and we'll keep you updated when we have time to build this.

**Comment by JCBerger** [comment]
Is this why I can never analyze any of the documents placed in the folder for analyzing?

**Comment by mvanzalu** [comment]
@JCBerger if you're running Datashare on server mode, this is the reason why that you can't see "Analyze your Documents" tab
