### ISSUE TITLE
Bugs when performing proximity searches using the * operator

### ISSUE THREAD

**Issue by randolphgow** [ICIJ/datashare#915]
In DataShare when searching using the * operator, I have noted two bugs:

1. If the search term begins with the * operator then the content of "Extracted Text" for each item will be empty even though the content will show up if the search is cleared.
![image](https://user-images.githubusercontent.com/3090126/175986081-9a8ec469-f4ad-487f-811d-6a1e9e6539f6.png)

3. If the search term ends or begins with the * operator, then "In this document" section shows that there are zero results
![image](https://user-images.githubusercontent.com/3090126/175985717-6a7acad4-2680-46e7-b74a-558d7702cce3.png)

1. Go to 'Search'
2. Type "*hello" or "hello*"
4. Search filter: Content
5. Click on 'Search'
6. Select any resulting item and click it

Expected behavior
1. If the * operator is used to begin a search, then the the extracted text should show up for every item
2. If the * operator is used at all, then it should show in the "In this document" section, the exact number of items it was able to find a given keyword.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome,
 - DataShare Server Version: e.g. 10.5.1

**Comment by pirhoo** [comment]
Not valid: we don't support regex/wildcard in local text search anymore.

**Comment by randolphgow** [comment]
> Not valid: we don't support regex/wildcard in local text search anymore.

Since what version?

**Comment by pirhoo** [comment]
Since version [10.9.0](https://github.com/ICIJ/datashare/releases/tag/10.9.0). We reviewed entirely the way we load the text content of each document to be able to handle huge file. That requires to handle the local search on the back-end through ElastiSearch with painless scripts. Unfortunetly ElasticSearch doesn't enable Regex bu default in painless scripts and many hosting providers (including AWS OpenSearch) forbid it.

**Comment by randolphgow** [comment]
> Since version [10.9.0](https://github.com/ICIJ/datashare/releases/tag/10.9.0). We reviewed entirely the way we load the text content of each document to be able to handle huge files. That requires to handle the local search on the back-end through ElastiSearch with painless scripts. Unfortunetly ElasticSearch doesn't enable Regex bu default in painless scripts and many hosting providers (including AWS OpenSearch) forbid it.

I understand this. However, what i am referring to is the use of wild cards, in this case the * sign, or are you saying that we can perform simple word searching now without using wild cards and logical operators (AND or OR).

**Comment by pirhoo** [comment]
In theory yes, you don't need any extract wildcard to search into the local text content.

**Comment by randolphgow** [comment]
But what if we want to use wildcards such as (*) we still get the error i described above.
