### ISSUE TITLE
Batch search - Number of fields error

### ISSUE THREAD

**Issue by randolphgow** [ICIJ/datashare#916]
When performing a batch search, we encountered an issue relating to the number of fields that can be used during a search in ElasticSearch. 
The following error is displayed:
`error:Object`
`root_cause:Array[1]`
`0:Object`
`type:"query_shard_exception"`
`reason:"failed to create query: field expansion for [*] matches too many fields, limit: 1024, got: 6504"`

**To Reproduce**
1. Create a batch search
2. Run a batch search 

**Expected behavior**
Either there should be a way to lift the limitation and search on all columns, which is obviously not desirable. The best solution here is to allow a user to specify the columns that should be search, or at least add an option to search only the Content field, which is the most common field being searched. 

**Desktop**
 - OS: e.g. Linux
 - Browser: Chrome
 - DataShare Server Version: 10.5.1

**Comment by mvanzalu** [comment]
Hi @randolphgow, you seem to have a similar issue raised in the post [here](https://github.com/ICIJ/datashare/issues/897#issuecomment-1160412556). You can try the solution proposed in the reply.
