### ISSUE TITLE
Cannot get Datashare working. 

### ISSUE THREAD

**Issue by sqleonheart** [ICIJ/datashare#917]
Good day everyone.
I'm having some issues, I believe it's some IBM issue ( idiot behind machine ). I cannot get Datashare to work at all. I've searched for methods and re-installed multiple times but I just cannot get it working. The Application runs as it should, I can access it via the web browser but it's not indexing and doesn't matter if I run it as root, normal user and even on Windows, I get the same errors the entire time.

Steps to reproduce:
While the application is running, navigate to Analyze your Documents, it does not index.

I've tried running it on both Linux and Windows:
 - OS: Ubuntu Server 20.04 LTS & Windows 10 Pro
 - Browser: Opera & Google Chrome

[Datashare Log.txt](https://github.com/ICIJ/datashare/files/8999934/Datashare.Log.txt)

If anyone is able to help point out the mistake I'm making, it will be greatly appreciated.

**Comment by mvanzalu** [comment]
Hello @sqleonheart,

Sorry for the late answer, this issue has been fixed the version 10.7.2
