### ISSUE TITLE
Indexing only new documents in server mode

### ISSUE THREAD

**Issue by erikkri** [ICIJ/datashare#920]
Is it possible to index only new documents in server mode?
The documentation for server mode says you should SCAN, and then INDEX, but it seems to re-index everything.

**Comment by loganwilliams** [comment]
@erikkri Did you figure out a resolution for this? I'm in the same situation.

**Comment by pirhoo** [comment]
The `SCAN` stage will queue everything regardless of existing documents, but the `INDEX` stage will skip any documents already indexed as long as they are in the report map in Redis.

So if I'm not mistaken, both in local and server mode, Datashare will skip existing documents by default (the SCAN populating the queue with everything might be confusing tho).
