### ISSUE TITLE
IllegalStateException: Queue full

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#921]
**Describe the bug**
When indexing locally with a memory [BlockingQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html) we have an exception `IllegalStateException: Queue full`.

**To Reproduce**

It is a bug observed by a user with : 

> 40.3K documents, among which 20.8K on disk and 35.65 GB of disk usage.

**Expected behavior**

Do not have the error.

**Desktop (please complete the following information):**

- Intel Xeon E5-2630 16 cores, 32 GB RAM.
- OS: Ubuntu 20.04 LTS

**Comment by bamthomas** [comment]
with a blocking queue, the capacity is 0. That means that if there is no consumer, then the queue is full even with 1 item.

https://stackoverflow.com/questions/9151871/queue-full-on-depth-of-the-blocking-queue-clarification-needed

What is weird is that we are using an [`ArrayBlockingQueue<Path>`](https://github.com/ICIJ/extract/blob/master/extract-lib/src/main/java/org/icij/extract/queue/MemoryDocumentQueue.java) with an initial capacity of 1024.

Does that mean that the consumer(s) are going slower than the production and that the queue is full ?
I'm going to do some tests.

**Comment by bamthomas** [comment]
I'm trying to reproduce. I have 17479 MP3 files / 82GB

**Comment by marieglr** [comment]
Another user encountered this error when trying to scan PDFs for OCR (email on 23/09): 
![image](https://user-images.githubusercontent.com/39140360/192472025-36f461b1-84c9-4370-be85-9e8f94be0c6c.png)
