### ISSUE TITLE
Names in facets are not internationalized

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#93]
How to reproduce:
- go to the French or Spanish version
- in the filter facets, the names of files, of languages and of extraction level remains in English

**Comment by annelhote** [comment]
- [ ] Files name
- [ ] Languages
- [ ] Extraction level

**Comment by annelhote** [comment]
@Soliine here is the list of the languages detected by the Backend. Could we plan to find a translation for all of these ?
ABKHAZIAN
AFAR
AFRIKAANS
AKAN
ALBANIAN
AMHARIC
ARABIC
ARAGONESE
ARMENIAN
ASSAMESE
AVARIC
AVESTAN
AYMARA
AZERBAIJANI
BAMBARA
BASHKIR
BASQUE
BELARUSIAN
BENGALI
BIHARI
BISLAMA
BOSNIAN
BRETON
BULGARIAN
BURMESE
CATALAN
CHAMORRO
CHECHEN
CHICHEWA
CHINESE
CHUVASH
CORNISH
CORSICAN
CREE
CROATIAN
CZECH
DANISH
MALDIVIAN
DUTCH
DZONGKHA
ENGLISH
ESPERANTO
ESTONIAN
EWE
FAROESE
FIJIAN
FINNISH
FRENCH
FULAH
GALICIAN
GEORGIAN
GERMAN
GREEK
GUARANI
GUJARATI
HAITIAN
HAUSA
HEBREW
HERERO
HINDI
HIRIMOTU
HUNGARIAN
INTERLINGUA
INDONESIAN
INTERLIGUE
IRISH
IGBO
INUPIAQ
IDO
ICELANDIC
ITALIAN
INUKTITUT
JAPANESE
JAVANESE
GREENLANDIC
KANNADA
KANURI
KASHMIRI
KAZAKH
CENTRALKHMER
KIKUYU
KINYARWANDA
KIRGHIZ
KOMI
KONGO
KOREAN
KURDISH
KUANYAMA
LATIN
LUXEMBOURGISH
GANDA
LIMBURGAN
LINGALA
LAO
LITHUANIAN
LUBAKATANGA
LATVIAN
MANX
MACEDONIAN
MALAGASY
MALAY
MALAYALAM
MALTESE
MAORI
MARATHI
MARSHALLESE
MONGOLIAN
NAURU
NAVAJO
NORTHNDEBELE
NEPALI
NDONGA
NORWEGIANBOKMAL
NORWEGIANNYNORSK
NORWEGIAN
SICHUANYI
SOUTHNDEBELE
OCCITAN
OJIBWA
OLDSLAVONIC
OROMO
ORIYA
OSSETIAN
PANJABI
PALI
PERSIAN
POLISH
PASHTO
PORTUGUESE
QUECHUA
ROMANSH
RUNDI
MOLDAVIAN
RUSSIAN
SANSKRIT
SARDINIAN
SINDHI
NORTHERNSAMI
SAMOAN
SANGO
SERBIAN
GAELIC
SHONA
SINHALESE
SLOVAK
SLOVENIAN
SOMALI
SOUTHERNSOTHO
SPANISH
SUNDANESE
SWAHILI
SWATI
SWEDISH
TAMIL
TELUGU
TAJIK
THAI
TIGRINYA
TIBETAN
TURKMEN
TAGALOG
TSWANA
TONGA
TURKISH
TSONGA
TATAR
TWI
TAHITIAN
UIGHUR
UKRAINIAN
URDU
UZBEK
VENDA
VIETNAMESE
VOLAPUK
WALLOON
WELSH
WOLOF
WESTERNFRISIAN
XHOSA
YIDDISH
YORUBA
ZHUANG
ZULU
UNKNOWN
