### ISSUE TITLE
Bug: Indexation issues on projects that used solr2es

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#933]
**Describe the bug**
For projects that used [solr2es](https://github.com/ICIJ/solr2es) for migration, there are some issues with the indexation of "children" files in elastic search (example: PST file attachments).
- [ ] Child elastic search document has no "rootDocument" attribute so the rootId and docId are the same in the URL

Once we put the proper attribute rootDocument, and follow the link to the "parent document" (PST file), the downloaded document on datashare is different from the one on the server when using the path of the document.
- [ ]  The referenced root document downloaded file does not correspond to the one stored on the server.

**Comment by mvanzalu** [comment]
- [ ] Solution : reindex the documents in question
