### ISSUE TITLE
Datashare is not starting in browser with edge 44 on windows 10

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#952]
**Describe the bug**

When installing on a windows 10 box without having upgraded the browser, it seems edge is in version 44.

and we have the error : 

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
chunk-vendors.chunk-vendors.js (354,40647)
```

When introspecting the JS we can see : 

```javascript
id = validKey(id) || validKey(id.substring(0, 2)) || detLocale; // Add fallback and spread default locale to prevent repetitive update loops

const defLocale = { ...locales['en-IE'],
    ...locales[id],
    id
  }; // Assign or merge defaults with provided config
```
it breaks on the like `defLocale = ...`

**To Reproduce**
1. install and launch datashare on a windows 10 machine
2. it should launch the edge browser 
3. Then the splash window is never exiting
4. in the console there is the above error

**Expected behavior**

Datashare is running.

**Desktop (please complete the following information):**
- OS: Windows 10 family
- Microsoft EdgeHTML 18.17763
- Microsoft Edge 44.17763.1.0

**Comment by pirhoo** [comment]
Current version is `107.0.1418.26`.

We don't fix more than 2 version past the current version.
