### ISSUE TITLE
Path file insted of name file

### ISSUE THREAD

**Issue by MMAAPPUU** [ICIJ/datashare#953]
Hello,

I'm just starting with DATASAHRE few month ago and I have noticed that : 

- In the "search in documents" pannel, insted of the file name "Summary of the report 2022.pdf" for exemple, it is written the path file "C:\User\MAPU\Desktop\File1\ ...." 

After re-instal DATASHARE and browsed into setting the issues is still happening.

Do you have any idea why ?

Thank you and have a nice day

**Comment by pirhoo** [comment]
Hello @MMAAPPUU!

Thanks for reporting the issue. Would you be able to share the PDF with us? Or a screenshot of the page where you see the problem? Thanks!
