### ISSUE TITLE
Improve mac installer

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#954]
**Is your feature request related to a problem? Please describe.**
We often encounter errors or confusion from users with Homebrew installation. 

**Describe the solution you'd like**
To discuss about it.

**Comment by pirhoo** [comment]
After doing some researches, I propose the follow improvements:

* automate `XCode Command Line Tools` installation it's not installed (nor `XCode`) ;
* automate `Homebrew` or `MacPorts` installation if none of them are installed ;
* use either `Homebrew` or `MacPorts` to install `tesseract`, depending on which one is installed ;
* check if Datashare is not already running before starting it again with the launcher ;
* sign Datashare with an [Apple Developer-ID](https://developer.apple.com/developer-id/).
