### ISSUE TITLE
Batch Search instances are frozen without reason

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#956]
**Describe the bug**
On production, one of the users had his batch search stuck in 'QUEUED' state for days.
The reason was both instances appeared to be shutdown since Nov 13 : 
```
2022-11-05 05:17:48.866 | <docker instance 1>
-- | --
Unable to resolve <redis address>
2022-11-03 11:25:36.906 | <docker instance 1>
Elasticsearch connections closed
2022-11-03 11:25:36.903 | <docker instance 1>
Closing Elasticsearch connections
2022-11-03 11:25:36.902 | <docker instance 1>
HikariPool-1 - Shutdown completed.
2022-11-03 11:25:36.881 | <docker instance 1>
HikariPool-1 - Shutdown initiated...
2022-11-03 11:25:36.823 | <docker instance 1>
exiting main loop
2022-11-03 11:25:36.821 | <docker instance 1>
batch search <batch search id> not ran because in state SUCCESS
2022-11-03 11:25:36.812 | <docker instance 1>
done batch search <batch search id>
```
We note that two batch search were submitted and processed just before 'exiting main loop' (it may have triggered the shutdown).
Actually docker instances were still up which means the shutdown isn't completely done.

For now we had to restart docker instances to make them process the queued batch searches

Two questions must be answered : 
- Why does the instances shutdown ?
- Why docker instances are still up even after the shutdown (some threads are still probably running)

**Expected behavior**
Batch search instance isn't supposed to exit by itself, 'QUEUED' batch searches are supposed to be processed if any is 'RUNNING'

**Comment by bamthomas** [comment]
it seems that we are exiting mainloop but redisson client is not properly shutdown so a thread is waiting and we never exit the JVM.

It maybe related to https://github.com/redisson/redisson/issues/1275

**Comment by mvanzalu** [comment]
**How to reproduce**

- Start Datashare on BATCH SEARCH mode
- Send a POISON ("\"poison\"") to the redis queue
- See instance, everything is closed except redis/redisson

**Comment by mvanzalu** [comment]
Linked PR [here](https://github.com/ICIJ/datashare/pull/986) and [here](https://github.com/ICIJ/datashare/pull/989)
