### ISSUE TITLE
Delete all returns 404 error

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#960]
**Describe the bug**
When trying to delete the database on Datashare local mode, a 404 error is returned

**Desktop (please complete the following information):**
 - Version: 10.14.0

**Comment by mvanzalu** [comment]
404 error is returned by delete Batch Search table, if it's empty it returns 404 which is normal.

**Comment by pirhoo** [comment]
So it's not really a bug? We should change the flash message on the front, then.

**Comment by mvanzalu** [comment]
Sure !
