### ISSUE TITLE
Publish ARM docker images of datashare

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#964]
**Is your feature request related to a problem? Please describe.**
In addition to amd docker images, it would be useful to have arm images.

**Comment by pirhoo** [comment]
Open JDK Alpine images are not built for ARM:

https://hub.docker.com/r/adoptopenjdk/openjdk11/tags?page=1&name=alpine

Should we migrate back to ubuntu/debian based image? The need for "lightweight" Docker image is no more since we provide standalone installers.
