### ISSUE TITLE
Consolidate search result with a new tab that child has extracted file

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare#98]
When I index some .eml files (e-mail files), and when it contains an attachment, I get two search results (or more depending on the amount of attachments), one for the parent, the eml body and the extracted child with the attachment.

It feels a bit clunky in the interface, and it clutters the results. I was thinking that adding them to another tab would maybe make more sense?

**Comment by Soliine** [comment]
Thanks a lot for this input! We finally display child documents as attachements of the parent document https://twitter.com/ICIJorg/status/1183095265781268482.

**Comment by DrWhax** [comment]
Thanks so much!
