### ISSUE TITLE
Last step of the tour plugin is broken

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#980]

**Comment by caro3801** [comment]
related to https://github.com/ICIJ/datashare-plugin-tour/compare/2cd533057900b7cfadb4e1380db2dcb0c74ca12f..297e0c303cb5ae8faace8e1613969e829b8ac92d
now released as v0.0.12

**Comment by pirhoo** [comment]
Cool! We should update it here:
https://github.com/ICIJ/datashare/blob/master/datashare-app/src/main/resources/plugins.json#L63

**Comment by caro3801** [comment]
yes! https://github.com/ICIJ/datashare/commit/2e13acab38092de1f9b540af25eda43f928115a0
